package club.doki7.openxr.enumtype;

import club.doki7.ffm.annotation.*;

/// @see <a href="https://registry.khronos.org/OpenXR/specs/1.1/man/html/XrBodyJointFB.html"><code>XrBodyJointFB</code></a>
public final class XrBodyJointFB {
    public static final int ROOT = 0x0;
    public static final int HIPS = 0x1;
    public static final int SPINE_LOWER = 0x2;
    public static final int SPINE_MIDDLE = 0x3;
    public static final int SPINE_UPPER = 0x4;
    public static final int CHEST = 0x5;
    public static final int NECK = 0x6;
    public static final int HEAD = 0x7;
    public static final int LEFT_SHOULDER = 0x8;
    public static final int LEFT_SCAPULA = 0x9;
    public static final int LEFT_ARM_UPPER = 0xa;
    public static final int LEFT_ARM_LOWER = 0xb;
    public static final int LEFT_HAND_WRIST_TWIST = 0xc;
    public static final int RIGHT_SHOULDER = 0xd;
    public static final int RIGHT_SCAPULA = 0xe;
    public static final int RIGHT_ARM_UPPER = 0xf;
    public static final int RIGHT_ARM_LOWER = 0x10;
    public static final int RIGHT_HAND_WRIST_TWIST = 0x11;
    public static final int LEFT_HAND_PALM = 0x12;
    public static final int LEFT_HAND_WRIST = 0x13;
    public static final int LEFT_HAND_THUMB_METACARPAL = 0x14;
    public static final int LEFT_HAND_THUMB_PROXIMAL = 0x15;
    public static final int LEFT_HAND_THUMB_DISTAL = 0x16;
    public static final int LEFT_HAND_THUMB_TIP = 0x17;
    public static final int LEFT_HAND_INDEX_METACARPAL = 0x18;
    public static final int LEFT_HAND_INDEX_PROXIMAL = 0x19;
    public static final int LEFT_HAND_INDEX_INTERMEDIATE = 0x1a;
    public static final int LEFT_HAND_INDEX_DISTAL = 0x1b;
    public static final int LEFT_HAND_INDEX_TIP = 0x1c;
    public static final int LEFT_HAND_MIDDLE_METACARPAL = 0x1d;
    public static final int LEFT_HAND_MIDDLE_PROXIMAL = 0x1e;
    public static final int LEFT_HAND_MIDDLE_INTERMEDIATE = 0x1f;
    public static final int LEFT_HAND_MIDDLE_DISTAL = 0x20;
    public static final int LEFT_HAND_MIDDLE_TIP = 0x21;
    public static final int LEFT_HAND_RING_METACARPAL = 0x22;
    public static final int LEFT_HAND_RING_PROXIMAL = 0x23;
    public static final int LEFT_HAND_RING_INTERMEDIATE = 0x24;
    public static final int LEFT_HAND_RING_DISTAL = 0x25;
    public static final int LEFT_HAND_RING_TIP = 0x26;
    public static final int LEFT_HAND_LITTLE_METACARPAL = 0x27;
    public static final int LEFT_HAND_LITTLE_PROXIMAL = 0x28;
    public static final int LEFT_HAND_LITTLE_INTERMEDIATE = 0x29;
    public static final int LEFT_HAND_LITTLE_DISTAL = 0x2a;
    public static final int LEFT_HAND_LITTLE_TIP = 0x2b;
    public static final int RIGHT_HAND_PALM = 0x2c;
    public static final int RIGHT_HAND_WRIST = 0x2d;
    public static final int RIGHT_HAND_THUMB_METACARPAL = 0x2e;
    public static final int RIGHT_HAND_THUMB_PROXIMAL = 0x2f;
    public static final int RIGHT_HAND_THUMB_DISTAL = 0x30;
    public static final int RIGHT_HAND_THUMB_TIP = 0x31;
    public static final int RIGHT_HAND_INDEX_METACARPAL = 0x32;
    public static final int RIGHT_HAND_INDEX_PROXIMAL = 0x33;
    public static final int RIGHT_HAND_INDEX_INTERMEDIATE = 0x34;
    public static final int RIGHT_HAND_INDEX_DISTAL = 0x35;
    public static final int RIGHT_HAND_INDEX_TIP = 0x36;
    public static final int RIGHT_HAND_MIDDLE_METACARPAL = 0x37;
    public static final int RIGHT_HAND_MIDDLE_PROXIMAL = 0x38;
    public static final int RIGHT_HAND_MIDDLE_INTERMEDIATE = 0x39;
    public static final int RIGHT_HAND_MIDDLE_DISTAL = 0x3a;
    public static final int RIGHT_HAND_MIDDLE_TIP = 0x3b;
    public static final int RIGHT_HAND_RING_METACARPAL = 0x3c;
    public static final int RIGHT_HAND_RING_PROXIMAL = 0x3d;
    public static final int RIGHT_HAND_RING_INTERMEDIATE = 0x3e;
    public static final int RIGHT_HAND_RING_DISTAL = 0x3f;
    public static final int RIGHT_HAND_RING_TIP = 0x40;
    public static final int RIGHT_HAND_LITTLE_METACARPAL = 0x41;
    public static final int RIGHT_HAND_LITTLE_PROXIMAL = 0x42;
    public static final int RIGHT_HAND_LITTLE_INTERMEDIATE = 0x43;
    public static final int RIGHT_HAND_LITTLE_DISTAL = 0x44;
    public static final int RIGHT_HAND_LITTLE_TIP = 0x45;
    public static final int COUNT = 0x46;
    public static final int NONE = 0xffffffff;

    public static String explain(@EnumType(XrBodyJointFB.class) int value) {
        return switch (value) {
            case XrBodyJointFB.CHEST -> "XR_BODY_JOINT_CHEST_FB";
            case XrBodyJointFB.COUNT -> "XR_BODY_JOINT_COUNT_FB";
            case XrBodyJointFB.HEAD -> "XR_BODY_JOINT_HEAD_FB";
            case XrBodyJointFB.HIPS -> "XR_BODY_JOINT_HIPS_FB";
            case XrBodyJointFB.LEFT_ARM_LOWER -> "XR_BODY_JOINT_LEFT_ARM_LOWER_FB";
            case XrBodyJointFB.LEFT_ARM_UPPER -> "XR_BODY_JOINT_LEFT_ARM_UPPER_FB";
            case XrBodyJointFB.LEFT_HAND_INDEX_DISTAL -> "XR_BODY_JOINT_LEFT_HAND_INDEX_DISTAL_FB";
            case XrBodyJointFB.LEFT_HAND_INDEX_INTERMEDIATE -> "XR_BODY_JOINT_LEFT_HAND_INDEX_INTERMEDIATE_FB";
            case XrBodyJointFB.LEFT_HAND_INDEX_METACARPAL -> "XR_BODY_JOINT_LEFT_HAND_INDEX_METACARPAL_FB";
            case XrBodyJointFB.LEFT_HAND_INDEX_PROXIMAL -> "XR_BODY_JOINT_LEFT_HAND_INDEX_PROXIMAL_FB";
            case XrBodyJointFB.LEFT_HAND_INDEX_TIP -> "XR_BODY_JOINT_LEFT_HAND_INDEX_TIP_FB";
            case XrBodyJointFB.LEFT_HAND_LITTLE_DISTAL -> "XR_BODY_JOINT_LEFT_HAND_LITTLE_DISTAL_FB";
            case XrBodyJointFB.LEFT_HAND_LITTLE_INTERMEDIATE -> "XR_BODY_JOINT_LEFT_HAND_LITTLE_INTERMEDIATE_FB";
            case XrBodyJointFB.LEFT_HAND_LITTLE_METACARPAL -> "XR_BODY_JOINT_LEFT_HAND_LITTLE_METACARPAL_FB";
            case XrBodyJointFB.LEFT_HAND_LITTLE_PROXIMAL -> "XR_BODY_JOINT_LEFT_HAND_LITTLE_PROXIMAL_FB";
            case XrBodyJointFB.LEFT_HAND_LITTLE_TIP -> "XR_BODY_JOINT_LEFT_HAND_LITTLE_TIP_FB";
            case XrBodyJointFB.LEFT_HAND_MIDDLE_DISTAL -> "XR_BODY_JOINT_LEFT_HAND_MIDDLE_DISTAL_FB";
            case XrBodyJointFB.LEFT_HAND_MIDDLE_INTERMEDIATE -> "XR_BODY_JOINT_LEFT_HAND_MIDDLE_INTERMEDIATE_FB";
            case XrBodyJointFB.LEFT_HAND_MIDDLE_METACARPAL -> "XR_BODY_JOINT_LEFT_HAND_MIDDLE_METACARPAL_FB";
            case XrBodyJointFB.LEFT_HAND_MIDDLE_PROXIMAL -> "XR_BODY_JOINT_LEFT_HAND_MIDDLE_PROXIMAL_FB";
            case XrBodyJointFB.LEFT_HAND_MIDDLE_TIP -> "XR_BODY_JOINT_LEFT_HAND_MIDDLE_TIP_FB";
            case XrBodyJointFB.LEFT_HAND_PALM -> "XR_BODY_JOINT_LEFT_HAND_PALM_FB";
            case XrBodyJointFB.LEFT_HAND_RING_DISTAL -> "XR_BODY_JOINT_LEFT_HAND_RING_DISTAL_FB";
            case XrBodyJointFB.LEFT_HAND_RING_INTERMEDIATE -> "XR_BODY_JOINT_LEFT_HAND_RING_INTERMEDIATE_FB";
            case XrBodyJointFB.LEFT_HAND_RING_METACARPAL -> "XR_BODY_JOINT_LEFT_HAND_RING_METACARPAL_FB";
            case XrBodyJointFB.LEFT_HAND_RING_PROXIMAL -> "XR_BODY_JOINT_LEFT_HAND_RING_PROXIMAL_FB";
            case XrBodyJointFB.LEFT_HAND_RING_TIP -> "XR_BODY_JOINT_LEFT_HAND_RING_TIP_FB";
            case XrBodyJointFB.LEFT_HAND_THUMB_DISTAL -> "XR_BODY_JOINT_LEFT_HAND_THUMB_DISTAL_FB";
            case XrBodyJointFB.LEFT_HAND_THUMB_METACARPAL -> "XR_BODY_JOINT_LEFT_HAND_THUMB_METACARPAL_FB";
            case XrBodyJointFB.LEFT_HAND_THUMB_PROXIMAL -> "XR_BODY_JOINT_LEFT_HAND_THUMB_PROXIMAL_FB";
            case XrBodyJointFB.LEFT_HAND_THUMB_TIP -> "XR_BODY_JOINT_LEFT_HAND_THUMB_TIP_FB";
            case XrBodyJointFB.LEFT_HAND_WRIST -> "XR_BODY_JOINT_LEFT_HAND_WRIST_FB";
            case XrBodyJointFB.LEFT_HAND_WRIST_TWIST -> "XR_BODY_JOINT_LEFT_HAND_WRIST_TWIST_FB";
            case XrBodyJointFB.LEFT_SCAPULA -> "XR_BODY_JOINT_LEFT_SCAPULA_FB";
            case XrBodyJointFB.LEFT_SHOULDER -> "XR_BODY_JOINT_LEFT_SHOULDER_FB";
            case XrBodyJointFB.NECK -> "XR_BODY_JOINT_NECK_FB";
            case XrBodyJointFB.NONE -> "XR_BODY_JOINT_NONE_FB";
            case XrBodyJointFB.RIGHT_ARM_LOWER -> "XR_BODY_JOINT_RIGHT_ARM_LOWER_FB";
            case XrBodyJointFB.RIGHT_ARM_UPPER -> "XR_BODY_JOINT_RIGHT_ARM_UPPER_FB";
            case XrBodyJointFB.RIGHT_HAND_INDEX_DISTAL -> "XR_BODY_JOINT_RIGHT_HAND_INDEX_DISTAL_FB";
            case XrBodyJointFB.RIGHT_HAND_INDEX_INTERMEDIATE -> "XR_BODY_JOINT_RIGHT_HAND_INDEX_INTERMEDIATE_FB";
            case XrBodyJointFB.RIGHT_HAND_INDEX_METACARPAL -> "XR_BODY_JOINT_RIGHT_HAND_INDEX_METACARPAL_FB";
            case XrBodyJointFB.RIGHT_HAND_INDEX_PROXIMAL -> "XR_BODY_JOINT_RIGHT_HAND_INDEX_PROXIMAL_FB";
            case XrBodyJointFB.RIGHT_HAND_INDEX_TIP -> "XR_BODY_JOINT_RIGHT_HAND_INDEX_TIP_FB";
            case XrBodyJointFB.RIGHT_HAND_LITTLE_DISTAL -> "XR_BODY_JOINT_RIGHT_HAND_LITTLE_DISTAL_FB";
            case XrBodyJointFB.RIGHT_HAND_LITTLE_INTERMEDIATE -> "XR_BODY_JOINT_RIGHT_HAND_LITTLE_INTERMEDIATE_FB";
            case XrBodyJointFB.RIGHT_HAND_LITTLE_METACARPAL -> "XR_BODY_JOINT_RIGHT_HAND_LITTLE_METACARPAL_FB";
            case XrBodyJointFB.RIGHT_HAND_LITTLE_PROXIMAL -> "XR_BODY_JOINT_RIGHT_HAND_LITTLE_PROXIMAL_FB";
            case XrBodyJointFB.RIGHT_HAND_LITTLE_TIP -> "XR_BODY_JOINT_RIGHT_HAND_LITTLE_TIP_FB";
            case XrBodyJointFB.RIGHT_HAND_MIDDLE_DISTAL -> "XR_BODY_JOINT_RIGHT_HAND_MIDDLE_DISTAL_FB";
            case XrBodyJointFB.RIGHT_HAND_MIDDLE_INTERMEDIATE -> "XR_BODY_JOINT_RIGHT_HAND_MIDDLE_INTERMEDIATE_FB";
            case XrBodyJointFB.RIGHT_HAND_MIDDLE_METACARPAL -> "XR_BODY_JOINT_RIGHT_HAND_MIDDLE_METACARPAL_FB";
            case XrBodyJointFB.RIGHT_HAND_MIDDLE_PROXIMAL -> "XR_BODY_JOINT_RIGHT_HAND_MIDDLE_PROXIMAL_FB";
            case XrBodyJointFB.RIGHT_HAND_MIDDLE_TIP -> "XR_BODY_JOINT_RIGHT_HAND_MIDDLE_TIP_FB";
            case XrBodyJointFB.RIGHT_HAND_PALM -> "XR_BODY_JOINT_RIGHT_HAND_PALM_FB";
            case XrBodyJointFB.RIGHT_HAND_RING_DISTAL -> "XR_BODY_JOINT_RIGHT_HAND_RING_DISTAL_FB";
            case XrBodyJointFB.RIGHT_HAND_RING_INTERMEDIATE -> "XR_BODY_JOINT_RIGHT_HAND_RING_INTERMEDIATE_FB";
            case XrBodyJointFB.RIGHT_HAND_RING_METACARPAL -> "XR_BODY_JOINT_RIGHT_HAND_RING_METACARPAL_FB";
            case XrBodyJointFB.RIGHT_HAND_RING_PROXIMAL -> "XR_BODY_JOINT_RIGHT_HAND_RING_PROXIMAL_FB";
            case XrBodyJointFB.RIGHT_HAND_RING_TIP -> "XR_BODY_JOINT_RIGHT_HAND_RING_TIP_FB";
            case XrBodyJointFB.RIGHT_HAND_THUMB_DISTAL -> "XR_BODY_JOINT_RIGHT_HAND_THUMB_DISTAL_FB";
            case XrBodyJointFB.RIGHT_HAND_THUMB_METACARPAL -> "XR_BODY_JOINT_RIGHT_HAND_THUMB_METACARPAL_FB";
            case XrBodyJointFB.RIGHT_HAND_THUMB_PROXIMAL -> "XR_BODY_JOINT_RIGHT_HAND_THUMB_PROXIMAL_FB";
            case XrBodyJointFB.RIGHT_HAND_THUMB_TIP -> "XR_BODY_JOINT_RIGHT_HAND_THUMB_TIP_FB";
            case XrBodyJointFB.RIGHT_HAND_WRIST -> "XR_BODY_JOINT_RIGHT_HAND_WRIST_FB";
            case XrBodyJointFB.RIGHT_HAND_WRIST_TWIST -> "XR_BODY_JOINT_RIGHT_HAND_WRIST_TWIST_FB";
            case XrBodyJointFB.RIGHT_SCAPULA -> "XR_BODY_JOINT_RIGHT_SCAPULA_FB";
            case XrBodyJointFB.RIGHT_SHOULDER -> "XR_BODY_JOINT_RIGHT_SHOULDER_FB";
            case XrBodyJointFB.ROOT -> "XR_BODY_JOINT_ROOT_FB";
            case XrBodyJointFB.SPINE_LOWER -> "XR_BODY_JOINT_SPINE_LOWER_FB";
            case XrBodyJointFB.SPINE_MIDDLE -> "XR_BODY_JOINT_SPINE_MIDDLE_FB";
            case XrBodyJointFB.SPINE_UPPER -> "XR_BODY_JOINT_SPINE_UPPER_FB";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private XrBodyJointFB() {}
}
