package club.doki7.openxr.enumtype;

import club.doki7.ffm.annotation.*;

/// @see <a href="https://registry.khronos.org/OpenXR/specs/1.1/man/html/XrFaceExpression2FB.html"><code>XrFaceExpression2FB</code></a>
public final class XrFaceExpression2FB {
    public static final int BROW_LOWERER_L = 0x0;
    public static final int BROW_LOWERER_R = 0x1;
    public static final int CHEEK_PUFF_L = 0x2;
    public static final int CHEEK_PUFF_R = 0x3;
    public static final int CHEEK_RAISER_L = 0x4;
    public static final int CHEEK_RAISER_R = 0x5;
    public static final int CHEEK_SUCK_L = 0x6;
    public static final int CHEEK_SUCK_R = 0x7;
    public static final int CHIN_RAISER_B = 0x8;
    public static final int CHIN_RAISER_T = 0x9;
    public static final int DIMPLER_L = 0xa;
    public static final int DIMPLER_R = 0xb;
    public static final int EYES_CLOSED_L = 0xc;
    public static final int EYES_CLOSED_R = 0xd;
    public static final int EYES_LOOK_DOWN_L = 0xe;
    public static final int EYES_LOOK_DOWN_R = 0xf;
    public static final int EYES_LOOK_LEFT_L = 0x10;
    public static final int EYES_LOOK_LEFT_R = 0x11;
    public static final int EYES_LOOK_RIGHT_L = 0x12;
    public static final int EYES_LOOK_RIGHT_R = 0x13;
    public static final int EYES_LOOK_UP_L = 0x14;
    public static final int EYES_LOOK_UP_R = 0x15;
    public static final int INNER_BROW_RAISER_L = 0x16;
    public static final int INNER_BROW_RAISER_R = 0x17;
    public static final int JAW_DROP = 0x18;
    public static final int JAW_SIDEWAYS_LEFT = 0x19;
    public static final int JAW_SIDEWAYS_RIGHT = 0x1a;
    public static final int JAW_THRUST = 0x1b;
    public static final int LID_TIGHTENER_L = 0x1c;
    public static final int LID_TIGHTENER_R = 0x1d;
    public static final int LIP_CORNER_DEPRESSOR_L = 0x1e;
    public static final int LIP_CORNER_DEPRESSOR_R = 0x1f;
    public static final int LIP_CORNER_PULLER_L = 0x20;
    public static final int LIP_CORNER_PULLER_R = 0x21;
    public static final int LIP_FUNNELER_LB = 0x22;
    public static final int LIP_FUNNELER_LT = 0x23;
    public static final int LIP_FUNNELER_RB = 0x24;
    public static final int LIP_FUNNELER_RT = 0x25;
    public static final int LIP_PRESSOR_L = 0x26;
    public static final int LIP_PRESSOR_R = 0x27;
    public static final int LIP_PUCKER_L = 0x28;
    public static final int LIP_PUCKER_R = 0x29;
    public static final int LIP_STRETCHER_L = 0x2a;
    public static final int LIP_STRETCHER_R = 0x2b;
    public static final int LIP_SUCK_LB = 0x2c;
    public static final int LIP_SUCK_LT = 0x2d;
    public static final int LIP_SUCK_RB = 0x2e;
    public static final int LIP_SUCK_RT = 0x2f;
    public static final int LIP_TIGHTENER_L = 0x30;
    public static final int LIP_TIGHTENER_R = 0x31;
    public static final int LIPS_TOWARD = 0x32;
    public static final int LOWER_LIP_DEPRESSOR_L = 0x33;
    public static final int LOWER_LIP_DEPRESSOR_R = 0x34;
    public static final int MOUTH_LEFT = 0x35;
    public static final int MOUTH_RIGHT = 0x36;
    public static final int NOSE_WRINKLER_L = 0x37;
    public static final int NOSE_WRINKLER_R = 0x38;
    public static final int OUTER_BROW_RAISER_L = 0x39;
    public static final int OUTER_BROW_RAISER_R = 0x3a;
    public static final int UPPER_LID_RAISER_L = 0x3b;
    public static final int UPPER_LID_RAISER_R = 0x3c;
    public static final int UPPER_LIP_RAISER_L = 0x3d;
    public static final int UPPER_LIP_RAISER_R = 0x3e;
    public static final int TONGUE_TIP_INTERDENTAL = 0x3f;
    public static final int TONGUE_TIP_ALVEOLAR = 0x40;
    public static final int TONGUE_FRONT_DORSAL_PALATE = 0x41;
    public static final int TONGUE_MID_DORSAL_PALATE = 0x42;
    public static final int TONGUE_BACK_DORSAL_VELAR = 0x43;
    public static final int TONGUE_OUT = 0x44;
    public static final int TONGUE_RETREAT = 0x45;
    public static final int COUNT = 0x46;

    public static String explain(@EnumType(XrFaceExpression2FB.class) int value) {
        return switch (value) {
            case XrFaceExpression2FB.BROW_LOWERER_L -> "XR_FACE_EXPRESSION2_BROW_LOWERER_L_FB";
            case XrFaceExpression2FB.BROW_LOWERER_R -> "XR_FACE_EXPRESSION2_BROW_LOWERER_R_FB";
            case XrFaceExpression2FB.CHEEK_PUFF_L -> "XR_FACE_EXPRESSION2_CHEEK_PUFF_L_FB";
            case XrFaceExpression2FB.CHEEK_PUFF_R -> "XR_FACE_EXPRESSION2_CHEEK_PUFF_R_FB";
            case XrFaceExpression2FB.CHEEK_RAISER_L -> "XR_FACE_EXPRESSION2_CHEEK_RAISER_L_FB";
            case XrFaceExpression2FB.CHEEK_RAISER_R -> "XR_FACE_EXPRESSION2_CHEEK_RAISER_R_FB";
            case XrFaceExpression2FB.CHEEK_SUCK_L -> "XR_FACE_EXPRESSION2_CHEEK_SUCK_L_FB";
            case XrFaceExpression2FB.CHEEK_SUCK_R -> "XR_FACE_EXPRESSION2_CHEEK_SUCK_R_FB";
            case XrFaceExpression2FB.CHIN_RAISER_B -> "XR_FACE_EXPRESSION2_CHIN_RAISER_B_FB";
            case XrFaceExpression2FB.CHIN_RAISER_T -> "XR_FACE_EXPRESSION2_CHIN_RAISER_T_FB";
            case XrFaceExpression2FB.COUNT -> "XR_FACE_EXPRESSION2_COUNT_FB";
            case XrFaceExpression2FB.DIMPLER_L -> "XR_FACE_EXPRESSION2_DIMPLER_L_FB";
            case XrFaceExpression2FB.DIMPLER_R -> "XR_FACE_EXPRESSION2_DIMPLER_R_FB";
            case XrFaceExpression2FB.EYES_CLOSED_L -> "XR_FACE_EXPRESSION2_EYES_CLOSED_L_FB";
            case XrFaceExpression2FB.EYES_CLOSED_R -> "XR_FACE_EXPRESSION2_EYES_CLOSED_R_FB";
            case XrFaceExpression2FB.EYES_LOOK_DOWN_L -> "XR_FACE_EXPRESSION2_EYES_LOOK_DOWN_L_FB";
            case XrFaceExpression2FB.EYES_LOOK_DOWN_R -> "XR_FACE_EXPRESSION2_EYES_LOOK_DOWN_R_FB";
            case XrFaceExpression2FB.EYES_LOOK_LEFT_L -> "XR_FACE_EXPRESSION2_EYES_LOOK_LEFT_L_FB";
            case XrFaceExpression2FB.EYES_LOOK_LEFT_R -> "XR_FACE_EXPRESSION2_EYES_LOOK_LEFT_R_FB";
            case XrFaceExpression2FB.EYES_LOOK_RIGHT_L -> "XR_FACE_EXPRESSION2_EYES_LOOK_RIGHT_L_FB";
            case XrFaceExpression2FB.EYES_LOOK_RIGHT_R -> "XR_FACE_EXPRESSION2_EYES_LOOK_RIGHT_R_FB";
            case XrFaceExpression2FB.EYES_LOOK_UP_L -> "XR_FACE_EXPRESSION2_EYES_LOOK_UP_L_FB";
            case XrFaceExpression2FB.EYES_LOOK_UP_R -> "XR_FACE_EXPRESSION2_EYES_LOOK_UP_R_FB";
            case XrFaceExpression2FB.INNER_BROW_RAISER_L -> "XR_FACE_EXPRESSION2_INNER_BROW_RAISER_L_FB";
            case XrFaceExpression2FB.INNER_BROW_RAISER_R -> "XR_FACE_EXPRESSION2_INNER_BROW_RAISER_R_FB";
            case XrFaceExpression2FB.JAW_DROP -> "XR_FACE_EXPRESSION2_JAW_DROP_FB";
            case XrFaceExpression2FB.JAW_SIDEWAYS_LEFT -> "XR_FACE_EXPRESSION2_JAW_SIDEWAYS_LEFT_FB";
            case XrFaceExpression2FB.JAW_SIDEWAYS_RIGHT -> "XR_FACE_EXPRESSION2_JAW_SIDEWAYS_RIGHT_FB";
            case XrFaceExpression2FB.JAW_THRUST -> "XR_FACE_EXPRESSION2_JAW_THRUST_FB";
            case XrFaceExpression2FB.LID_TIGHTENER_L -> "XR_FACE_EXPRESSION2_LID_TIGHTENER_L_FB";
            case XrFaceExpression2FB.LID_TIGHTENER_R -> "XR_FACE_EXPRESSION2_LID_TIGHTENER_R_FB";
            case XrFaceExpression2FB.LIPS_TOWARD -> "XR_FACE_EXPRESSION2_LIPS_TOWARD_FB";
            case XrFaceExpression2FB.LIP_CORNER_DEPRESSOR_L -> "XR_FACE_EXPRESSION2_LIP_CORNER_DEPRESSOR_L_FB";
            case XrFaceExpression2FB.LIP_CORNER_DEPRESSOR_R -> "XR_FACE_EXPRESSION2_LIP_CORNER_DEPRESSOR_R_FB";
            case XrFaceExpression2FB.LIP_CORNER_PULLER_L -> "XR_FACE_EXPRESSION2_LIP_CORNER_PULLER_L_FB";
            case XrFaceExpression2FB.LIP_CORNER_PULLER_R -> "XR_FACE_EXPRESSION2_LIP_CORNER_PULLER_R_FB";
            case XrFaceExpression2FB.LIP_FUNNELER_LB -> "XR_FACE_EXPRESSION2_LIP_FUNNELER_LB_FB";
            case XrFaceExpression2FB.LIP_FUNNELER_LT -> "XR_FACE_EXPRESSION2_LIP_FUNNELER_LT_FB";
            case XrFaceExpression2FB.LIP_FUNNELER_RB -> "XR_FACE_EXPRESSION2_LIP_FUNNELER_RB_FB";
            case XrFaceExpression2FB.LIP_FUNNELER_RT -> "XR_FACE_EXPRESSION2_LIP_FUNNELER_RT_FB";
            case XrFaceExpression2FB.LIP_PRESSOR_L -> "XR_FACE_EXPRESSION2_LIP_PRESSOR_L_FB";
            case XrFaceExpression2FB.LIP_PRESSOR_R -> "XR_FACE_EXPRESSION2_LIP_PRESSOR_R_FB";
            case XrFaceExpression2FB.LIP_PUCKER_L -> "XR_FACE_EXPRESSION2_LIP_PUCKER_L_FB";
            case XrFaceExpression2FB.LIP_PUCKER_R -> "XR_FACE_EXPRESSION2_LIP_PUCKER_R_FB";
            case XrFaceExpression2FB.LIP_STRETCHER_L -> "XR_FACE_EXPRESSION2_LIP_STRETCHER_L_FB";
            case XrFaceExpression2FB.LIP_STRETCHER_R -> "XR_FACE_EXPRESSION2_LIP_STRETCHER_R_FB";
            case XrFaceExpression2FB.LIP_SUCK_LB -> "XR_FACE_EXPRESSION2_LIP_SUCK_LB_FB";
            case XrFaceExpression2FB.LIP_SUCK_LT -> "XR_FACE_EXPRESSION2_LIP_SUCK_LT_FB";
            case XrFaceExpression2FB.LIP_SUCK_RB -> "XR_FACE_EXPRESSION2_LIP_SUCK_RB_FB";
            case XrFaceExpression2FB.LIP_SUCK_RT -> "XR_FACE_EXPRESSION2_LIP_SUCK_RT_FB";
            case XrFaceExpression2FB.LIP_TIGHTENER_L -> "XR_FACE_EXPRESSION2_LIP_TIGHTENER_L_FB";
            case XrFaceExpression2FB.LIP_TIGHTENER_R -> "XR_FACE_EXPRESSION2_LIP_TIGHTENER_R_FB";
            case XrFaceExpression2FB.LOWER_LIP_DEPRESSOR_L -> "XR_FACE_EXPRESSION2_LOWER_LIP_DEPRESSOR_L_FB";
            case XrFaceExpression2FB.LOWER_LIP_DEPRESSOR_R -> "XR_FACE_EXPRESSION2_LOWER_LIP_DEPRESSOR_R_FB";
            case XrFaceExpression2FB.MOUTH_LEFT -> "XR_FACE_EXPRESSION2_MOUTH_LEFT_FB";
            case XrFaceExpression2FB.MOUTH_RIGHT -> "XR_FACE_EXPRESSION2_MOUTH_RIGHT_FB";
            case XrFaceExpression2FB.NOSE_WRINKLER_L -> "XR_FACE_EXPRESSION2_NOSE_WRINKLER_L_FB";
            case XrFaceExpression2FB.NOSE_WRINKLER_R -> "XR_FACE_EXPRESSION2_NOSE_WRINKLER_R_FB";
            case XrFaceExpression2FB.OUTER_BROW_RAISER_L -> "XR_FACE_EXPRESSION2_OUTER_BROW_RAISER_L_FB";
            case XrFaceExpression2FB.OUTER_BROW_RAISER_R -> "XR_FACE_EXPRESSION2_OUTER_BROW_RAISER_R_FB";
            case XrFaceExpression2FB.TONGUE_BACK_DORSAL_VELAR -> "XR_FACE_EXPRESSION2_TONGUE_BACK_DORSAL_VELAR_FB";
            case XrFaceExpression2FB.TONGUE_FRONT_DORSAL_PALATE -> "XR_FACE_EXPRESSION2_TONGUE_FRONT_DORSAL_PALATE_FB";
            case XrFaceExpression2FB.TONGUE_MID_DORSAL_PALATE -> "XR_FACE_EXPRESSION2_TONGUE_MID_DORSAL_PALATE_FB";
            case XrFaceExpression2FB.TONGUE_OUT -> "XR_FACE_EXPRESSION2_TONGUE_OUT_FB";
            case XrFaceExpression2FB.TONGUE_RETREAT -> "XR_FACE_EXPRESSION2_TONGUE_RETREAT_FB";
            case XrFaceExpression2FB.TONGUE_TIP_ALVEOLAR -> "XR_FACE_EXPRESSION2_TONGUE_TIP_ALVEOLAR_FB";
            case XrFaceExpression2FB.TONGUE_TIP_INTERDENTAL -> "XR_FACE_EXPRESSION2_TONGUE_TIP_INTERDENTAL_FB";
            case XrFaceExpression2FB.UPPER_LID_RAISER_L -> "XR_FACE_EXPRESSION2_UPPER_LID_RAISER_L_FB";
            case XrFaceExpression2FB.UPPER_LID_RAISER_R -> "XR_FACE_EXPRESSION2_UPPER_LID_RAISER_R_FB";
            case XrFaceExpression2FB.UPPER_LIP_RAISER_L -> "XR_FACE_EXPRESSION2_UPPER_LIP_RAISER_L_FB";
            case XrFaceExpression2FB.UPPER_LIP_RAISER_R -> "XR_FACE_EXPRESSION2_UPPER_LIP_RAISER_R_FB";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private XrFaceExpression2FB() {}
}
