package club.doki7.openxr.enumtype;

import club.doki7.ffm.annotation.*;

/// @see <a href="https://registry.khronos.org/OpenXR/specs/1.1/man/html/XrFullBodyJointMETA.html"><code>XrFullBodyJointMETA</code></a>
public final class XrFullBodyJointMETA {
    public static final int ROOT = 0x0;
    public static final int HIPS = 0x1;
    public static final int SPINE_LOWER = 0x2;
    public static final int SPINE_MIDDLE = 0x3;
    public static final int SPINE_UPPER = 0x4;
    public static final int CHEST = 0x5;
    public static final int NECK = 0x6;
    public static final int HEAD = 0x7;
    public static final int LEFT_SHOULDER = 0x8;
    public static final int LEFT_SCAPULA = 0x9;
    public static final int LEFT_ARM_UPPER = 0xa;
    public static final int LEFT_ARM_LOWER = 0xb;
    public static final int LEFT_HAND_WRIST_TWIST = 0xc;
    public static final int RIGHT_SHOULDER = 0xd;
    public static final int RIGHT_SCAPULA = 0xe;
    public static final int RIGHT_ARM_UPPER = 0xf;
    public static final int RIGHT_ARM_LOWER = 0x10;
    public static final int RIGHT_HAND_WRIST_TWIST = 0x11;
    public static final int LEFT_HAND_PALM = 0x12;
    public static final int LEFT_HAND_WRIST = 0x13;
    public static final int LEFT_HAND_THUMB_METACARPAL = 0x14;
    public static final int LEFT_HAND_THUMB_PROXIMAL = 0x15;
    public static final int LEFT_HAND_THUMB_DISTAL = 0x16;
    public static final int LEFT_HAND_THUMB_TIP = 0x17;
    public static final int LEFT_HAND_INDEX_METACARPAL = 0x18;
    public static final int LEFT_HAND_INDEX_PROXIMAL = 0x19;
    public static final int LEFT_HAND_INDEX_INTERMEDIATE = 0x1a;
    public static final int LEFT_HAND_INDEX_DISTAL = 0x1b;
    public static final int LEFT_HAND_INDEX_TIP = 0x1c;
    public static final int LEFT_HAND_MIDDLE_METACARPAL = 0x1d;
    public static final int LEFT_HAND_MIDDLE_PROXIMAL = 0x1e;
    public static final int LEFT_HAND_MIDDLE_INTERMEDIATE = 0x1f;
    public static final int LEFT_HAND_MIDDLE_DISTAL = 0x20;
    public static final int LEFT_HAND_MIDDLE_TIP = 0x21;
    public static final int LEFT_HAND_RING_METACARPAL = 0x22;
    public static final int LEFT_HAND_RING_PROXIMAL = 0x23;
    public static final int LEFT_HAND_RING_INTERMEDIATE = 0x24;
    public static final int LEFT_HAND_RING_DISTAL = 0x25;
    public static final int LEFT_HAND_RING_TIP = 0x26;
    public static final int LEFT_HAND_LITTLE_METACARPAL = 0x27;
    public static final int LEFT_HAND_LITTLE_PROXIMAL = 0x28;
    public static final int LEFT_HAND_LITTLE_INTERMEDIATE = 0x29;
    public static final int LEFT_HAND_LITTLE_DISTAL = 0x2a;
    public static final int LEFT_HAND_LITTLE_TIP = 0x2b;
    public static final int RIGHT_HAND_PALM = 0x2c;
    public static final int RIGHT_HAND_WRIST = 0x2d;
    public static final int RIGHT_HAND_THUMB_METACARPAL = 0x2e;
    public static final int RIGHT_HAND_THUMB_PROXIMAL = 0x2f;
    public static final int RIGHT_HAND_THUMB_DISTAL = 0x30;
    public static final int RIGHT_HAND_THUMB_TIP = 0x31;
    public static final int RIGHT_HAND_INDEX_METACARPAL = 0x32;
    public static final int RIGHT_HAND_INDEX_PROXIMAL = 0x33;
    public static final int RIGHT_HAND_INDEX_INTERMEDIATE = 0x34;
    public static final int RIGHT_HAND_INDEX_DISTAL = 0x35;
    public static final int RIGHT_HAND_INDEX_TIP = 0x36;
    public static final int RIGHT_HAND_MIDDLE_METACARPAL = 0x37;
    public static final int RIGHT_HAND_MIDDLE_PROXIMAL = 0x38;
    public static final int RIGHT_HAND_MIDDLE_INTERMEDIATE = 0x39;
    public static final int RIGHT_HAND_MIDDLE_DISTAL = 0x3a;
    public static final int RIGHT_HAND_MIDDLE_TIP = 0x3b;
    public static final int RIGHT_HAND_RING_METACARPAL = 0x3c;
    public static final int RIGHT_HAND_RING_PROXIMAL = 0x3d;
    public static final int RIGHT_HAND_RING_INTERMEDIATE = 0x3e;
    public static final int RIGHT_HAND_RING_DISTAL = 0x3f;
    public static final int RIGHT_HAND_RING_TIP = 0x40;
    public static final int RIGHT_HAND_LITTLE_METACARPAL = 0x41;
    public static final int RIGHT_HAND_LITTLE_PROXIMAL = 0x42;
    public static final int RIGHT_HAND_LITTLE_INTERMEDIATE = 0x43;
    public static final int RIGHT_HAND_LITTLE_DISTAL = 0x44;
    public static final int RIGHT_HAND_LITTLE_TIP = 0x45;
    public static final int LEFT_UPPER_LEG = 0x46;
    public static final int LEFT_LOWER_LEG = 0x47;
    public static final int LEFT_FOOT_ANKLE_TWIST = 0x48;
    public static final int LEFT_FOOT_ANKLE = 0x49;
    public static final int LEFT_FOOT_SUBTALAR = 0x4a;
    public static final int LEFT_FOOT_TRANSVERSE = 0x4b;
    public static final int LEFT_FOOT_BALL = 0x4c;
    public static final int RIGHT_UPPER_LEG = 0x4d;
    public static final int RIGHT_LOWER_LEG = 0x4e;
    public static final int RIGHT_FOOT_ANKLE_TWIST = 0x4f;
    public static final int RIGHT_FOOT_ANKLE = 0x50;
    public static final int RIGHT_FOOT_SUBTALAR = 0x51;
    public static final int RIGHT_FOOT_TRANSVERSE = 0x52;
    public static final int RIGHT_FOOT_BALL = 0x53;
    public static final int COUNT = 0x54;
    public static final int NONE = 0x55;

    public static String explain(@EnumType(XrFullBodyJointMETA.class) int value) {
        return switch (value) {
            case XrFullBodyJointMETA.CHEST -> "XR_FULL_BODY_JOINT_CHEST_META";
            case XrFullBodyJointMETA.COUNT -> "XR_FULL_BODY_JOINT_COUNT_META";
            case XrFullBodyJointMETA.HEAD -> "XR_FULL_BODY_JOINT_HEAD_META";
            case XrFullBodyJointMETA.HIPS -> "XR_FULL_BODY_JOINT_HIPS_META";
            case XrFullBodyJointMETA.LEFT_ARM_LOWER -> "XR_FULL_BODY_JOINT_LEFT_ARM_LOWER_META";
            case XrFullBodyJointMETA.LEFT_ARM_UPPER -> "XR_FULL_BODY_JOINT_LEFT_ARM_UPPER_META";
            case XrFullBodyJointMETA.LEFT_FOOT_ANKLE -> "XR_FULL_BODY_JOINT_LEFT_FOOT_ANKLE_META";
            case XrFullBodyJointMETA.LEFT_FOOT_ANKLE_TWIST -> "XR_FULL_BODY_JOINT_LEFT_FOOT_ANKLE_TWIST_META";
            case XrFullBodyJointMETA.LEFT_FOOT_BALL -> "XR_FULL_BODY_JOINT_LEFT_FOOT_BALL_META";
            case XrFullBodyJointMETA.LEFT_FOOT_SUBTALAR -> "XR_FULL_BODY_JOINT_LEFT_FOOT_SUBTALAR_META";
            case XrFullBodyJointMETA.LEFT_FOOT_TRANSVERSE -> "XR_FULL_BODY_JOINT_LEFT_FOOT_TRANSVERSE_META";
            case XrFullBodyJointMETA.LEFT_HAND_INDEX_DISTAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_INDEX_DISTAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_INDEX_INTERMEDIATE -> "XR_FULL_BODY_JOINT_LEFT_HAND_INDEX_INTERMEDIATE_META";
            case XrFullBodyJointMETA.LEFT_HAND_INDEX_METACARPAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_INDEX_METACARPAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_INDEX_PROXIMAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_INDEX_PROXIMAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_INDEX_TIP -> "XR_FULL_BODY_JOINT_LEFT_HAND_INDEX_TIP_META";
            case XrFullBodyJointMETA.LEFT_HAND_LITTLE_DISTAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_LITTLE_DISTAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_LITTLE_INTERMEDIATE -> "XR_FULL_BODY_JOINT_LEFT_HAND_LITTLE_INTERMEDIATE_META";
            case XrFullBodyJointMETA.LEFT_HAND_LITTLE_METACARPAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_LITTLE_METACARPAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_LITTLE_PROXIMAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_LITTLE_PROXIMAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_LITTLE_TIP -> "XR_FULL_BODY_JOINT_LEFT_HAND_LITTLE_TIP_META";
            case XrFullBodyJointMETA.LEFT_HAND_MIDDLE_DISTAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_MIDDLE_DISTAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_MIDDLE_INTERMEDIATE -> "XR_FULL_BODY_JOINT_LEFT_HAND_MIDDLE_INTERMEDIATE_META";
            case XrFullBodyJointMETA.LEFT_HAND_MIDDLE_METACARPAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_MIDDLE_METACARPAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_MIDDLE_PROXIMAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_MIDDLE_PROXIMAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_MIDDLE_TIP -> "XR_FULL_BODY_JOINT_LEFT_HAND_MIDDLE_TIP_META";
            case XrFullBodyJointMETA.LEFT_HAND_PALM -> "XR_FULL_BODY_JOINT_LEFT_HAND_PALM_META";
            case XrFullBodyJointMETA.LEFT_HAND_RING_DISTAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_RING_DISTAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_RING_INTERMEDIATE -> "XR_FULL_BODY_JOINT_LEFT_HAND_RING_INTERMEDIATE_META";
            case XrFullBodyJointMETA.LEFT_HAND_RING_METACARPAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_RING_METACARPAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_RING_PROXIMAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_RING_PROXIMAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_RING_TIP -> "XR_FULL_BODY_JOINT_LEFT_HAND_RING_TIP_META";
            case XrFullBodyJointMETA.LEFT_HAND_THUMB_DISTAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_THUMB_DISTAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_THUMB_METACARPAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_THUMB_METACARPAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_THUMB_PROXIMAL -> "XR_FULL_BODY_JOINT_LEFT_HAND_THUMB_PROXIMAL_META";
            case XrFullBodyJointMETA.LEFT_HAND_THUMB_TIP -> "XR_FULL_BODY_JOINT_LEFT_HAND_THUMB_TIP_META";
            case XrFullBodyJointMETA.LEFT_HAND_WRIST -> "XR_FULL_BODY_JOINT_LEFT_HAND_WRIST_META";
            case XrFullBodyJointMETA.LEFT_HAND_WRIST_TWIST -> "XR_FULL_BODY_JOINT_LEFT_HAND_WRIST_TWIST_META";
            case XrFullBodyJointMETA.LEFT_LOWER_LEG -> "XR_FULL_BODY_JOINT_LEFT_LOWER_LEG_META";
            case XrFullBodyJointMETA.LEFT_SCAPULA -> "XR_FULL_BODY_JOINT_LEFT_SCAPULA_META";
            case XrFullBodyJointMETA.LEFT_SHOULDER -> "XR_FULL_BODY_JOINT_LEFT_SHOULDER_META";
            case XrFullBodyJointMETA.LEFT_UPPER_LEG -> "XR_FULL_BODY_JOINT_LEFT_UPPER_LEG_META";
            case XrFullBodyJointMETA.NECK -> "XR_FULL_BODY_JOINT_NECK_META";
            case XrFullBodyJointMETA.NONE -> "XR_FULL_BODY_JOINT_NONE_META";
            case XrFullBodyJointMETA.RIGHT_ARM_LOWER -> "XR_FULL_BODY_JOINT_RIGHT_ARM_LOWER_META";
            case XrFullBodyJointMETA.RIGHT_ARM_UPPER -> "XR_FULL_BODY_JOINT_RIGHT_ARM_UPPER_META";
            case XrFullBodyJointMETA.RIGHT_FOOT_ANKLE -> "XR_FULL_BODY_JOINT_RIGHT_FOOT_ANKLE_META";
            case XrFullBodyJointMETA.RIGHT_FOOT_ANKLE_TWIST -> "XR_FULL_BODY_JOINT_RIGHT_FOOT_ANKLE_TWIST_META";
            case XrFullBodyJointMETA.RIGHT_FOOT_BALL -> "XR_FULL_BODY_JOINT_RIGHT_FOOT_BALL_META";
            case XrFullBodyJointMETA.RIGHT_FOOT_SUBTALAR -> "XR_FULL_BODY_JOINT_RIGHT_FOOT_SUBTALAR_META";
            case XrFullBodyJointMETA.RIGHT_FOOT_TRANSVERSE -> "XR_FULL_BODY_JOINT_RIGHT_FOOT_TRANSVERSE_META";
            case XrFullBodyJointMETA.RIGHT_HAND_INDEX_DISTAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_INDEX_DISTAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_INDEX_INTERMEDIATE -> "XR_FULL_BODY_JOINT_RIGHT_HAND_INDEX_INTERMEDIATE_META";
            case XrFullBodyJointMETA.RIGHT_HAND_INDEX_METACARPAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_INDEX_METACARPAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_INDEX_PROXIMAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_INDEX_PROXIMAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_INDEX_TIP -> "XR_FULL_BODY_JOINT_RIGHT_HAND_INDEX_TIP_META";
            case XrFullBodyJointMETA.RIGHT_HAND_LITTLE_DISTAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_LITTLE_DISTAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_LITTLE_INTERMEDIATE -> "XR_FULL_BODY_JOINT_RIGHT_HAND_LITTLE_INTERMEDIATE_META";
            case XrFullBodyJointMETA.RIGHT_HAND_LITTLE_METACARPAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_LITTLE_METACARPAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_LITTLE_PROXIMAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_LITTLE_PROXIMAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_LITTLE_TIP -> "XR_FULL_BODY_JOINT_RIGHT_HAND_LITTLE_TIP_META";
            case XrFullBodyJointMETA.RIGHT_HAND_MIDDLE_DISTAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_DISTAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_MIDDLE_INTERMEDIATE -> "XR_FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_INTERMEDIATE_META";
            case XrFullBodyJointMETA.RIGHT_HAND_MIDDLE_METACARPAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_METACARPAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_MIDDLE_PROXIMAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_PROXIMAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_MIDDLE_TIP -> "XR_FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_TIP_META";
            case XrFullBodyJointMETA.RIGHT_HAND_PALM -> "XR_FULL_BODY_JOINT_RIGHT_HAND_PALM_META";
            case XrFullBodyJointMETA.RIGHT_HAND_RING_DISTAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_RING_DISTAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_RING_INTERMEDIATE -> "XR_FULL_BODY_JOINT_RIGHT_HAND_RING_INTERMEDIATE_META";
            case XrFullBodyJointMETA.RIGHT_HAND_RING_METACARPAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_RING_METACARPAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_RING_PROXIMAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_RING_PROXIMAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_RING_TIP -> "XR_FULL_BODY_JOINT_RIGHT_HAND_RING_TIP_META";
            case XrFullBodyJointMETA.RIGHT_HAND_THUMB_DISTAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_THUMB_DISTAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_THUMB_METACARPAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_THUMB_METACARPAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_THUMB_PROXIMAL -> "XR_FULL_BODY_JOINT_RIGHT_HAND_THUMB_PROXIMAL_META";
            case XrFullBodyJointMETA.RIGHT_HAND_THUMB_TIP -> "XR_FULL_BODY_JOINT_RIGHT_HAND_THUMB_TIP_META";
            case XrFullBodyJointMETA.RIGHT_HAND_WRIST -> "XR_FULL_BODY_JOINT_RIGHT_HAND_WRIST_META";
            case XrFullBodyJointMETA.RIGHT_HAND_WRIST_TWIST -> "XR_FULL_BODY_JOINT_RIGHT_HAND_WRIST_TWIST_META";
            case XrFullBodyJointMETA.RIGHT_LOWER_LEG -> "XR_FULL_BODY_JOINT_RIGHT_LOWER_LEG_META";
            case XrFullBodyJointMETA.RIGHT_SCAPULA -> "XR_FULL_BODY_JOINT_RIGHT_SCAPULA_META";
            case XrFullBodyJointMETA.RIGHT_SHOULDER -> "XR_FULL_BODY_JOINT_RIGHT_SHOULDER_META";
            case XrFullBodyJointMETA.RIGHT_UPPER_LEG -> "XR_FULL_BODY_JOINT_RIGHT_UPPER_LEG_META";
            case XrFullBodyJointMETA.ROOT -> "XR_FULL_BODY_JOINT_ROOT_META";
            case XrFullBodyJointMETA.SPINE_LOWER -> "XR_FULL_BODY_JOINT_SPINE_LOWER_META";
            case XrFullBodyJointMETA.SPINE_MIDDLE -> "XR_FULL_BODY_JOINT_SPINE_MIDDLE_META";
            case XrFullBodyJointMETA.SPINE_UPPER -> "XR_FULL_BODY_JOINT_SPINE_UPPER_META";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private XrFullBodyJointMETA() {}
}
