package club.doki7.openxr.enumtype;

import club.doki7.ffm.annotation.*;

/// @see <a href="https://registry.khronos.org/OpenXR/specs/1.1/man/html/XrStructureType.html"><code>XrStructureType</code></a>
public final class XrStructureType {
    public static final int UNKNOWN = 0x0;
    public static final int API_LAYER_PROPERTIES = 0x1;
    public static final int EXTENSION_PROPERTIES = 0x2;
    public static final int INSTANCE_CREATE_INFO = 0x3;
    public static final int SYSTEM_GET_INFO = 0x4;
    public static final int SYSTEM_PROPERTIES = 0x5;
    public static final int VIEW_LOCATE_INFO = 0x6;
    public static final int VIEW = 0x7;
    public static final int SESSION_CREATE_INFO = 0x8;
    public static final int SWAPCHAIN_CREATE_INFO = 0x9;
    public static final int SESSION_BEGIN_INFO = 0xa;
    public static final int VIEW_STATE = 0xb;
    public static final int FRAME_END_INFO = 0xc;
    public static final int HAPTIC_VIBRATION = 0xd;
    public static final int EVENT_DATA_BUFFER = 0x10;
    public static final int EVENT_DATA_INSTANCE_LOSS_PENDING = 0x11;
    public static final int EVENT_DATA_SESSION_STATE_CHANGED = 0x12;
    public static final int ACTION_STATE_BOOLEAN = 0x17;
    public static final int ACTION_STATE_FLOAT = 0x18;
    public static final int ACTION_STATE_VECTOR2F = 0x19;
    public static final int ACTION_STATE_POSE = 0x1b;
    public static final int ACTION_SET_CREATE_INFO = 0x1c;
    public static final int ACTION_CREATE_INFO = 0x1d;
    public static final int INSTANCE_PROPERTIES = 0x20;
    public static final int FRAME_WAIT_INFO = 0x21;
    public static final int COMPOSITION_LAYER_PROJECTION = 0x23;
    public static final int COMPOSITION_LAYER_QUAD = 0x24;
    public static final int REFERENCE_SPACE_CREATE_INFO = 0x25;
    public static final int ACTION_SPACE_CREATE_INFO = 0x26;
    public static final int EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING = 0x28;
    public static final int VIEW_CONFIGURATION_VIEW = 0x29;
    public static final int SPACE_LOCATION = 0x2a;
    public static final int SPACE_VELOCITY = 0x2b;
    public static final int FRAME_STATE = 0x2c;
    public static final int VIEW_CONFIGURATION_PROPERTIES = 0x2d;
    public static final int FRAME_BEGIN_INFO = 0x2e;
    public static final int COMPOSITION_LAYER_PROJECTION_VIEW = 0x30;
    public static final int EVENT_DATA_EVENTS_LOST = 0x31;
    public static final int INTERACTION_PROFILE_SUGGESTED_BINDING = 0x33;
    public static final int EVENT_DATA_INTERACTION_PROFILE_CHANGED = 0x34;
    public static final int INTERACTION_PROFILE_STATE = 0x35;
    public static final int SWAPCHAIN_IMAGE_ACQUIRE_INFO = 0x37;
    public static final int SWAPCHAIN_IMAGE_WAIT_INFO = 0x38;
    public static final int SWAPCHAIN_IMAGE_RELEASE_INFO = 0x39;
    public static final int ACTION_STATE_GET_INFO = 0x3a;
    public static final int HAPTIC_ACTION_INFO = 0x3b;
    public static final int SESSION_ACTION_SETS_ATTACH_INFO = 0x3c;
    public static final int ACTIONS_SYNC_INFO = 0x3d;
    public static final int BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO = 0x3e;
    public static final int INPUT_SOURCE_LOCALIZED_NAME_GET_INFO = 0x3f;
    public static final int SPACES_LOCATE_INFO = 0x3ba1f9d8;
    public static final int SPACE_LOCATIONS = 0x3ba1f9d9;
    public static final int SPACE_VELOCITIES = 0x3ba1f9da;
    public static final int COMPOSITION_LAYER_CUBE_KHR = 0x3b9ae170;
    public static final int INSTANCE_CREATE_INFO_ANDROID_KHR = 0x3b9ae940;
    public static final int COMPOSITION_LAYER_DEPTH_INFO_KHR = 0x3b9af110;
    public static final int VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR = 0x3b9b00b0;
    public static final int EVENT_DATA_PERF_SETTINGS_EXT = 0x3b9b0498;
    public static final int COMPOSITION_LAYER_CYLINDER_KHR = 0x3b9b0c68;
    public static final int COMPOSITION_LAYER_EQUIRECT_KHR = 0x3b9b1050;
    public static final int DEBUG_UTILS_OBJECT_NAME_INFO_EXT = 0x3b9b1438;
    public static final int DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT = 0x3b9b1439;
    public static final int DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT = 0x3b9b143a;
    public static final int DEBUG_UTILS_LABEL_EXT = 0x3b9b143b;
    public static final int GRAPHICS_BINDING_OPENGL_WIN32_KHR = 0x3b9b23d8;
    public static final int GRAPHICS_BINDING_OPENGL_XLIB_KHR = 0x3b9b23d9;
    public static final int GRAPHICS_BINDING_OPENGL_XCB_KHR = 0x3b9b23da;
    public static final int GRAPHICS_BINDING_OPENGL_WAYLAND_KHR = 0x3b9b23db;
    public static final int SWAPCHAIN_IMAGE_OPENGL_KHR = 0x3b9b23dc;
    public static final int GRAPHICS_REQUIREMENTS_OPENGL_KHR = 0x3b9b23dd;
    public static final int GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR = 0x3b9b27c1;
    public static final int SWAPCHAIN_IMAGE_OPENGL_ES_KHR = 0x3b9b27c2;
    public static final int GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR = 0x3b9b27c3;
    public static final int GRAPHICS_BINDING_VULKAN_KHR = 0x3b9b2ba8;
    public static final int SWAPCHAIN_IMAGE_VULKAN_KHR = 0x3b9b2ba9;
    public static final int GRAPHICS_REQUIREMENTS_VULKAN_KHR = 0x3b9b2baa;
    public static final int GRAPHICS_BINDING_D3D11_KHR = 0x3b9b3378;
    public static final int SWAPCHAIN_IMAGE_D3D11_KHR = 0x3b9b3379;
    public static final int GRAPHICS_REQUIREMENTS_D3D11_KHR = 0x3b9b337a;
    public static final int GRAPHICS_BINDING_D3D12_KHR = 0x3b9b3760;
    public static final int SWAPCHAIN_IMAGE_D3D12_KHR = 0x3b9b3761;
    public static final int GRAPHICS_REQUIREMENTS_D3D12_KHR = 0x3b9b3762;
    public static final int GRAPHICS_BINDING_METAL_KHR = 0x3b9b3b48;
    public static final int SWAPCHAIN_IMAGE_METAL_KHR = 0x3b9b3b49;
    public static final int GRAPHICS_REQUIREMENTS_METAL_KHR = 0x3b9b3b4a;
    public static final int SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT = 0x3b9b3f30;
    public static final int EYE_GAZE_SAMPLE_TIME_EXT = 0x3b9b3f31;
    public static final int VISIBILITY_MASK_KHR = 0x3b9b4318;
    public static final int EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR = 0x3b9b4319;
    public static final int SESSION_CREATE_INFO_OVERLAY_EXTX = 0x3b9b4ae8;
    public static final int EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX = 0x3b9b4aeb;
    public static final int COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR = 0x3b9b4ed0;
    public static final int SPATIAL_ANCHOR_CREATE_INFO_MSFT = 0x3b9b6258;
    public static final int SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT = 0x3b9b6259;
    public static final int COMPOSITION_LAYER_IMAGE_LAYOUT_FB = 0x3b9b6640;
    public static final int COMPOSITION_LAYER_ALPHA_BLEND_FB = 0x3b9b6a29;
    public static final int VIEW_CONFIGURATION_DEPTH_RANGE_EXT = 0x3b9b7db0;
    public static final int GRAPHICS_BINDING_EGL_MNDX = 0x3b9b8584;
    public static final int SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT = 0x3b9b8968;
    public static final int SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT = 0x3b9b8969;
    public static final int SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT = 0x3b9b896a;
    public static final int SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT = 0x3b9b896b;
    public static final int SYSTEM_HAND_TRACKING_PROPERTIES_EXT = 0x3b9b9138;
    public static final int HAND_TRACKER_CREATE_INFO_EXT = 0x3b9b9139;
    public static final int HAND_JOINTS_LOCATE_INFO_EXT = 0x3b9b913a;
    public static final int HAND_JOINT_LOCATIONS_EXT = 0x3b9b913b;
    public static final int HAND_JOINT_VELOCITIES_EXT = 0x3b9b913c;
    public static final int SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT = 0x3b9b9520;
    public static final int HAND_MESH_SPACE_CREATE_INFO_MSFT = 0x3b9b9521;
    public static final int HAND_MESH_UPDATE_INFO_MSFT = 0x3b9b9522;
    public static final int HAND_MESH_MSFT = 0x3b9b9523;
    public static final int HAND_POSE_TYPE_INFO_MSFT = 0x3b9b9524;
    public static final int SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT = 0x3b9b9908;
    public static final int SECONDARY_VIEW_CONFIGURATION_STATE_MSFT = 0x3b9b9909;
    public static final int SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT = 0x3b9b990a;
    public static final int SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT = 0x3b9b990b;
    public static final int SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT = 0x3b9b990c;
    public static final int SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT = 0x3b9b990d;
    public static final int CONTROLLER_MODEL_KEY_STATE_MSFT = 0x3b9ba0d8;
    public static final int CONTROLLER_MODEL_NODE_PROPERTIES_MSFT = 0x3b9ba0d9;
    public static final int CONTROLLER_MODEL_PROPERTIES_MSFT = 0x3b9ba0da;
    public static final int CONTROLLER_MODEL_NODE_STATE_MSFT = 0x3b9ba0db;
    public static final int CONTROLLER_MODEL_STATE_MSFT = 0x3b9ba0dc;
    public static final int VIEW_CONFIGURATION_VIEW_FOV_EPIC = 0x3b9bb078;
    public static final int HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT = 0x3b9bc018;
    public static final int COMPOSITION_LAYER_REPROJECTION_INFO_MSFT = 0x3b9bcbd0;
    public static final int COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT = 0x3b9bcbd1;
    public static final int ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB = 0x3b9bdb70;
    public static final int COMPOSITION_LAYER_SECURE_CONTENT_FB = 0x3b9be340;
    public static final int BODY_TRACKER_CREATE_INFO_FB = 0x3b9bf2e1;
    public static final int BODY_JOINTS_LOCATE_INFO_FB = 0x3b9bf2e2;
    public static final int SYSTEM_BODY_TRACKING_PROPERTIES_FB = 0x3b9bf2e4;
    public static final int BODY_JOINT_LOCATIONS_FB = 0x3b9bf2e5;
    public static final int BODY_SKELETON_FB = 0x3b9bf2e6;
    public static final int INTERACTION_PROFILE_DPAD_BINDING_EXT = 0x3b9bfab0;
    public static final int INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE = 0x3b9bfe98;
    public static final int HAND_JOINTS_MOTION_RANGE_INFO_EXT = 0x3b9c0280;
    public static final int LOADER_INIT_INFO_ANDROID_KHR = 0x3b9c25a8;
    public static final int VULKAN_INSTANCE_CREATE_INFO_KHR = 0x3b9c2990;
    public static final int VULKAN_DEVICE_CREATE_INFO_KHR = 0x3b9c2991;
    public static final int VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR = 0x3b9c2993;
    public static final int GRAPHICS_BINDING_VULKAN2_KHR = GRAPHICS_BINDING_VULKAN_KHR;
    public static final int SWAPCHAIN_IMAGE_VULKAN2_KHR = SWAPCHAIN_IMAGE_VULKAN_KHR;
    public static final int GRAPHICS_REQUIREMENTS_VULKAN2_KHR = GRAPHICS_REQUIREMENTS_VULKAN_KHR;
    public static final int COMPOSITION_LAYER_EQUIRECT2_KHR = 0x3b9c2d78;
    public static final int SCENE_OBSERVER_CREATE_INFO_MSFT = 0x3b9c44e8;
    public static final int SCENE_CREATE_INFO_MSFT = 0x3b9c44e9;
    public static final int NEW_SCENE_COMPUTE_INFO_MSFT = 0x3b9c44ea;
    public static final int VISUAL_MESH_COMPUTE_LOD_INFO_MSFT = 0x3b9c44eb;
    public static final int SCENE_COMPONENTS_MSFT = 0x3b9c44ec;
    public static final int SCENE_COMPONENTS_GET_INFO_MSFT = 0x3b9c44ed;
    public static final int SCENE_COMPONENT_LOCATIONS_MSFT = 0x3b9c44ee;
    public static final int SCENE_COMPONENTS_LOCATE_INFO_MSFT = 0x3b9c44ef;
    public static final int SCENE_OBJECTS_MSFT = 0x3b9c44f0;
    public static final int SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT = 0x3b9c44f1;
    public static final int SCENE_OBJECT_TYPES_FILTER_INFO_MSFT = 0x3b9c44f2;
    public static final int SCENE_PLANES_MSFT = 0x3b9c44f3;
    public static final int SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT = 0x3b9c44f4;
    public static final int SCENE_MESHES_MSFT = 0x3b9c44f5;
    public static final int SCENE_MESH_BUFFERS_GET_INFO_MSFT = 0x3b9c44f6;
    public static final int SCENE_MESH_BUFFERS_MSFT = 0x3b9c44f7;
    public static final int SCENE_MESH_VERTEX_BUFFER_MSFT = 0x3b9c44f8;
    public static final int SCENE_MESH_INDICES_UINT32_MSFT = 0x3b9c44f9;
    public static final int SCENE_MESH_INDICES_UINT16_MSFT = 0x3b9c44fa;
    public static final int SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT = 0x3b9c48d0;
    public static final int SCENE_DESERIALIZE_INFO_MSFT = 0x3b9c48d1;
    public static final int EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB = 0x3b9c5488;
    public static final int VIVE_TRACKER_PATHS_HTCX = 0x3b9c5c58;
    public static final int EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX = 0x3b9c5c59;
    public static final int SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC = 0x3b9c6040;
    public static final int FACIAL_TRACKER_CREATE_INFO_HTC = 0x3b9c6041;
    public static final int FACIAL_EXPRESSIONS_HTC = 0x3b9c6042;
    public static final int SYSTEM_COLOR_SPACE_PROPERTIES_FB = 0x3b9c6fe0;
    public static final int HAND_TRACKING_MESH_FB = 0x3b9c77b1;
    public static final int HAND_TRACKING_SCALE_FB = 0x3b9c77b3;
    public static final int HAND_TRACKING_AIM_STATE_FB = 0x3b9c7b99;
    public static final int HAND_TRACKING_CAPSULES_STATE_FB = 0x3b9c7f80;
    public static final int SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB = 0x3b9c836c;
    public static final int SPATIAL_ANCHOR_CREATE_INFO_FB = 0x3b9c836b;
    public static final int SPACE_COMPONENT_STATUS_SET_INFO_FB = 0x3b9c836f;
    public static final int SPACE_COMPONENT_STATUS_FB = 0x3b9c8369;
    public static final int EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB = 0x3b9c836d;
    public static final int EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB = 0x3b9c836e;
    public static final int FOVEATION_PROFILE_CREATE_INFO_FB = 0x3b9c8750;
    public static final int SWAPCHAIN_CREATE_INFO_FOVEATION_FB = 0x3b9c8751;
    public static final int SWAPCHAIN_STATE_FOVEATION_FB = 0x3b9c8752;
    public static final int FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB = 0x3b9c8b38;
    public static final int KEYBOARD_SPACE_CREATE_INFO_FB = 0x3b9c8f29;
    public static final int KEYBOARD_TRACKING_QUERY_FB = 0x3b9c8f24;
    public static final int SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB = 0x3b9c8f22;
    public static final int TRIANGLE_MESH_CREATE_INFO_FB = 0x3b9c9309;
    public static final int SYSTEM_PASSTHROUGH_PROPERTIES_FB = 0x3b9c96f0;
    public static final int PASSTHROUGH_CREATE_INFO_FB = 0x3b9c96f1;
    public static final int PASSTHROUGH_LAYER_CREATE_INFO_FB = 0x3b9c96f2;
    public static final int COMPOSITION_LAYER_PASSTHROUGH_FB = 0x3b9c96f3;
    public static final int GEOMETRY_INSTANCE_CREATE_INFO_FB = 0x3b9c96f4;
    public static final int GEOMETRY_INSTANCE_TRANSFORM_FB = 0x3b9c96f5;
    public static final int SYSTEM_PASSTHROUGH_PROPERTIES2_FB = 0x3b9c96f6;
    public static final int PASSTHROUGH_STYLE_FB = 0x3b9c9704;
    public static final int PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB = 0x3b9c9705;
    public static final int PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB = 0x3b9c9706;
    public static final int PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB = 0x3b9c9707;
    public static final int EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB = 0x3b9c970e;
    public static final int RENDER_MODEL_PATH_INFO_FB = 0x3b9c9ad8;
    public static final int RENDER_MODEL_PROPERTIES_FB = 0x3b9c9ad9;
    public static final int RENDER_MODEL_BUFFER_FB = 0x3b9c9ada;
    public static final int RENDER_MODEL_LOAD_INFO_FB = 0x3b9c9adb;
    public static final int SYSTEM_RENDER_MODEL_PROPERTIES_FB = 0x3b9c9adc;
    public static final int RENDER_MODEL_CAPABILITIES_REQUEST_FB = 0x3b9c9add;
    public static final int BINDING_MODIFICATIONS_KHR = 0x3b9c9ec0;
    public static final int VIEW_LOCATE_FOVEATED_RENDERING_VARJO = 0x3b9ca2a8;
    public static final int FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO = 0x3b9ca2a9;
    public static final int SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO = 0x3b9ca2aa;
    public static final int COMPOSITION_LAYER_DEPTH_TEST_VARJO = 0x3b9ca690;
    public static final int SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO = 0x3b9cae60;
    public static final int EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO = 0x3b9cae61;
    public static final int MARKER_SPACE_CREATE_INFO_VARJO = 0x3b9cae62;
    public static final int FRAME_END_INFO_ML = 0x3b9cd958;
    public static final int GLOBAL_DIMMER_FRAME_END_INFO_ML = 0x3b9cdd40;
    public static final int COORDINATE_SPACE_CREATE_INFO_ML = 0x3b9ce128;
    public static final int SYSTEM_MARKER_UNDERSTANDING_PROPERTIES_ML = 0x3b9ce510;
    public static final int MARKER_DETECTOR_CREATE_INFO_ML = 0x3b9ce511;
    public static final int MARKER_DETECTOR_ARUCO_INFO_ML = 0x3b9ce512;
    public static final int MARKER_DETECTOR_SIZE_INFO_ML = 0x3b9ce513;
    public static final int MARKER_DETECTOR_APRIL_TAG_INFO_ML = 0x3b9ce514;
    public static final int MARKER_DETECTOR_CUSTOM_PROFILE_INFO_ML = 0x3b9ce515;
    public static final int MARKER_DETECTOR_SNAPSHOT_INFO_ML = 0x3b9ce516;
    public static final int MARKER_DETECTOR_STATE_ML = 0x3b9ce517;
    public static final int MARKER_SPACE_CREATE_INFO_ML = 0x3b9ce518;
    public static final int LOCALIZATION_MAP_ML = 0x3b9ce8f8;
    public static final int EVENT_DATA_LOCALIZATION_CHANGED_ML = 0x3b9ce8f9;
    public static final int MAP_LOCALIZATION_REQUEST_INFO_ML = 0x3b9ce8fa;
    public static final int LOCALIZATION_MAP_IMPORT_INFO_ML = 0x3b9ce8fb;
    public static final int LOCALIZATION_ENABLE_EVENTS_INFO_ML = 0x3b9ce8fc;
    public static final int SPATIAL_ANCHORS_CREATE_INFO_FROM_POSE_ML = 0x3b9cece0;
    public static final int CREATE_SPATIAL_ANCHORS_COMPLETION_ML = 0x3b9cece1;
    public static final int SPATIAL_ANCHOR_STATE_ML = 0x3b9cece2;
    public static final int SPATIAL_ANCHORS_CREATE_STORAGE_INFO_ML = 0x3b9cf0c8;
    public static final int SPATIAL_ANCHORS_QUERY_INFO_RADIUS_ML = 0x3b9cf0c9;
    public static final int SPATIAL_ANCHORS_QUERY_COMPLETION_ML = 0x3b9cf0ca;
    public static final int SPATIAL_ANCHORS_CREATE_INFO_FROM_UUIDS_ML = 0x3b9cf0cb;
    public static final int SPATIAL_ANCHORS_PUBLISH_INFO_ML = 0x3b9cf0cc;
    public static final int SPATIAL_ANCHORS_PUBLISH_COMPLETION_ML = 0x3b9cf0cd;
    public static final int SPATIAL_ANCHORS_DELETE_INFO_ML = 0x3b9cf0ce;
    public static final int SPATIAL_ANCHORS_DELETE_COMPLETION_ML = 0x3b9cf0cf;
    public static final int SPATIAL_ANCHORS_UPDATE_EXPIRATION_INFO_ML = 0x3b9cf0d0;
    public static final int SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_ML = 0x3b9cf0d1;
    public static final int SPATIAL_ANCHORS_PUBLISH_COMPLETION_DETAILS_ML = 0x3b9cf0d2;
    public static final int SPATIAL_ANCHORS_DELETE_COMPLETION_DETAILS_ML = 0x3b9cf0d3;
    public static final int SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_DETAILS_ML = 0x3b9cf0d4;
    public static final int EVENT_DATA_HEADSET_FIT_CHANGED_ML = 0x3ba1fdc0;
    public static final int EVENT_DATA_EYE_CALIBRATION_CHANGED_ML = 0x3ba1fdc1;
    public static final int USER_CALIBRATION_ENABLE_EVENTS_INFO_ML = 0x3ba1fdc2;
    public static final int SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT = 0x3b9cf4b0;
    public static final int SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT = 0x3b9cf4b1;
    public static final int SCENE_MARKERS_MSFT = 0x3b9d0838;
    public static final int SCENE_MARKER_TYPE_FILTER_MSFT = 0x3b9d0839;
    public static final int SCENE_MARKER_QR_CODES_MSFT = 0x3b9d083a;
    public static final int SPACE_QUERY_INFO_FB = 0x3b9d2b61;
    public static final int SPACE_QUERY_RESULTS_FB = 0x3b9d2b62;
    public static final int SPACE_STORAGE_LOCATION_FILTER_INFO_FB = 0x3b9d2b63;
    public static final int SPACE_UUID_FILTER_INFO_FB = 0x3b9d2b96;
    public static final int SPACE_COMPONENT_FILTER_INFO_FB = 0x3b9d2b94;
    public static final int EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB = 0x3b9d2bc7;
    public static final int EVENT_DATA_SPACE_QUERY_COMPLETE_FB = 0x3b9d2bc8;
    public static final int SPACE_SAVE_INFO_FB = 0x3b9d3330;
    public static final int SPACE_ERASE_INFO_FB = 0x3b9d3331;
    public static final int EVENT_DATA_SPACE_SAVE_COMPLETE_FB = 0x3b9d339a;
    public static final int EVENT_DATA_SPACE_ERASE_COMPLETE_FB = 0x3b9d339b;
    public static final int SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB = 0x3b9d3b00;
    public static final int SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB = 0x3b9d3ee8;
    public static final int SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB = 0x3b9d42d0;
    public static final int SWAPCHAIN_STATE_SAMPLER_VULKAN_FB = 0x3b9d46b8;
    public static final int SPACE_SHARE_INFO_FB = 0x3b9d5e29;
    public static final int EVENT_DATA_SPACE_SHARE_COMPLETE_FB = 0x3b9d5e2a;
    public static final int COMPOSITION_LAYER_SPACE_WARP_INFO_FB = 0x3b9d65f8;
    public static final int SYSTEM_SPACE_WARP_PROPERTIES_FB = 0x3b9d65f9;
    public static final int HAPTIC_AMPLITUDE_ENVELOPE_VIBRATION_FB = 0x3b9d6dc9;
    public static final int SEMANTIC_LABELS_FB = 0x3b9d7598;
    public static final int ROOM_LAYOUT_FB = 0x3b9d7599;
    public static final int BOUNDARY_2D_FB = 0x3b9d759a;
    public static final int SEMANTIC_LABELS_SUPPORT_INFO_FB = 0x3b9d75a2;
    public static final int DIGITAL_LENS_CONTROL_ALMALENCE = 0x3b9dc7a0;
    public static final int EVENT_DATA_SCENE_CAPTURE_COMPLETE_FB = 0x3b9dcf71;
    public static final int SCENE_CAPTURE_REQUEST_INFO_FB = 0x3b9dcfa2;
    public static final int SPACE_CONTAINER_FB = 0x3b9dd358;
    public static final int FOVEATION_EYE_TRACKED_PROFILE_CREATE_INFO_META = 0x3b9dd740;
    public static final int FOVEATION_EYE_TRACKED_STATE_META = 0x3b9dd741;
    public static final int SYSTEM_FOVEATION_EYE_TRACKED_PROPERTIES_META = 0x3b9dd742;
    public static final int SYSTEM_FACE_TRACKING_PROPERTIES_FB = 0x3b9ddb2c;
    public static final int FACE_TRACKER_CREATE_INFO_FB = 0x3b9ddb2d;
    public static final int FACE_EXPRESSION_INFO_FB = 0x3b9ddb2a;
    public static final int FACE_EXPRESSION_WEIGHTS_FB = 0x3b9ddb2e;
    public static final int EYE_TRACKER_CREATE_INFO_FB = 0x3b9ddf11;
    public static final int EYE_GAZES_INFO_FB = 0x3b9ddf12;
    public static final int EYE_GAZES_FB = 0x3b9ddf13;
    public static final int SYSTEM_EYE_TRACKING_PROPERTIES_FB = 0x3b9ddf14;
    public static final int PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB = 0x3b9de2fa;
    public static final int COMPOSITION_LAYER_SETTINGS_FB = 0x3b9de6e0;
    public static final int HAPTIC_PCM_VIBRATION_FB = 0x3b9dfa69;
    public static final int DEVICE_PCM_SAMPLE_RATE_STATE_FB = 0x3b9dfa6a;
    public static final int DEVICE_PCM_SAMPLE_RATE_GET_INFO_FB = DEVICE_PCM_SAMPLE_RATE_STATE_FB;
    public static final int FRAME_SYNTHESIS_INFO_EXT = 0x3b9e0238;
    public static final int FRAME_SYNTHESIS_CONFIG_VIEW_EXT = 0x3b9e0239;
    public static final int COMPOSITION_LAYER_DEPTH_TEST_FB = 0x3b9e0620;
    public static final int LOCAL_DIMMING_FRAME_END_INFO_META = 0x3b9e15c0;
    public static final int PASSTHROUGH_PREFERENCES_META = 0x3b9e19a8;
    public static final int SYSTEM_VIRTUAL_KEYBOARD_PROPERTIES_META = 0x3b9e2179;
    public static final int VIRTUAL_KEYBOARD_CREATE_INFO_META = 0x3b9e217a;
    public static final int VIRTUAL_KEYBOARD_SPACE_CREATE_INFO_META = 0x3b9e217b;
    public static final int VIRTUAL_KEYBOARD_LOCATION_INFO_META = 0x3b9e217c;
    public static final int VIRTUAL_KEYBOARD_MODEL_VISIBILITY_SET_INFO_META = 0x3b9e217d;
    public static final int VIRTUAL_KEYBOARD_ANIMATION_STATE_META = 0x3b9e217e;
    public static final int VIRTUAL_KEYBOARD_MODEL_ANIMATION_STATES_META = 0x3b9e217f;
    public static final int VIRTUAL_KEYBOARD_TEXTURE_DATA_META = 0x3b9e2181;
    public static final int VIRTUAL_KEYBOARD_INPUT_INFO_META = 0x3b9e2182;
    public static final int VIRTUAL_KEYBOARD_TEXT_CONTEXT_CHANGE_INFO_META = 0x3b9e2183;
    public static final int EVENT_DATA_VIRTUAL_KEYBOARD_COMMIT_TEXT_META = 0x3b9e2186;
    public static final int EVENT_DATA_VIRTUAL_KEYBOARD_BACKSPACE_META = 0x3b9e2187;
    public static final int EVENT_DATA_VIRTUAL_KEYBOARD_ENTER_META = 0x3b9e2188;
    public static final int EVENT_DATA_VIRTUAL_KEYBOARD_SHOWN_META = 0x3b9e2189;
    public static final int EVENT_DATA_VIRTUAL_KEYBOARD_HIDDEN_META = 0x3b9e218a;
    public static final int EXTERNAL_CAMERA_OCULUS = 0x3b9e3cd0;
    public static final int VULKAN_SWAPCHAIN_CREATE_INFO_META = 0x3b9e40b8;
    public static final int PERFORMANCE_METRICS_STATE_META = 0x3b9e5441;
    public static final int PERFORMANCE_METRICS_COUNTER_META = 0x3b9e5442;
    public static final int SPACE_LIST_SAVE_INFO_FB = 0x3b9e6bb0;
    public static final int EVENT_DATA_SPACE_LIST_SAVE_COMPLETE_FB = 0x3b9e6bb1;
    public static final int SPACE_USER_CREATE_INFO_FB = 0x3b9e7769;
    public static final int SYSTEM_HEADSET_ID_PROPERTIES_META = 0x3b9e8708;
    public static final int RECOMMENDED_LAYER_RESOLUTION_META = 0x3b9eaa30;
    public static final int RECOMMENDED_LAYER_RESOLUTION_GET_INFO_META = 0x3b9eaa31;
    public static final int SYSTEM_PASSTHROUGH_COLOR_LUT_PROPERTIES_META = 0x3b9ed910;
    public static final int PASSTHROUGH_COLOR_LUT_CREATE_INFO_META = 0x3b9ed911;
    public static final int PASSTHROUGH_COLOR_LUT_UPDATE_INFO_META = 0x3b9ed912;
    public static final int PASSTHROUGH_COLOR_MAP_LUT_META = 0x3b9ed974;
    public static final int PASSTHROUGH_COLOR_MAP_INTERPOLATED_LUT_META = 0x3b9ed975;
    public static final int SPACE_TRIANGLE_MESH_GET_INFO_META = 0x3b9ee4c9;
    public static final int SPACE_TRIANGLE_MESH_META = 0x3b9ee4ca;
    public static final int SYSTEM_PROPERTIES_BODY_TRACKING_FULL_BODY_META = 0x3b9ef850;
    public static final int EVENT_DATA_PASSTHROUGH_LAYER_RESUMED_META = 0x3b9f1790;
    public static final int SYSTEM_FACE_TRACKING_PROPERTIES2_FB = 0x3b9f2b25;
    public static final int FACE_TRACKER_CREATE_INFO2_FB = 0x3b9f2b26;
    public static final int FACE_EXPRESSION_INFO2_FB = 0x3b9f2b27;
    public static final int FACE_EXPRESSION_WEIGHTS2_FB = 0x3b9f2b28;
    public static final int SYSTEM_SPATIAL_ENTITY_SHARING_PROPERTIES_META = 0x3b9f36d0;
    public static final int SHARE_SPACES_INFO_META = 0x3b9f36d1;
    public static final int EVENT_DATA_SHARE_SPACES_COMPLETE_META = 0x3b9f36d2;
    public static final int ENVIRONMENT_DEPTH_PROVIDER_CREATE_INFO_META = 0x3b9f3ab8;
    public static final int ENVIRONMENT_DEPTH_SWAPCHAIN_CREATE_INFO_META = 0x3b9f3ab9;
    public static final int ENVIRONMENT_DEPTH_SWAPCHAIN_STATE_META = 0x3b9f3aba;
    public static final int ENVIRONMENT_DEPTH_IMAGE_ACQUIRE_INFO_META = 0x3b9f3abb;
    public static final int ENVIRONMENT_DEPTH_IMAGE_VIEW_META = 0x3b9f3abc;
    public static final int ENVIRONMENT_DEPTH_IMAGE_META = 0x3b9f3abd;
    public static final int ENVIRONMENT_DEPTH_HAND_REMOVAL_SET_INFO_META = 0x3b9f3abe;
    public static final int SYSTEM_ENVIRONMENT_DEPTH_PROPERTIES_META = 0x3b9f3abf;
    public static final int RENDER_MODEL_CREATE_INFO_EXT = 0x3b9f5de0;
    public static final int RENDER_MODEL_PROPERTIES_GET_INFO_EXT = 0x3b9f5de1;
    public static final int RENDER_MODEL_PROPERTIES_EXT = 0x3b9f5de2;
    public static final int RENDER_MODEL_SPACE_CREATE_INFO_EXT = 0x3b9f5de3;
    public static final int RENDER_MODEL_STATE_GET_INFO_EXT = 0x3b9f5de4;
    public static final int RENDER_MODEL_STATE_EXT = 0x3b9f5de5;
    public static final int RENDER_MODEL_ASSET_CREATE_INFO_EXT = 0x3b9f5de6;
    public static final int RENDER_MODEL_ASSET_DATA_GET_INFO_EXT = 0x3b9f5de7;
    public static final int RENDER_MODEL_ASSET_DATA_EXT = 0x3b9f5de8;
    public static final int RENDER_MODEL_ASSET_PROPERTIES_GET_INFO_EXT = 0x3b9f5de9;
    public static final int RENDER_MODEL_ASSET_PROPERTIES_EXT = 0x3b9f5dea;
    public static final int INTERACTION_RENDER_MODEL_IDS_ENUMERATE_INFO_EXT = 0x3b9f61c8;
    public static final int INTERACTION_RENDER_MODEL_SUBACTION_PATH_INFO_EXT = 0x3b9f61c9;
    public static final int EVENT_DATA_INTERACTION_RENDER_MODELS_CHANGED_EXT = 0x3b9f61ca;
    public static final int INTERACTION_RENDER_MODEL_TOP_LEVEL_USER_PATH_GET_INFO_EXT = 0x3b9f61cb;
    public static final int PASSTHROUGH_CREATE_INFO_HTC = 0x3b9fa049;
    public static final int PASSTHROUGH_COLOR_HTC = 0x3b9fa04a;
    public static final int PASSTHROUGH_MESH_TRANSFORM_INFO_HTC = 0x3b9fa04b;
    public static final int COMPOSITION_LAYER_PASSTHROUGH_HTC = 0x3b9fa04c;
    public static final int FOVEATION_APPLY_INFO_HTC = 0x3b9fa430;
    public static final int FOVEATION_DYNAMIC_MODE_INFO_HTC = 0x3b9fa431;
    public static final int FOVEATION_CUSTOM_MODE_INFO_HTC = 0x3b9fa432;
    public static final int SYSTEM_ANCHOR_PROPERTIES_HTC = 0x3b9fa818;
    public static final int SPATIAL_ANCHOR_CREATE_INFO_HTC = 0x3b9fa819;
    public static final int SYSTEM_BODY_TRACKING_PROPERTIES_HTC = 0x3b9fac00;
    public static final int BODY_TRACKER_CREATE_INFO_HTC = 0x3b9fac01;
    public static final int BODY_JOINTS_LOCATE_INFO_HTC = 0x3b9fac02;
    public static final int BODY_JOINT_LOCATIONS_HTC = 0x3b9fac03;
    public static final int BODY_SKELETON_HTC = 0x3b9fac04;
    public static final int ACTIVE_ACTION_SET_PRIORITIES_EXT = 0x3ba07b08;
    public static final int SYSTEM_FORCE_FEEDBACK_CURL_PROPERTIES_MNDX = 0x3ba082d8;
    public static final int FORCE_FEEDBACK_CURL_APPLY_LOCATIONS_MNDX = 0x3ba082d9;
    public static final int BODY_TRACKER_CREATE_INFO_BD = 0x3ba0a9e9;
    public static final int BODY_JOINTS_LOCATE_INFO_BD = 0x3ba0a9ea;
    public static final int BODY_JOINT_LOCATIONS_BD = 0x3ba0a9eb;
    public static final int SYSTEM_BODY_TRACKING_PROPERTIES_BD = 0x3ba0a9ec;
    public static final int SYSTEM_SPATIAL_SENSING_PROPERTIES_BD = 0x3ba0b988;
    public static final int SPATIAL_ENTITY_COMPONENT_GET_INFO_BD = 0x3ba0b989;
    public static final int SPATIAL_ENTITY_LOCATION_GET_INFO_BD = 0x3ba0b98a;
    public static final int SPATIAL_ENTITY_COMPONENT_DATA_LOCATION_BD = 0x3ba0b98b;
    public static final int SPATIAL_ENTITY_COMPONENT_DATA_SEMANTIC_BD = 0x3ba0b98c;
    public static final int SPATIAL_ENTITY_COMPONENT_DATA_BOUNDING_BOX_2D_BD = 0x3ba0b98d;
    public static final int SPATIAL_ENTITY_COMPONENT_DATA_POLYGON_BD = 0x3ba0b98e;
    public static final int SPATIAL_ENTITY_COMPONENT_DATA_BOUNDING_BOX_3D_BD = 0x3ba0b98f;
    public static final int SPATIAL_ENTITY_COMPONENT_DATA_TRIANGLE_MESH_BD = 0x3ba0b990;
    public static final int SENSE_DATA_PROVIDER_CREATE_INFO_BD = 0x3ba0b991;
    public static final int SENSE_DATA_PROVIDER_START_INFO_BD = 0x3ba0b992;
    public static final int EVENT_DATA_SENSE_DATA_PROVIDER_STATE_CHANGED_BD = 0x3ba0b993;
    public static final int EVENT_DATA_SENSE_DATA_UPDATED_BD = 0x3ba0b994;
    public static final int SENSE_DATA_QUERY_INFO_BD = 0x3ba0b995;
    public static final int SENSE_DATA_QUERY_COMPLETION_BD = 0x3ba0b996;
    public static final int SENSE_DATA_FILTER_UUID_BD = 0x3ba0b997;
    public static final int SENSE_DATA_FILTER_SEMANTIC_BD = 0x3ba0b998;
    public static final int QUERIED_SENSE_DATA_GET_INFO_BD = 0x3ba0b999;
    public static final int QUERIED_SENSE_DATA_BD = 0x3ba0b99a;
    public static final int SPATIAL_ENTITY_STATE_BD = 0x3ba0b99b;
    public static final int SPATIAL_ENTITY_ANCHOR_CREATE_INFO_BD = 0x3ba0b99c;
    public static final int ANCHOR_SPACE_CREATE_INFO_BD = 0x3ba0b99d;
    public static final int SYSTEM_SPATIAL_ANCHOR_PROPERTIES_BD = 0x3ba0bd70;
    public static final int SPATIAL_ANCHOR_CREATE_INFO_BD = 0x3ba0bd71;
    public static final int SPATIAL_ANCHOR_CREATE_COMPLETION_BD = 0x3ba0bd72;
    public static final int SPATIAL_ANCHOR_PERSIST_INFO_BD = 0x3ba0bd73;
    public static final int SPATIAL_ANCHOR_UNPERSIST_INFO_BD = 0x3ba0bd74;
    public static final int SYSTEM_SPATIAL_ANCHOR_SHARING_PROPERTIES_BD = 0x3ba0c158;
    public static final int SPATIAL_ANCHOR_SHARE_INFO_BD = 0x3ba0c159;
    public static final int SHARED_SPATIAL_ANCHOR_DOWNLOAD_INFO_BD = 0x3ba0c15a;
    public static final int SYSTEM_SPATIAL_SCENE_PROPERTIES_BD = 0x3ba0c540;
    public static final int SCENE_CAPTURE_INFO_BD = 0x3ba0c541;
    public static final int SYSTEM_SPATIAL_MESH_PROPERTIES_BD = 0x3ba0c928;
    public static final int SENSE_DATA_PROVIDER_CREATE_INFO_SPATIAL_MESH_BD = 0x3ba0c929;
    public static final int FUTURE_POLL_RESULT_PROGRESS_BD = 0x3ba0cd11;
    public static final int SYSTEM_SPATIAL_PLANE_PROPERTIES_BD = 0x3ba0d4e0;
    public static final int SPATIAL_ENTITY_COMPONENT_DATA_PLANE_ORIENTATION_BD = 0x3ba0d4e1;
    public static final int SENSE_DATA_FILTER_PLANE_ORIENTATION_BD = 0x3ba0d4e2;
    public static final int HAND_TRACKING_DATA_SOURCE_INFO_EXT = 0x3ba151e0;
    public static final int HAND_TRACKING_DATA_SOURCE_STATE_EXT = 0x3ba151e1;
    public static final int PLANE_DETECTOR_CREATE_INFO_EXT = 0x3ba155c9;
    public static final int PLANE_DETECTOR_BEGIN_INFO_EXT = 0x3ba155ca;
    public static final int PLANE_DETECTOR_GET_INFO_EXT = 0x3ba155cb;
    public static final int PLANE_DETECTOR_LOCATIONS_EXT = 0x3ba155cc;
    public static final int PLANE_DETECTOR_LOCATION_EXT = 0x3ba155cd;
    public static final int PLANE_DETECTOR_POLYGON_BUFFER_EXT = 0x3ba155ce;
    public static final int SYSTEM_PLANE_DETECTION_PROPERTIES_EXT = 0x3ba155cf;
    public static final int FUTURE_CANCEL_INFO_EXT = 0x3ba1f208;
    public static final int FUTURE_POLL_INFO_EXT = 0x3ba1f209;
    public static final int FUTURE_COMPLETION_EXT = 0x3ba1f20a;
    public static final int FUTURE_POLL_RESULT_EXT = 0x3ba1f20b;
    public static final int EVENT_DATA_USER_PRESENCE_CHANGED_EXT = 0x3ba1f5f0;
    public static final int SYSTEM_USER_PRESENCE_PROPERTIES_EXT = 0x3ba1f5f1;
    public static final int SPACES_LOCATE_INFO_KHR = SPACES_LOCATE_INFO;
    public static final int SPACE_LOCATIONS_KHR = SPACE_LOCATIONS;
    public static final int SPACE_VELOCITIES_KHR = SPACE_VELOCITIES;
    public static final int SYSTEM_NOTIFICATIONS_SET_INFO_ML = 0x3ba201a8;
    public static final int WORLD_MESH_DETECTOR_CREATE_INFO_ML = 0x3ba20591;
    public static final int WORLD_MESH_STATE_REQUEST_INFO_ML = 0x3ba20592;
    public static final int WORLD_MESH_BLOCK_STATE_ML = 0x3ba20593;
    public static final int WORLD_MESH_STATE_REQUEST_COMPLETION_ML = 0x3ba20594;
    public static final int WORLD_MESH_BUFFER_RECOMMENDED_SIZE_INFO_ML = 0x3ba20595;
    public static final int WORLD_MESH_BUFFER_SIZE_ML = 0x3ba20596;
    public static final int WORLD_MESH_BUFFER_ML = 0x3ba20597;
    public static final int WORLD_MESH_BLOCK_REQUEST_ML = 0x3ba20598;
    public static final int WORLD_MESH_GET_INFO_ML = 0x3ba20599;
    public static final int WORLD_MESH_BLOCK_ML = 0x3ba2059a;
    public static final int WORLD_MESH_REQUEST_COMPLETION_ML = 0x3ba2059b;
    public static final int WORLD_MESH_REQUEST_COMPLETION_INFO_ML = 0x3ba2059c;
    public static final int SYSTEM_FACIAL_EXPRESSION_PROPERTIES_ML = 0x3ba224d4;
    public static final int FACIAL_EXPRESSION_CLIENT_CREATE_INFO_ML = 0x3ba224d5;
    public static final int FACIAL_EXPRESSION_BLEND_SHAPE_GET_INFO_ML = 0x3ba224d6;
    public static final int FACIAL_EXPRESSION_BLEND_SHAPE_PROPERTIES_ML = 0x3ba224d7;
    public static final int SYSTEM_SIMULTANEOUS_HANDS_AND_CONTROLLERS_PROPERTIES_META = 0x3ba2e821;
    public static final int SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_RESUME_INFO_META = 0x3ba2e822;
    public static final int SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_PAUSE_INFO_META = 0x3ba2e823;
    public static final int COLOCATION_DISCOVERY_START_INFO_META = 0x3ba38082;
    public static final int COLOCATION_DISCOVERY_STOP_INFO_META = 0x3ba38083;
    public static final int COLOCATION_ADVERTISEMENT_START_INFO_META = 0x3ba38084;
    public static final int COLOCATION_ADVERTISEMENT_STOP_INFO_META = 0x3ba38085;
    public static final int EVENT_DATA_START_COLOCATION_ADVERTISEMENT_COMPLETE_META = 0x3ba3808c;
    public static final int EVENT_DATA_STOP_COLOCATION_ADVERTISEMENT_COMPLETE_META = 0x3ba3808d;
    public static final int EVENT_DATA_COLOCATION_ADVERTISEMENT_COMPLETE_META = 0x3ba3808e;
    public static final int EVENT_DATA_START_COLOCATION_DISCOVERY_COMPLETE_META = 0x3ba3808f;
    public static final int EVENT_DATA_COLOCATION_DISCOVERY_RESULT_META = 0x3ba38090;
    public static final int EVENT_DATA_COLOCATION_DISCOVERY_COMPLETE_META = 0x3ba38091;
    public static final int EVENT_DATA_STOP_COLOCATION_DISCOVERY_COMPLETE_META = 0x3ba38092;
    public static final int SYSTEM_COLOCATION_DISCOVERY_PROPERTIES_META = 0x3ba38096;
    public static final int SHARE_SPACES_RECIPIENT_GROUPS_META = 0x3ba38460;
    public static final int SPACE_GROUP_UUID_FILTER_INFO_META = 0x3ba38461;
    public static final int SYSTEM_SPATIAL_ENTITY_GROUP_SHARING_PROPERTIES_META = 0x3ba384c4;
    public static final int SPATIAL_CAPABILITY_COMPONENT_TYPES_EXT = 0x3ba614a0;
    public static final int SPATIAL_CONTEXT_CREATE_INFO_EXT = 0x3ba614a1;
    public static final int CREATE_SPATIAL_CONTEXT_COMPLETION_EXT = 0x3ba614a2;
    public static final int SPATIAL_DISCOVERY_SNAPSHOT_CREATE_INFO_EXT = 0x3ba614a3;
    public static final int CREATE_SPATIAL_DISCOVERY_SNAPSHOT_COMPLETION_INFO_EXT = 0x3ba614a4;
    public static final int CREATE_SPATIAL_DISCOVERY_SNAPSHOT_COMPLETION_EXT = 0x3ba614a5;
    public static final int SPATIAL_COMPONENT_DATA_QUERY_CONDITION_EXT = 0x3ba614a6;
    public static final int SPATIAL_COMPONENT_DATA_QUERY_RESULT_EXT = 0x3ba614a7;
    public static final int SPATIAL_BUFFER_GET_INFO_EXT = 0x3ba614a8;
    public static final int SPATIAL_COMPONENT_BOUNDED_2D_LIST_EXT = 0x3ba614a9;
    public static final int SPATIAL_COMPONENT_BOUNDED_3D_LIST_EXT = 0x3ba614aa;
    public static final int SPATIAL_COMPONENT_PARENT_LIST_EXT = 0x3ba614ab;
    public static final int SPATIAL_COMPONENT_MESH_3D_LIST_EXT = 0x3ba614ac;
    public static final int SPATIAL_ENTITY_FROM_ID_CREATE_INFO_EXT = 0x3ba614ad;
    public static final int SPATIAL_UPDATE_SNAPSHOT_CREATE_INFO_EXT = 0x3ba614ae;
    public static final int EVENT_DATA_SPATIAL_DISCOVERY_RECOMMENDED_EXT = 0x3ba614af;
    public static final int SPATIAL_FILTER_TRACKING_STATE_EXT = 0x3ba614b0;
    public static final int SPATIAL_CAPABILITY_CONFIGURATION_PLANE_TRACKING_EXT = 0x3ba61888;
    public static final int SPATIAL_COMPONENT_PLANE_ALIGNMENT_LIST_EXT = 0x3ba61889;
    public static final int SPATIAL_COMPONENT_MESH_2D_LIST_EXT = 0x3ba6188a;
    public static final int SPATIAL_COMPONENT_POLYGON_2D_LIST_EXT = 0x3ba6188b;
    public static final int SPATIAL_COMPONENT_PLANE_SEMANTIC_LABEL_LIST_EXT = 0x3ba6188c;
    public static final int SPATIAL_CAPABILITY_CONFIGURATION_QR_CODE_EXT = 0x3ba62058;
    public static final int SPATIAL_CAPABILITY_CONFIGURATION_MICRO_QR_CODE_EXT = 0x3ba62059;
    public static final int SPATIAL_CAPABILITY_CONFIGURATION_ARUCO_MARKER_EXT = 0x3ba6205a;
    public static final int SPATIAL_CAPABILITY_CONFIGURATION_APRIL_TAG_EXT = 0x3ba6205b;
    public static final int SPATIAL_MARKER_SIZE_EXT = 0x3ba6205c;
    public static final int SPATIAL_MARKER_STATIC_OPTIMIZATION_EXT = 0x3ba6205d;
    public static final int SPATIAL_COMPONENT_MARKER_LIST_EXT = 0x3ba6205e;
    public static final int SPATIAL_CAPABILITY_CONFIGURATION_ANCHOR_EXT = 0x3ba66a90;
    public static final int SPATIAL_COMPONENT_ANCHOR_LIST_EXT = 0x3ba66a91;
    public static final int SPATIAL_ANCHOR_CREATE_INFO_EXT = 0x3ba66a92;
    public static final int SPATIAL_PERSISTENCE_CONTEXT_CREATE_INFO_EXT = 0x3ba66e78;
    public static final int CREATE_SPATIAL_PERSISTENCE_CONTEXT_COMPLETION_EXT = 0x3ba66e79;
    public static final int SPATIAL_CONTEXT_PERSISTENCE_CONFIG_EXT = 0x3ba66e7a;
    public static final int SPATIAL_DISCOVERY_PERSISTENCE_UUID_FILTER_EXT = 0x3ba66e7b;
    public static final int SPATIAL_COMPONENT_PERSISTENCE_LIST_EXT = 0x3ba66e7c;
    public static final int SPATIAL_ENTITY_PERSIST_INFO_EXT = 0x3ba6b4c8;
    public static final int PERSIST_SPATIAL_ENTITY_COMPLETION_EXT = 0x3ba6b4c9;
    public static final int SPATIAL_ENTITY_UNPERSIST_INFO_EXT = 0x3ba6b4ca;
    public static final int UNPERSIST_SPATIAL_ENTITY_COMPLETION_EXT = 0x3ba6b4cb;

    public static String explain(@EnumType(XrStructureType.class) int value) {
        return switch (value) {
            case XrStructureType.ACTIONS_SYNC_INFO -> "XR_TYPE_ACTIONS_SYNC_INFO";
            case XrStructureType.ACTION_CREATE_INFO -> "XR_TYPE_ACTION_CREATE_INFO";
            case XrStructureType.ACTION_SET_CREATE_INFO -> "XR_TYPE_ACTION_SET_CREATE_INFO";
            case XrStructureType.ACTION_SPACE_CREATE_INFO -> "XR_TYPE_ACTION_SPACE_CREATE_INFO";
            case XrStructureType.ACTION_STATE_BOOLEAN -> "XR_TYPE_ACTION_STATE_BOOLEAN";
            case XrStructureType.ACTION_STATE_FLOAT -> "XR_TYPE_ACTION_STATE_FLOAT";
            case XrStructureType.ACTION_STATE_GET_INFO -> "XR_TYPE_ACTION_STATE_GET_INFO";
            case XrStructureType.ACTION_STATE_POSE -> "XR_TYPE_ACTION_STATE_POSE";
            case XrStructureType.ACTION_STATE_VECTOR2F -> "XR_TYPE_ACTION_STATE_VECTOR2F";
            case XrStructureType.ACTIVE_ACTION_SET_PRIORITIES_EXT -> "XR_TYPE_ACTIVE_ACTION_SET_PRIORITIES_EXT";
            case XrStructureType.ANCHOR_SPACE_CREATE_INFO_BD -> "XR_TYPE_ANCHOR_SPACE_CREATE_INFO_BD";
            case XrStructureType.ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB -> "XR_TYPE_ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB";
            case XrStructureType.API_LAYER_PROPERTIES -> "XR_TYPE_API_LAYER_PROPERTIES";
            case XrStructureType.BINDING_MODIFICATIONS_KHR -> "XR_TYPE_BINDING_MODIFICATIONS_KHR";
            case XrStructureType.BODY_JOINTS_LOCATE_INFO_BD -> "XR_TYPE_BODY_JOINTS_LOCATE_INFO_BD";
            case XrStructureType.BODY_JOINTS_LOCATE_INFO_FB -> "XR_TYPE_BODY_JOINTS_LOCATE_INFO_FB";
            case XrStructureType.BODY_JOINTS_LOCATE_INFO_HTC -> "XR_TYPE_BODY_JOINTS_LOCATE_INFO_HTC";
            case XrStructureType.BODY_JOINT_LOCATIONS_BD -> "XR_TYPE_BODY_JOINT_LOCATIONS_BD";
            case XrStructureType.BODY_JOINT_LOCATIONS_FB -> "XR_TYPE_BODY_JOINT_LOCATIONS_FB";
            case XrStructureType.BODY_JOINT_LOCATIONS_HTC -> "XR_TYPE_BODY_JOINT_LOCATIONS_HTC";
            case XrStructureType.BODY_SKELETON_FB -> "XR_TYPE_BODY_SKELETON_FB";
            case XrStructureType.BODY_SKELETON_HTC -> "XR_TYPE_BODY_SKELETON_HTC";
            case XrStructureType.BODY_TRACKER_CREATE_INFO_BD -> "XR_TYPE_BODY_TRACKER_CREATE_INFO_BD";
            case XrStructureType.BODY_TRACKER_CREATE_INFO_FB -> "XR_TYPE_BODY_TRACKER_CREATE_INFO_FB";
            case XrStructureType.BODY_TRACKER_CREATE_INFO_HTC -> "XR_TYPE_BODY_TRACKER_CREATE_INFO_HTC";
            case XrStructureType.BOUNDARY_2D_FB -> "XR_TYPE_BOUNDARY_2D_FB";
            case XrStructureType.BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO -> "XR_TYPE_BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO";
            case XrStructureType.COLOCATION_ADVERTISEMENT_START_INFO_META -> "XR_TYPE_COLOCATION_ADVERTISEMENT_START_INFO_META";
            case XrStructureType.COLOCATION_ADVERTISEMENT_STOP_INFO_META -> "XR_TYPE_COLOCATION_ADVERTISEMENT_STOP_INFO_META";
            case XrStructureType.COLOCATION_DISCOVERY_START_INFO_META -> "XR_TYPE_COLOCATION_DISCOVERY_START_INFO_META";
            case XrStructureType.COLOCATION_DISCOVERY_STOP_INFO_META -> "XR_TYPE_COLOCATION_DISCOVERY_STOP_INFO_META";
            case XrStructureType.COMPOSITION_LAYER_ALPHA_BLEND_FB -> "XR_TYPE_COMPOSITION_LAYER_ALPHA_BLEND_FB";
            case XrStructureType.COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR -> "XR_TYPE_COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR";
            case XrStructureType.COMPOSITION_LAYER_CUBE_KHR -> "XR_TYPE_COMPOSITION_LAYER_CUBE_KHR";
            case XrStructureType.COMPOSITION_LAYER_CYLINDER_KHR -> "XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR";
            case XrStructureType.COMPOSITION_LAYER_DEPTH_INFO_KHR -> "XR_TYPE_COMPOSITION_LAYER_DEPTH_INFO_KHR";
            case XrStructureType.COMPOSITION_LAYER_DEPTH_TEST_FB -> "XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_FB";
            case XrStructureType.COMPOSITION_LAYER_DEPTH_TEST_VARJO -> "XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_VARJO";
            case XrStructureType.COMPOSITION_LAYER_EQUIRECT2_KHR -> "XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR";
            case XrStructureType.COMPOSITION_LAYER_EQUIRECT_KHR -> "XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR";
            case XrStructureType.COMPOSITION_LAYER_IMAGE_LAYOUT_FB -> "XR_TYPE_COMPOSITION_LAYER_IMAGE_LAYOUT_FB";
            case XrStructureType.COMPOSITION_LAYER_PASSTHROUGH_FB -> "XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_FB";
            case XrStructureType.COMPOSITION_LAYER_PASSTHROUGH_HTC -> "XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_HTC";
            case XrStructureType.COMPOSITION_LAYER_PROJECTION -> "XR_TYPE_COMPOSITION_LAYER_PROJECTION";
            case XrStructureType.COMPOSITION_LAYER_PROJECTION_VIEW -> "XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW";
            case XrStructureType.COMPOSITION_LAYER_QUAD -> "XR_TYPE_COMPOSITION_LAYER_QUAD";
            case XrStructureType.COMPOSITION_LAYER_REPROJECTION_INFO_MSFT -> "XR_TYPE_COMPOSITION_LAYER_REPROJECTION_INFO_MSFT";
            case XrStructureType.COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT -> "XR_TYPE_COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT";
            case XrStructureType.COMPOSITION_LAYER_SECURE_CONTENT_FB -> "XR_TYPE_COMPOSITION_LAYER_SECURE_CONTENT_FB";
            case XrStructureType.COMPOSITION_LAYER_SETTINGS_FB -> "XR_TYPE_COMPOSITION_LAYER_SETTINGS_FB";
            case XrStructureType.COMPOSITION_LAYER_SPACE_WARP_INFO_FB -> "XR_TYPE_COMPOSITION_LAYER_SPACE_WARP_INFO_FB";
            case XrStructureType.CONTROLLER_MODEL_KEY_STATE_MSFT -> "XR_TYPE_CONTROLLER_MODEL_KEY_STATE_MSFT";
            case XrStructureType.CONTROLLER_MODEL_NODE_PROPERTIES_MSFT -> "XR_TYPE_CONTROLLER_MODEL_NODE_PROPERTIES_MSFT";
            case XrStructureType.CONTROLLER_MODEL_NODE_STATE_MSFT -> "XR_TYPE_CONTROLLER_MODEL_NODE_STATE_MSFT";
            case XrStructureType.CONTROLLER_MODEL_PROPERTIES_MSFT -> "XR_TYPE_CONTROLLER_MODEL_PROPERTIES_MSFT";
            case XrStructureType.CONTROLLER_MODEL_STATE_MSFT -> "XR_TYPE_CONTROLLER_MODEL_STATE_MSFT";
            case XrStructureType.COORDINATE_SPACE_CREATE_INFO_ML -> "XR_TYPE_COORDINATE_SPACE_CREATE_INFO_ML";
            case XrStructureType.CREATE_SPATIAL_ANCHORS_COMPLETION_ML -> "XR_TYPE_CREATE_SPATIAL_ANCHORS_COMPLETION_ML";
            case XrStructureType.CREATE_SPATIAL_CONTEXT_COMPLETION_EXT -> "XR_TYPE_CREATE_SPATIAL_CONTEXT_COMPLETION_EXT";
            case XrStructureType.CREATE_SPATIAL_DISCOVERY_SNAPSHOT_COMPLETION_EXT -> "XR_TYPE_CREATE_SPATIAL_DISCOVERY_SNAPSHOT_COMPLETION_EXT";
            case XrStructureType.CREATE_SPATIAL_DISCOVERY_SNAPSHOT_COMPLETION_INFO_EXT -> "XR_TYPE_CREATE_SPATIAL_DISCOVERY_SNAPSHOT_COMPLETION_INFO_EXT";
            case XrStructureType.CREATE_SPATIAL_PERSISTENCE_CONTEXT_COMPLETION_EXT -> "XR_TYPE_CREATE_SPATIAL_PERSISTENCE_CONTEXT_COMPLETION_EXT";
            case XrStructureType.DEBUG_UTILS_LABEL_EXT -> "XR_TYPE_DEBUG_UTILS_LABEL_EXT";
            case XrStructureType.DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT -> "XR_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT";
            case XrStructureType.DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT -> "XR_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT";
            case XrStructureType.DEBUG_UTILS_OBJECT_NAME_INFO_EXT -> "XR_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT";
            case XrStructureType.DEVICE_PCM_SAMPLE_RATE_STATE_FB -> "XR_TYPE_DEVICE_PCM_SAMPLE_RATE_STATE_FB";
            case XrStructureType.DIGITAL_LENS_CONTROL_ALMALENCE -> "XR_TYPE_DIGITAL_LENS_CONTROL_ALMALENCE";
            case XrStructureType.ENVIRONMENT_DEPTH_HAND_REMOVAL_SET_INFO_META -> "XR_TYPE_ENVIRONMENT_DEPTH_HAND_REMOVAL_SET_INFO_META";
            case XrStructureType.ENVIRONMENT_DEPTH_IMAGE_ACQUIRE_INFO_META -> "XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_ACQUIRE_INFO_META";
            case XrStructureType.ENVIRONMENT_DEPTH_IMAGE_META -> "XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_META";
            case XrStructureType.ENVIRONMENT_DEPTH_IMAGE_VIEW_META -> "XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_VIEW_META";
            case XrStructureType.ENVIRONMENT_DEPTH_PROVIDER_CREATE_INFO_META -> "XR_TYPE_ENVIRONMENT_DEPTH_PROVIDER_CREATE_INFO_META";
            case XrStructureType.ENVIRONMENT_DEPTH_SWAPCHAIN_CREATE_INFO_META -> "XR_TYPE_ENVIRONMENT_DEPTH_SWAPCHAIN_CREATE_INFO_META";
            case XrStructureType.ENVIRONMENT_DEPTH_SWAPCHAIN_STATE_META -> "XR_TYPE_ENVIRONMENT_DEPTH_SWAPCHAIN_STATE_META";
            case XrStructureType.EVENT_DATA_BUFFER -> "XR_TYPE_EVENT_DATA_BUFFER";
            case XrStructureType.EVENT_DATA_COLOCATION_ADVERTISEMENT_COMPLETE_META -> "XR_TYPE_EVENT_DATA_COLOCATION_ADVERTISEMENT_COMPLETE_META";
            case XrStructureType.EVENT_DATA_COLOCATION_DISCOVERY_COMPLETE_META -> "XR_TYPE_EVENT_DATA_COLOCATION_DISCOVERY_COMPLETE_META";
            case XrStructureType.EVENT_DATA_COLOCATION_DISCOVERY_RESULT_META -> "XR_TYPE_EVENT_DATA_COLOCATION_DISCOVERY_RESULT_META";
            case XrStructureType.EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB -> "XR_TYPE_EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB";
            case XrStructureType.EVENT_DATA_EVENTS_LOST -> "XR_TYPE_EVENT_DATA_EVENTS_LOST";
            case XrStructureType.EVENT_DATA_EYE_CALIBRATION_CHANGED_ML -> "XR_TYPE_EVENT_DATA_EYE_CALIBRATION_CHANGED_ML";
            case XrStructureType.EVENT_DATA_HEADSET_FIT_CHANGED_ML -> "XR_TYPE_EVENT_DATA_HEADSET_FIT_CHANGED_ML";
            case XrStructureType.EVENT_DATA_INSTANCE_LOSS_PENDING -> "XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING";
            case XrStructureType.EVENT_DATA_INTERACTION_PROFILE_CHANGED -> "XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED";
            case XrStructureType.EVENT_DATA_INTERACTION_RENDER_MODELS_CHANGED_EXT -> "XR_TYPE_EVENT_DATA_INTERACTION_RENDER_MODELS_CHANGED_EXT";
            case XrStructureType.EVENT_DATA_LOCALIZATION_CHANGED_ML -> "XR_TYPE_EVENT_DATA_LOCALIZATION_CHANGED_ML";
            case XrStructureType.EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX -> "XR_TYPE_EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX";
            case XrStructureType.EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO -> "XR_TYPE_EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO";
            case XrStructureType.EVENT_DATA_PASSTHROUGH_LAYER_RESUMED_META -> "XR_TYPE_EVENT_DATA_PASSTHROUGH_LAYER_RESUMED_META";
            case XrStructureType.EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB -> "XR_TYPE_EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB";
            case XrStructureType.EVENT_DATA_PERF_SETTINGS_EXT -> "XR_TYPE_EVENT_DATA_PERF_SETTINGS_EXT";
            case XrStructureType.EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING -> "XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING";
            case XrStructureType.EVENT_DATA_SCENE_CAPTURE_COMPLETE_FB -> "XR_TYPE_EVENT_DATA_SCENE_CAPTURE_COMPLETE_FB";
            case XrStructureType.EVENT_DATA_SENSE_DATA_PROVIDER_STATE_CHANGED_BD -> "XR_TYPE_EVENT_DATA_SENSE_DATA_PROVIDER_STATE_CHANGED_BD";
            case XrStructureType.EVENT_DATA_SENSE_DATA_UPDATED_BD -> "XR_TYPE_EVENT_DATA_SENSE_DATA_UPDATED_BD";
            case XrStructureType.EVENT_DATA_SESSION_STATE_CHANGED -> "XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED";
            case XrStructureType.EVENT_DATA_SHARE_SPACES_COMPLETE_META -> "XR_TYPE_EVENT_DATA_SHARE_SPACES_COMPLETE_META";
            case XrStructureType.EVENT_DATA_SPACE_ERASE_COMPLETE_FB -> "XR_TYPE_EVENT_DATA_SPACE_ERASE_COMPLETE_FB";
            case XrStructureType.EVENT_DATA_SPACE_LIST_SAVE_COMPLETE_FB -> "XR_TYPE_EVENT_DATA_SPACE_LIST_SAVE_COMPLETE_FB";
            case XrStructureType.EVENT_DATA_SPACE_QUERY_COMPLETE_FB -> "XR_TYPE_EVENT_DATA_SPACE_QUERY_COMPLETE_FB";
            case XrStructureType.EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB -> "XR_TYPE_EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB";
            case XrStructureType.EVENT_DATA_SPACE_SAVE_COMPLETE_FB -> "XR_TYPE_EVENT_DATA_SPACE_SAVE_COMPLETE_FB";
            case XrStructureType.EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB -> "XR_TYPE_EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB";
            case XrStructureType.EVENT_DATA_SPACE_SHARE_COMPLETE_FB -> "XR_TYPE_EVENT_DATA_SPACE_SHARE_COMPLETE_FB";
            case XrStructureType.EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB -> "XR_TYPE_EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB";
            case XrStructureType.EVENT_DATA_SPATIAL_DISCOVERY_RECOMMENDED_EXT -> "XR_TYPE_EVENT_DATA_SPATIAL_DISCOVERY_RECOMMENDED_EXT";
            case XrStructureType.EVENT_DATA_START_COLOCATION_ADVERTISEMENT_COMPLETE_META -> "XR_TYPE_EVENT_DATA_START_COLOCATION_ADVERTISEMENT_COMPLETE_META";
            case XrStructureType.EVENT_DATA_START_COLOCATION_DISCOVERY_COMPLETE_META -> "XR_TYPE_EVENT_DATA_START_COLOCATION_DISCOVERY_COMPLETE_META";
            case XrStructureType.EVENT_DATA_STOP_COLOCATION_ADVERTISEMENT_COMPLETE_META -> "XR_TYPE_EVENT_DATA_STOP_COLOCATION_ADVERTISEMENT_COMPLETE_META";
            case XrStructureType.EVENT_DATA_STOP_COLOCATION_DISCOVERY_COMPLETE_META -> "XR_TYPE_EVENT_DATA_STOP_COLOCATION_DISCOVERY_COMPLETE_META";
            case XrStructureType.EVENT_DATA_USER_PRESENCE_CHANGED_EXT -> "XR_TYPE_EVENT_DATA_USER_PRESENCE_CHANGED_EXT";
            case XrStructureType.EVENT_DATA_VIRTUAL_KEYBOARD_BACKSPACE_META -> "XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_BACKSPACE_META";
            case XrStructureType.EVENT_DATA_VIRTUAL_KEYBOARD_COMMIT_TEXT_META -> "XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_COMMIT_TEXT_META";
            case XrStructureType.EVENT_DATA_VIRTUAL_KEYBOARD_ENTER_META -> "XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_ENTER_META";
            case XrStructureType.EVENT_DATA_VIRTUAL_KEYBOARD_HIDDEN_META -> "XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_HIDDEN_META";
            case XrStructureType.EVENT_DATA_VIRTUAL_KEYBOARD_SHOWN_META -> "XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_SHOWN_META";
            case XrStructureType.EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR -> "XR_TYPE_EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR";
            case XrStructureType.EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX -> "XR_TYPE_EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX";
            case XrStructureType.EXTENSION_PROPERTIES -> "XR_TYPE_EXTENSION_PROPERTIES";
            case XrStructureType.EXTERNAL_CAMERA_OCULUS -> "XR_TYPE_EXTERNAL_CAMERA_OCULUS";
            case XrStructureType.EYE_GAZES_FB -> "XR_TYPE_EYE_GAZES_FB";
            case XrStructureType.EYE_GAZES_INFO_FB -> "XR_TYPE_EYE_GAZES_INFO_FB";
            case XrStructureType.EYE_GAZE_SAMPLE_TIME_EXT -> "XR_TYPE_EYE_GAZE_SAMPLE_TIME_EXT";
            case XrStructureType.EYE_TRACKER_CREATE_INFO_FB -> "XR_TYPE_EYE_TRACKER_CREATE_INFO_FB";
            case XrStructureType.FACE_EXPRESSION_INFO2_FB -> "XR_TYPE_FACE_EXPRESSION_INFO2_FB";
            case XrStructureType.FACE_EXPRESSION_INFO_FB -> "XR_TYPE_FACE_EXPRESSION_INFO_FB";
            case XrStructureType.FACE_EXPRESSION_WEIGHTS2_FB -> "XR_TYPE_FACE_EXPRESSION_WEIGHTS2_FB";
            case XrStructureType.FACE_EXPRESSION_WEIGHTS_FB -> "XR_TYPE_FACE_EXPRESSION_WEIGHTS_FB";
            case XrStructureType.FACE_TRACKER_CREATE_INFO2_FB -> "XR_TYPE_FACE_TRACKER_CREATE_INFO2_FB";
            case XrStructureType.FACE_TRACKER_CREATE_INFO_FB -> "XR_TYPE_FACE_TRACKER_CREATE_INFO_FB";
            case XrStructureType.FACIAL_EXPRESSIONS_HTC -> "XR_TYPE_FACIAL_EXPRESSIONS_HTC";
            case XrStructureType.FACIAL_EXPRESSION_BLEND_SHAPE_GET_INFO_ML -> "XR_TYPE_FACIAL_EXPRESSION_BLEND_SHAPE_GET_INFO_ML";
            case XrStructureType.FACIAL_EXPRESSION_BLEND_SHAPE_PROPERTIES_ML -> "XR_TYPE_FACIAL_EXPRESSION_BLEND_SHAPE_PROPERTIES_ML";
            case XrStructureType.FACIAL_EXPRESSION_CLIENT_CREATE_INFO_ML -> "XR_TYPE_FACIAL_EXPRESSION_CLIENT_CREATE_INFO_ML";
            case XrStructureType.FACIAL_TRACKER_CREATE_INFO_HTC -> "XR_TYPE_FACIAL_TRACKER_CREATE_INFO_HTC";
            case XrStructureType.FORCE_FEEDBACK_CURL_APPLY_LOCATIONS_MNDX -> "XR_TYPE_FORCE_FEEDBACK_CURL_APPLY_LOCATIONS_MNDX";
            case XrStructureType.FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO -> "XR_TYPE_FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO";
            case XrStructureType.FOVEATION_APPLY_INFO_HTC -> "XR_TYPE_FOVEATION_APPLY_INFO_HTC";
            case XrStructureType.FOVEATION_CUSTOM_MODE_INFO_HTC -> "XR_TYPE_FOVEATION_CUSTOM_MODE_INFO_HTC";
            case XrStructureType.FOVEATION_DYNAMIC_MODE_INFO_HTC -> "XR_TYPE_FOVEATION_DYNAMIC_MODE_INFO_HTC";
            case XrStructureType.FOVEATION_EYE_TRACKED_PROFILE_CREATE_INFO_META -> "XR_TYPE_FOVEATION_EYE_TRACKED_PROFILE_CREATE_INFO_META";
            case XrStructureType.FOVEATION_EYE_TRACKED_STATE_META -> "XR_TYPE_FOVEATION_EYE_TRACKED_STATE_META";
            case XrStructureType.FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB -> "XR_TYPE_FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB";
            case XrStructureType.FOVEATION_PROFILE_CREATE_INFO_FB -> "XR_TYPE_FOVEATION_PROFILE_CREATE_INFO_FB";
            case XrStructureType.FRAME_BEGIN_INFO -> "XR_TYPE_FRAME_BEGIN_INFO";
            case XrStructureType.FRAME_END_INFO -> "XR_TYPE_FRAME_END_INFO";
            case XrStructureType.FRAME_END_INFO_ML -> "XR_TYPE_FRAME_END_INFO_ML";
            case XrStructureType.FRAME_STATE -> "XR_TYPE_FRAME_STATE";
            case XrStructureType.FRAME_SYNTHESIS_CONFIG_VIEW_EXT -> "XR_TYPE_FRAME_SYNTHESIS_CONFIG_VIEW_EXT";
            case XrStructureType.FRAME_SYNTHESIS_INFO_EXT -> "XR_TYPE_FRAME_SYNTHESIS_INFO_EXT";
            case XrStructureType.FRAME_WAIT_INFO -> "XR_TYPE_FRAME_WAIT_INFO";
            case XrStructureType.FUTURE_CANCEL_INFO_EXT -> "XR_TYPE_FUTURE_CANCEL_INFO_EXT";
            case XrStructureType.FUTURE_COMPLETION_EXT -> "XR_TYPE_FUTURE_COMPLETION_EXT";
            case XrStructureType.FUTURE_POLL_INFO_EXT -> "XR_TYPE_FUTURE_POLL_INFO_EXT";
            case XrStructureType.FUTURE_POLL_RESULT_EXT -> "XR_TYPE_FUTURE_POLL_RESULT_EXT";
            case XrStructureType.FUTURE_POLL_RESULT_PROGRESS_BD -> "XR_TYPE_FUTURE_POLL_RESULT_PROGRESS_BD";
            case XrStructureType.GEOMETRY_INSTANCE_CREATE_INFO_FB -> "XR_TYPE_GEOMETRY_INSTANCE_CREATE_INFO_FB";
            case XrStructureType.GEOMETRY_INSTANCE_TRANSFORM_FB -> "XR_TYPE_GEOMETRY_INSTANCE_TRANSFORM_FB";
            case XrStructureType.GLOBAL_DIMMER_FRAME_END_INFO_ML -> "XR_TYPE_GLOBAL_DIMMER_FRAME_END_INFO_ML";
            case XrStructureType.GRAPHICS_BINDING_D3D11_KHR -> "XR_TYPE_GRAPHICS_BINDING_D3D11_KHR";
            case XrStructureType.GRAPHICS_BINDING_D3D12_KHR -> "XR_TYPE_GRAPHICS_BINDING_D3D12_KHR";
            case XrStructureType.GRAPHICS_BINDING_EGL_MNDX -> "XR_TYPE_GRAPHICS_BINDING_EGL_MNDX";
            case XrStructureType.GRAPHICS_BINDING_METAL_KHR -> "XR_TYPE_GRAPHICS_BINDING_METAL_KHR";
            case XrStructureType.GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR -> "XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR";
            case XrStructureType.GRAPHICS_BINDING_OPENGL_WAYLAND_KHR -> "XR_TYPE_GRAPHICS_BINDING_OPENGL_WAYLAND_KHR";
            case XrStructureType.GRAPHICS_BINDING_OPENGL_WIN32_KHR -> "XR_TYPE_GRAPHICS_BINDING_OPENGL_WIN32_KHR";
            case XrStructureType.GRAPHICS_BINDING_OPENGL_XCB_KHR -> "XR_TYPE_GRAPHICS_BINDING_OPENGL_XCB_KHR";
            case XrStructureType.GRAPHICS_BINDING_OPENGL_XLIB_KHR -> "XR_TYPE_GRAPHICS_BINDING_OPENGL_XLIB_KHR";
            case XrStructureType.GRAPHICS_BINDING_VULKAN_KHR -> "XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR";
            case XrStructureType.GRAPHICS_REQUIREMENTS_D3D11_KHR -> "XR_TYPE_GRAPHICS_REQUIREMENTS_D3D11_KHR";
            case XrStructureType.GRAPHICS_REQUIREMENTS_D3D12_KHR -> "XR_TYPE_GRAPHICS_REQUIREMENTS_D3D12_KHR";
            case XrStructureType.GRAPHICS_REQUIREMENTS_METAL_KHR -> "XR_TYPE_GRAPHICS_REQUIREMENTS_METAL_KHR";
            case XrStructureType.GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR -> "XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR";
            case XrStructureType.GRAPHICS_REQUIREMENTS_OPENGL_KHR -> "XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_KHR";
            case XrStructureType.GRAPHICS_REQUIREMENTS_VULKAN_KHR -> "XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR";
            case XrStructureType.HAND_JOINTS_LOCATE_INFO_EXT -> "XR_TYPE_HAND_JOINTS_LOCATE_INFO_EXT";
            case XrStructureType.HAND_JOINTS_MOTION_RANGE_INFO_EXT -> "XR_TYPE_HAND_JOINTS_MOTION_RANGE_INFO_EXT";
            case XrStructureType.HAND_JOINT_LOCATIONS_EXT -> "XR_TYPE_HAND_JOINT_LOCATIONS_EXT";
            case XrStructureType.HAND_JOINT_VELOCITIES_EXT -> "XR_TYPE_HAND_JOINT_VELOCITIES_EXT";
            case XrStructureType.HAND_MESH_MSFT -> "XR_TYPE_HAND_MESH_MSFT";
            case XrStructureType.HAND_MESH_SPACE_CREATE_INFO_MSFT -> "XR_TYPE_HAND_MESH_SPACE_CREATE_INFO_MSFT";
            case XrStructureType.HAND_MESH_UPDATE_INFO_MSFT -> "XR_TYPE_HAND_MESH_UPDATE_INFO_MSFT";
            case XrStructureType.HAND_POSE_TYPE_INFO_MSFT -> "XR_TYPE_HAND_POSE_TYPE_INFO_MSFT";
            case XrStructureType.HAND_TRACKER_CREATE_INFO_EXT -> "XR_TYPE_HAND_TRACKER_CREATE_INFO_EXT";
            case XrStructureType.HAND_TRACKING_AIM_STATE_FB -> "XR_TYPE_HAND_TRACKING_AIM_STATE_FB";
            case XrStructureType.HAND_TRACKING_CAPSULES_STATE_FB -> "XR_TYPE_HAND_TRACKING_CAPSULES_STATE_FB";
            case XrStructureType.HAND_TRACKING_DATA_SOURCE_INFO_EXT -> "XR_TYPE_HAND_TRACKING_DATA_SOURCE_INFO_EXT";
            case XrStructureType.HAND_TRACKING_DATA_SOURCE_STATE_EXT -> "XR_TYPE_HAND_TRACKING_DATA_SOURCE_STATE_EXT";
            case XrStructureType.HAND_TRACKING_MESH_FB -> "XR_TYPE_HAND_TRACKING_MESH_FB";
            case XrStructureType.HAND_TRACKING_SCALE_FB -> "XR_TYPE_HAND_TRACKING_SCALE_FB";
            case XrStructureType.HAPTIC_ACTION_INFO -> "XR_TYPE_HAPTIC_ACTION_INFO";
            case XrStructureType.HAPTIC_AMPLITUDE_ENVELOPE_VIBRATION_FB -> "XR_TYPE_HAPTIC_AMPLITUDE_ENVELOPE_VIBRATION_FB";
            case XrStructureType.HAPTIC_PCM_VIBRATION_FB -> "XR_TYPE_HAPTIC_PCM_VIBRATION_FB";
            case XrStructureType.HAPTIC_VIBRATION -> "XR_TYPE_HAPTIC_VIBRATION";
            case XrStructureType.HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT -> "XR_TYPE_HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT";
            case XrStructureType.INPUT_SOURCE_LOCALIZED_NAME_GET_INFO -> "XR_TYPE_INPUT_SOURCE_LOCALIZED_NAME_GET_INFO";
            case XrStructureType.INSTANCE_CREATE_INFO -> "XR_TYPE_INSTANCE_CREATE_INFO";
            case XrStructureType.INSTANCE_CREATE_INFO_ANDROID_KHR -> "XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR";
            case XrStructureType.INSTANCE_PROPERTIES -> "XR_TYPE_INSTANCE_PROPERTIES";
            case XrStructureType.INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE -> "XR_TYPE_INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE";
            case XrStructureType.INTERACTION_PROFILE_DPAD_BINDING_EXT -> "XR_TYPE_INTERACTION_PROFILE_DPAD_BINDING_EXT";
            case XrStructureType.INTERACTION_PROFILE_STATE -> "XR_TYPE_INTERACTION_PROFILE_STATE";
            case XrStructureType.INTERACTION_PROFILE_SUGGESTED_BINDING -> "XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING";
            case XrStructureType.INTERACTION_RENDER_MODEL_IDS_ENUMERATE_INFO_EXT -> "XR_TYPE_INTERACTION_RENDER_MODEL_IDS_ENUMERATE_INFO_EXT";
            case XrStructureType.INTERACTION_RENDER_MODEL_SUBACTION_PATH_INFO_EXT -> "XR_TYPE_INTERACTION_RENDER_MODEL_SUBACTION_PATH_INFO_EXT";
            case XrStructureType.INTERACTION_RENDER_MODEL_TOP_LEVEL_USER_PATH_GET_INFO_EXT -> "XR_TYPE_INTERACTION_RENDER_MODEL_TOP_LEVEL_USER_PATH_GET_INFO_EXT";
            case XrStructureType.KEYBOARD_SPACE_CREATE_INFO_FB -> "XR_TYPE_KEYBOARD_SPACE_CREATE_INFO_FB";
            case XrStructureType.KEYBOARD_TRACKING_QUERY_FB -> "XR_TYPE_KEYBOARD_TRACKING_QUERY_FB";
            case XrStructureType.LOADER_INIT_INFO_ANDROID_KHR -> "XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR";
            case XrStructureType.LOCALIZATION_ENABLE_EVENTS_INFO_ML -> "XR_TYPE_LOCALIZATION_ENABLE_EVENTS_INFO_ML";
            case XrStructureType.LOCALIZATION_MAP_IMPORT_INFO_ML -> "XR_TYPE_LOCALIZATION_MAP_IMPORT_INFO_ML";
            case XrStructureType.LOCALIZATION_MAP_ML -> "XR_TYPE_LOCALIZATION_MAP_ML";
            case XrStructureType.LOCAL_DIMMING_FRAME_END_INFO_META -> "XR_TYPE_LOCAL_DIMMING_FRAME_END_INFO_META";
            case XrStructureType.MAP_LOCALIZATION_REQUEST_INFO_ML -> "XR_TYPE_MAP_LOCALIZATION_REQUEST_INFO_ML";
            case XrStructureType.MARKER_DETECTOR_APRIL_TAG_INFO_ML -> "XR_TYPE_MARKER_DETECTOR_APRIL_TAG_INFO_ML";
            case XrStructureType.MARKER_DETECTOR_ARUCO_INFO_ML -> "XR_TYPE_MARKER_DETECTOR_ARUCO_INFO_ML";
            case XrStructureType.MARKER_DETECTOR_CREATE_INFO_ML -> "XR_TYPE_MARKER_DETECTOR_CREATE_INFO_ML";
            case XrStructureType.MARKER_DETECTOR_CUSTOM_PROFILE_INFO_ML -> "XR_TYPE_MARKER_DETECTOR_CUSTOM_PROFILE_INFO_ML";
            case XrStructureType.MARKER_DETECTOR_SIZE_INFO_ML -> "XR_TYPE_MARKER_DETECTOR_SIZE_INFO_ML";
            case XrStructureType.MARKER_DETECTOR_SNAPSHOT_INFO_ML -> "XR_TYPE_MARKER_DETECTOR_SNAPSHOT_INFO_ML";
            case XrStructureType.MARKER_DETECTOR_STATE_ML -> "XR_TYPE_MARKER_DETECTOR_STATE_ML";
            case XrStructureType.MARKER_SPACE_CREATE_INFO_ML -> "XR_TYPE_MARKER_SPACE_CREATE_INFO_ML";
            case XrStructureType.MARKER_SPACE_CREATE_INFO_VARJO -> "XR_TYPE_MARKER_SPACE_CREATE_INFO_VARJO";
            case XrStructureType.NEW_SCENE_COMPUTE_INFO_MSFT -> "XR_TYPE_NEW_SCENE_COMPUTE_INFO_MSFT";
            case XrStructureType.PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB -> "XR_TYPE_PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB";
            case XrStructureType.PASSTHROUGH_COLOR_HTC -> "XR_TYPE_PASSTHROUGH_COLOR_HTC";
            case XrStructureType.PASSTHROUGH_COLOR_LUT_CREATE_INFO_META -> "XR_TYPE_PASSTHROUGH_COLOR_LUT_CREATE_INFO_META";
            case XrStructureType.PASSTHROUGH_COLOR_LUT_UPDATE_INFO_META -> "XR_TYPE_PASSTHROUGH_COLOR_LUT_UPDATE_INFO_META";
            case XrStructureType.PASSTHROUGH_COLOR_MAP_INTERPOLATED_LUT_META -> "XR_TYPE_PASSTHROUGH_COLOR_MAP_INTERPOLATED_LUT_META";
            case XrStructureType.PASSTHROUGH_COLOR_MAP_LUT_META -> "XR_TYPE_PASSTHROUGH_COLOR_MAP_LUT_META";
            case XrStructureType.PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB -> "XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB";
            case XrStructureType.PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB -> "XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB";
            case XrStructureType.PASSTHROUGH_CREATE_INFO_FB -> "XR_TYPE_PASSTHROUGH_CREATE_INFO_FB";
            case XrStructureType.PASSTHROUGH_CREATE_INFO_HTC -> "XR_TYPE_PASSTHROUGH_CREATE_INFO_HTC";
            case XrStructureType.PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB -> "XR_TYPE_PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB";
            case XrStructureType.PASSTHROUGH_LAYER_CREATE_INFO_FB -> "XR_TYPE_PASSTHROUGH_LAYER_CREATE_INFO_FB";
            case XrStructureType.PASSTHROUGH_MESH_TRANSFORM_INFO_HTC -> "XR_TYPE_PASSTHROUGH_MESH_TRANSFORM_INFO_HTC";
            case XrStructureType.PASSTHROUGH_PREFERENCES_META -> "XR_TYPE_PASSTHROUGH_PREFERENCES_META";
            case XrStructureType.PASSTHROUGH_STYLE_FB -> "XR_TYPE_PASSTHROUGH_STYLE_FB";
            case XrStructureType.PERFORMANCE_METRICS_COUNTER_META -> "XR_TYPE_PERFORMANCE_METRICS_COUNTER_META";
            case XrStructureType.PERFORMANCE_METRICS_STATE_META -> "XR_TYPE_PERFORMANCE_METRICS_STATE_META";
            case XrStructureType.PERSIST_SPATIAL_ENTITY_COMPLETION_EXT -> "XR_TYPE_PERSIST_SPATIAL_ENTITY_COMPLETION_EXT";
            case XrStructureType.PLANE_DETECTOR_BEGIN_INFO_EXT -> "XR_TYPE_PLANE_DETECTOR_BEGIN_INFO_EXT";
            case XrStructureType.PLANE_DETECTOR_CREATE_INFO_EXT -> "XR_TYPE_PLANE_DETECTOR_CREATE_INFO_EXT";
            case XrStructureType.PLANE_DETECTOR_GET_INFO_EXT -> "XR_TYPE_PLANE_DETECTOR_GET_INFO_EXT";
            case XrStructureType.PLANE_DETECTOR_LOCATIONS_EXT -> "XR_TYPE_PLANE_DETECTOR_LOCATIONS_EXT";
            case XrStructureType.PLANE_DETECTOR_LOCATION_EXT -> "XR_TYPE_PLANE_DETECTOR_LOCATION_EXT";
            case XrStructureType.PLANE_DETECTOR_POLYGON_BUFFER_EXT -> "XR_TYPE_PLANE_DETECTOR_POLYGON_BUFFER_EXT";
            case XrStructureType.QUERIED_SENSE_DATA_BD -> "XR_TYPE_QUERIED_SENSE_DATA_BD";
            case XrStructureType.QUERIED_SENSE_DATA_GET_INFO_BD -> "XR_TYPE_QUERIED_SENSE_DATA_GET_INFO_BD";
            case XrStructureType.RECOMMENDED_LAYER_RESOLUTION_GET_INFO_META -> "XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_GET_INFO_META";
            case XrStructureType.RECOMMENDED_LAYER_RESOLUTION_META -> "XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_META";
            case XrStructureType.REFERENCE_SPACE_CREATE_INFO -> "XR_TYPE_REFERENCE_SPACE_CREATE_INFO";
            case XrStructureType.RENDER_MODEL_ASSET_CREATE_INFO_EXT -> "XR_TYPE_RENDER_MODEL_ASSET_CREATE_INFO_EXT";
            case XrStructureType.RENDER_MODEL_ASSET_DATA_EXT -> "XR_TYPE_RENDER_MODEL_ASSET_DATA_EXT";
            case XrStructureType.RENDER_MODEL_ASSET_DATA_GET_INFO_EXT -> "XR_TYPE_RENDER_MODEL_ASSET_DATA_GET_INFO_EXT";
            case XrStructureType.RENDER_MODEL_ASSET_PROPERTIES_EXT -> "XR_TYPE_RENDER_MODEL_ASSET_PROPERTIES_EXT";
            case XrStructureType.RENDER_MODEL_ASSET_PROPERTIES_GET_INFO_EXT -> "XR_TYPE_RENDER_MODEL_ASSET_PROPERTIES_GET_INFO_EXT";
            case XrStructureType.RENDER_MODEL_BUFFER_FB -> "XR_TYPE_RENDER_MODEL_BUFFER_FB";
            case XrStructureType.RENDER_MODEL_CAPABILITIES_REQUEST_FB -> "XR_TYPE_RENDER_MODEL_CAPABILITIES_REQUEST_FB";
            case XrStructureType.RENDER_MODEL_CREATE_INFO_EXT -> "XR_TYPE_RENDER_MODEL_CREATE_INFO_EXT";
            case XrStructureType.RENDER_MODEL_LOAD_INFO_FB -> "XR_TYPE_RENDER_MODEL_LOAD_INFO_FB";
            case XrStructureType.RENDER_MODEL_PATH_INFO_FB -> "XR_TYPE_RENDER_MODEL_PATH_INFO_FB";
            case XrStructureType.RENDER_MODEL_PROPERTIES_EXT -> "XR_TYPE_RENDER_MODEL_PROPERTIES_EXT";
            case XrStructureType.RENDER_MODEL_PROPERTIES_FB -> "XR_TYPE_RENDER_MODEL_PROPERTIES_FB";
            case XrStructureType.RENDER_MODEL_PROPERTIES_GET_INFO_EXT -> "XR_TYPE_RENDER_MODEL_PROPERTIES_GET_INFO_EXT";
            case XrStructureType.RENDER_MODEL_SPACE_CREATE_INFO_EXT -> "XR_TYPE_RENDER_MODEL_SPACE_CREATE_INFO_EXT";
            case XrStructureType.RENDER_MODEL_STATE_EXT -> "XR_TYPE_RENDER_MODEL_STATE_EXT";
            case XrStructureType.RENDER_MODEL_STATE_GET_INFO_EXT -> "XR_TYPE_RENDER_MODEL_STATE_GET_INFO_EXT";
            case XrStructureType.ROOM_LAYOUT_FB -> "XR_TYPE_ROOM_LAYOUT_FB";
            case XrStructureType.SCENE_CAPTURE_INFO_BD -> "XR_TYPE_SCENE_CAPTURE_INFO_BD";
            case XrStructureType.SCENE_CAPTURE_REQUEST_INFO_FB -> "XR_TYPE_SCENE_CAPTURE_REQUEST_INFO_FB";
            case XrStructureType.SCENE_COMPONENTS_GET_INFO_MSFT -> "XR_TYPE_SCENE_COMPONENTS_GET_INFO_MSFT";
            case XrStructureType.SCENE_COMPONENTS_LOCATE_INFO_MSFT -> "XR_TYPE_SCENE_COMPONENTS_LOCATE_INFO_MSFT";
            case XrStructureType.SCENE_COMPONENTS_MSFT -> "XR_TYPE_SCENE_COMPONENTS_MSFT";
            case XrStructureType.SCENE_COMPONENT_LOCATIONS_MSFT -> "XR_TYPE_SCENE_COMPONENT_LOCATIONS_MSFT";
            case XrStructureType.SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT -> "XR_TYPE_SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT";
            case XrStructureType.SCENE_CREATE_INFO_MSFT -> "XR_TYPE_SCENE_CREATE_INFO_MSFT";
            case XrStructureType.SCENE_DESERIALIZE_INFO_MSFT -> "XR_TYPE_SCENE_DESERIALIZE_INFO_MSFT";
            case XrStructureType.SCENE_MARKERS_MSFT -> "XR_TYPE_SCENE_MARKERS_MSFT";
            case XrStructureType.SCENE_MARKER_QR_CODES_MSFT -> "XR_TYPE_SCENE_MARKER_QR_CODES_MSFT";
            case XrStructureType.SCENE_MARKER_TYPE_FILTER_MSFT -> "XR_TYPE_SCENE_MARKER_TYPE_FILTER_MSFT";
            case XrStructureType.SCENE_MESHES_MSFT -> "XR_TYPE_SCENE_MESHES_MSFT";
            case XrStructureType.SCENE_MESH_BUFFERS_GET_INFO_MSFT -> "XR_TYPE_SCENE_MESH_BUFFERS_GET_INFO_MSFT";
            case XrStructureType.SCENE_MESH_BUFFERS_MSFT -> "XR_TYPE_SCENE_MESH_BUFFERS_MSFT";
            case XrStructureType.SCENE_MESH_INDICES_UINT16_MSFT -> "XR_TYPE_SCENE_MESH_INDICES_UINT16_MSFT";
            case XrStructureType.SCENE_MESH_INDICES_UINT32_MSFT -> "XR_TYPE_SCENE_MESH_INDICES_UINT32_MSFT";
            case XrStructureType.SCENE_MESH_VERTEX_BUFFER_MSFT -> "XR_TYPE_SCENE_MESH_VERTEX_BUFFER_MSFT";
            case XrStructureType.SCENE_OBJECTS_MSFT -> "XR_TYPE_SCENE_OBJECTS_MSFT";
            case XrStructureType.SCENE_OBJECT_TYPES_FILTER_INFO_MSFT -> "XR_TYPE_SCENE_OBJECT_TYPES_FILTER_INFO_MSFT";
            case XrStructureType.SCENE_OBSERVER_CREATE_INFO_MSFT -> "XR_TYPE_SCENE_OBSERVER_CREATE_INFO_MSFT";
            case XrStructureType.SCENE_PLANES_MSFT -> "XR_TYPE_SCENE_PLANES_MSFT";
            case XrStructureType.SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT -> "XR_TYPE_SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT";
            case XrStructureType.SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT -> "XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT";
            case XrStructureType.SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT -> "XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT";
            case XrStructureType.SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT -> "XR_TYPE_SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT";
            case XrStructureType.SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT -> "XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT";
            case XrStructureType.SECONDARY_VIEW_CONFIGURATION_STATE_MSFT -> "XR_TYPE_SECONDARY_VIEW_CONFIGURATION_STATE_MSFT";
            case XrStructureType.SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT -> "XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT";
            case XrStructureType.SEMANTIC_LABELS_FB -> "XR_TYPE_SEMANTIC_LABELS_FB";
            case XrStructureType.SEMANTIC_LABELS_SUPPORT_INFO_FB -> "XR_TYPE_SEMANTIC_LABELS_SUPPORT_INFO_FB";
            case XrStructureType.SENSE_DATA_FILTER_PLANE_ORIENTATION_BD -> "XR_TYPE_SENSE_DATA_FILTER_PLANE_ORIENTATION_BD";
            case XrStructureType.SENSE_DATA_FILTER_SEMANTIC_BD -> "XR_TYPE_SENSE_DATA_FILTER_SEMANTIC_BD";
            case XrStructureType.SENSE_DATA_FILTER_UUID_BD -> "XR_TYPE_SENSE_DATA_FILTER_UUID_BD";
            case XrStructureType.SENSE_DATA_PROVIDER_CREATE_INFO_BD -> "XR_TYPE_SENSE_DATA_PROVIDER_CREATE_INFO_BD";
            case XrStructureType.SENSE_DATA_PROVIDER_CREATE_INFO_SPATIAL_MESH_BD -> "XR_TYPE_SENSE_DATA_PROVIDER_CREATE_INFO_SPATIAL_MESH_BD";
            case XrStructureType.SENSE_DATA_PROVIDER_START_INFO_BD -> "XR_TYPE_SENSE_DATA_PROVIDER_START_INFO_BD";
            case XrStructureType.SENSE_DATA_QUERY_COMPLETION_BD -> "XR_TYPE_SENSE_DATA_QUERY_COMPLETION_BD";
            case XrStructureType.SENSE_DATA_QUERY_INFO_BD -> "XR_TYPE_SENSE_DATA_QUERY_INFO_BD";
            case XrStructureType.SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT -> "XR_TYPE_SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT";
            case XrStructureType.SESSION_ACTION_SETS_ATTACH_INFO -> "XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO";
            case XrStructureType.SESSION_BEGIN_INFO -> "XR_TYPE_SESSION_BEGIN_INFO";
            case XrStructureType.SESSION_CREATE_INFO -> "XR_TYPE_SESSION_CREATE_INFO";
            case XrStructureType.SESSION_CREATE_INFO_OVERLAY_EXTX -> "XR_TYPE_SESSION_CREATE_INFO_OVERLAY_EXTX";
            case XrStructureType.SHARED_SPATIAL_ANCHOR_DOWNLOAD_INFO_BD -> "XR_TYPE_SHARED_SPATIAL_ANCHOR_DOWNLOAD_INFO_BD";
            case XrStructureType.SHARE_SPACES_INFO_META -> "XR_TYPE_SHARE_SPACES_INFO_META";
            case XrStructureType.SHARE_SPACES_RECIPIENT_GROUPS_META -> "XR_TYPE_SHARE_SPACES_RECIPIENT_GROUPS_META";
            case XrStructureType.SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_PAUSE_INFO_META -> "XR_TYPE_SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_PAUSE_INFO_META";
            case XrStructureType.SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_RESUME_INFO_META -> "XR_TYPE_SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_RESUME_INFO_META";
            case XrStructureType.SPACES_LOCATE_INFO -> "XR_TYPE_SPACES_LOCATE_INFO";
            case XrStructureType.SPACE_COMPONENT_FILTER_INFO_FB -> "XR_TYPE_SPACE_COMPONENT_FILTER_INFO_FB";
            case XrStructureType.SPACE_COMPONENT_STATUS_FB -> "XR_TYPE_SPACE_COMPONENT_STATUS_FB";
            case XrStructureType.SPACE_COMPONENT_STATUS_SET_INFO_FB -> "XR_TYPE_SPACE_COMPONENT_STATUS_SET_INFO_FB";
            case XrStructureType.SPACE_CONTAINER_FB -> "XR_TYPE_SPACE_CONTAINER_FB";
            case XrStructureType.SPACE_ERASE_INFO_FB -> "XR_TYPE_SPACE_ERASE_INFO_FB";
            case XrStructureType.SPACE_GROUP_UUID_FILTER_INFO_META -> "XR_TYPE_SPACE_GROUP_UUID_FILTER_INFO_META";
            case XrStructureType.SPACE_LIST_SAVE_INFO_FB -> "XR_TYPE_SPACE_LIST_SAVE_INFO_FB";
            case XrStructureType.SPACE_LOCATION -> "XR_TYPE_SPACE_LOCATION";
            case XrStructureType.SPACE_LOCATIONS -> "XR_TYPE_SPACE_LOCATIONS";
            case XrStructureType.SPACE_QUERY_INFO_FB -> "XR_TYPE_SPACE_QUERY_INFO_FB";
            case XrStructureType.SPACE_QUERY_RESULTS_FB -> "XR_TYPE_SPACE_QUERY_RESULTS_FB";
            case XrStructureType.SPACE_SAVE_INFO_FB -> "XR_TYPE_SPACE_SAVE_INFO_FB";
            case XrStructureType.SPACE_SHARE_INFO_FB -> "XR_TYPE_SPACE_SHARE_INFO_FB";
            case XrStructureType.SPACE_STORAGE_LOCATION_FILTER_INFO_FB -> "XR_TYPE_SPACE_STORAGE_LOCATION_FILTER_INFO_FB";
            case XrStructureType.SPACE_TRIANGLE_MESH_GET_INFO_META -> "XR_TYPE_SPACE_TRIANGLE_MESH_GET_INFO_META";
            case XrStructureType.SPACE_TRIANGLE_MESH_META -> "XR_TYPE_SPACE_TRIANGLE_MESH_META";
            case XrStructureType.SPACE_USER_CREATE_INFO_FB -> "XR_TYPE_SPACE_USER_CREATE_INFO_FB";
            case XrStructureType.SPACE_UUID_FILTER_INFO_FB -> "XR_TYPE_SPACE_UUID_FILTER_INFO_FB";
            case XrStructureType.SPACE_VELOCITIES -> "XR_TYPE_SPACE_VELOCITIES";
            case XrStructureType.SPACE_VELOCITY -> "XR_TYPE_SPACE_VELOCITY";
            case XrStructureType.SPATIAL_ANCHORS_CREATE_INFO_FROM_POSE_ML -> "XR_TYPE_SPATIAL_ANCHORS_CREATE_INFO_FROM_POSE_ML";
            case XrStructureType.SPATIAL_ANCHORS_CREATE_INFO_FROM_UUIDS_ML -> "XR_TYPE_SPATIAL_ANCHORS_CREATE_INFO_FROM_UUIDS_ML";
            case XrStructureType.SPATIAL_ANCHORS_CREATE_STORAGE_INFO_ML -> "XR_TYPE_SPATIAL_ANCHORS_CREATE_STORAGE_INFO_ML";
            case XrStructureType.SPATIAL_ANCHORS_DELETE_COMPLETION_DETAILS_ML -> "XR_TYPE_SPATIAL_ANCHORS_DELETE_COMPLETION_DETAILS_ML";
            case XrStructureType.SPATIAL_ANCHORS_DELETE_COMPLETION_ML -> "XR_TYPE_SPATIAL_ANCHORS_DELETE_COMPLETION_ML";
            case XrStructureType.SPATIAL_ANCHORS_DELETE_INFO_ML -> "XR_TYPE_SPATIAL_ANCHORS_DELETE_INFO_ML";
            case XrStructureType.SPATIAL_ANCHORS_PUBLISH_COMPLETION_DETAILS_ML -> "XR_TYPE_SPATIAL_ANCHORS_PUBLISH_COMPLETION_DETAILS_ML";
            case XrStructureType.SPATIAL_ANCHORS_PUBLISH_COMPLETION_ML -> "XR_TYPE_SPATIAL_ANCHORS_PUBLISH_COMPLETION_ML";
            case XrStructureType.SPATIAL_ANCHORS_PUBLISH_INFO_ML -> "XR_TYPE_SPATIAL_ANCHORS_PUBLISH_INFO_ML";
            case XrStructureType.SPATIAL_ANCHORS_QUERY_COMPLETION_ML -> "XR_TYPE_SPATIAL_ANCHORS_QUERY_COMPLETION_ML";
            case XrStructureType.SPATIAL_ANCHORS_QUERY_INFO_RADIUS_ML -> "XR_TYPE_SPATIAL_ANCHORS_QUERY_INFO_RADIUS_ML";
            case XrStructureType.SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_DETAILS_ML -> "XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_DETAILS_ML";
            case XrStructureType.SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_ML -> "XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_ML";
            case XrStructureType.SPATIAL_ANCHORS_UPDATE_EXPIRATION_INFO_ML -> "XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_INFO_ML";
            case XrStructureType.SPATIAL_ANCHOR_CREATE_COMPLETION_BD -> "XR_TYPE_SPATIAL_ANCHOR_CREATE_COMPLETION_BD";
            case XrStructureType.SPATIAL_ANCHOR_CREATE_INFO_BD -> "XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_BD";
            case XrStructureType.SPATIAL_ANCHOR_CREATE_INFO_EXT -> "XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_EXT";
            case XrStructureType.SPATIAL_ANCHOR_CREATE_INFO_FB -> "XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_FB";
            case XrStructureType.SPATIAL_ANCHOR_CREATE_INFO_HTC -> "XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_HTC";
            case XrStructureType.SPATIAL_ANCHOR_CREATE_INFO_MSFT -> "XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT";
            case XrStructureType.SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT -> "XR_TYPE_SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT";
            case XrStructureType.SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT -> "XR_TYPE_SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT";
            case XrStructureType.SPATIAL_ANCHOR_PERSIST_INFO_BD -> "XR_TYPE_SPATIAL_ANCHOR_PERSIST_INFO_BD";
            case XrStructureType.SPATIAL_ANCHOR_SHARE_INFO_BD -> "XR_TYPE_SPATIAL_ANCHOR_SHARE_INFO_BD";
            case XrStructureType.SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT -> "XR_TYPE_SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT";
            case XrStructureType.SPATIAL_ANCHOR_STATE_ML -> "XR_TYPE_SPATIAL_ANCHOR_STATE_ML";
            case XrStructureType.SPATIAL_ANCHOR_UNPERSIST_INFO_BD -> "XR_TYPE_SPATIAL_ANCHOR_UNPERSIST_INFO_BD";
            case XrStructureType.SPATIAL_BUFFER_GET_INFO_EXT -> "XR_TYPE_SPATIAL_BUFFER_GET_INFO_EXT";
            case XrStructureType.SPATIAL_CAPABILITY_COMPONENT_TYPES_EXT -> "XR_TYPE_SPATIAL_CAPABILITY_COMPONENT_TYPES_EXT";
            case XrStructureType.SPATIAL_CAPABILITY_CONFIGURATION_ANCHOR_EXT -> "XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_ANCHOR_EXT";
            case XrStructureType.SPATIAL_CAPABILITY_CONFIGURATION_APRIL_TAG_EXT -> "XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_APRIL_TAG_EXT";
            case XrStructureType.SPATIAL_CAPABILITY_CONFIGURATION_ARUCO_MARKER_EXT -> "XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_ARUCO_MARKER_EXT";
            case XrStructureType.SPATIAL_CAPABILITY_CONFIGURATION_MICRO_QR_CODE_EXT -> "XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_MICRO_QR_CODE_EXT";
            case XrStructureType.SPATIAL_CAPABILITY_CONFIGURATION_PLANE_TRACKING_EXT -> "XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_PLANE_TRACKING_EXT";
            case XrStructureType.SPATIAL_CAPABILITY_CONFIGURATION_QR_CODE_EXT -> "XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_QR_CODE_EXT";
            case XrStructureType.SPATIAL_COMPONENT_ANCHOR_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_ANCHOR_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_BOUNDED_2D_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_BOUNDED_2D_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_BOUNDED_3D_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_BOUNDED_3D_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_DATA_QUERY_CONDITION_EXT -> "XR_TYPE_SPATIAL_COMPONENT_DATA_QUERY_CONDITION_EXT";
            case XrStructureType.SPATIAL_COMPONENT_DATA_QUERY_RESULT_EXT -> "XR_TYPE_SPATIAL_COMPONENT_DATA_QUERY_RESULT_EXT";
            case XrStructureType.SPATIAL_COMPONENT_MARKER_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_MARKER_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_MESH_2D_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_MESH_2D_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_MESH_3D_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_MESH_3D_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_PARENT_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_PARENT_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_PERSISTENCE_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_PERSISTENCE_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_PLANE_ALIGNMENT_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_PLANE_ALIGNMENT_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_PLANE_SEMANTIC_LABEL_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_PLANE_SEMANTIC_LABEL_LIST_EXT";
            case XrStructureType.SPATIAL_COMPONENT_POLYGON_2D_LIST_EXT -> "XR_TYPE_SPATIAL_COMPONENT_POLYGON_2D_LIST_EXT";
            case XrStructureType.SPATIAL_CONTEXT_CREATE_INFO_EXT -> "XR_TYPE_SPATIAL_CONTEXT_CREATE_INFO_EXT";
            case XrStructureType.SPATIAL_CONTEXT_PERSISTENCE_CONFIG_EXT -> "XR_TYPE_SPATIAL_CONTEXT_PERSISTENCE_CONFIG_EXT";
            case XrStructureType.SPATIAL_DISCOVERY_PERSISTENCE_UUID_FILTER_EXT -> "XR_TYPE_SPATIAL_DISCOVERY_PERSISTENCE_UUID_FILTER_EXT";
            case XrStructureType.SPATIAL_DISCOVERY_SNAPSHOT_CREATE_INFO_EXT -> "XR_TYPE_SPATIAL_DISCOVERY_SNAPSHOT_CREATE_INFO_EXT";
            case XrStructureType.SPATIAL_ENTITY_ANCHOR_CREATE_INFO_BD -> "XR_TYPE_SPATIAL_ENTITY_ANCHOR_CREATE_INFO_BD";
            case XrStructureType.SPATIAL_ENTITY_COMPONENT_DATA_BOUNDING_BOX_2D_BD -> "XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_BOUNDING_BOX_2D_BD";
            case XrStructureType.SPATIAL_ENTITY_COMPONENT_DATA_BOUNDING_BOX_3D_BD -> "XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_BOUNDING_BOX_3D_BD";
            case XrStructureType.SPATIAL_ENTITY_COMPONENT_DATA_LOCATION_BD -> "XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_LOCATION_BD";
            case XrStructureType.SPATIAL_ENTITY_COMPONENT_DATA_PLANE_ORIENTATION_BD -> "XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_PLANE_ORIENTATION_BD";
            case XrStructureType.SPATIAL_ENTITY_COMPONENT_DATA_POLYGON_BD -> "XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_POLYGON_BD";
            case XrStructureType.SPATIAL_ENTITY_COMPONENT_DATA_SEMANTIC_BD -> "XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_SEMANTIC_BD";
            case XrStructureType.SPATIAL_ENTITY_COMPONENT_DATA_TRIANGLE_MESH_BD -> "XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_TRIANGLE_MESH_BD";
            case XrStructureType.SPATIAL_ENTITY_COMPONENT_GET_INFO_BD -> "XR_TYPE_SPATIAL_ENTITY_COMPONENT_GET_INFO_BD";
            case XrStructureType.SPATIAL_ENTITY_FROM_ID_CREATE_INFO_EXT -> "XR_TYPE_SPATIAL_ENTITY_FROM_ID_CREATE_INFO_EXT";
            case XrStructureType.SPATIAL_ENTITY_LOCATION_GET_INFO_BD -> "XR_TYPE_SPATIAL_ENTITY_LOCATION_GET_INFO_BD";
            case XrStructureType.SPATIAL_ENTITY_PERSIST_INFO_EXT -> "XR_TYPE_SPATIAL_ENTITY_PERSIST_INFO_EXT";
            case XrStructureType.SPATIAL_ENTITY_STATE_BD -> "XR_TYPE_SPATIAL_ENTITY_STATE_BD";
            case XrStructureType.SPATIAL_ENTITY_UNPERSIST_INFO_EXT -> "XR_TYPE_SPATIAL_ENTITY_UNPERSIST_INFO_EXT";
            case XrStructureType.SPATIAL_FILTER_TRACKING_STATE_EXT -> "XR_TYPE_SPATIAL_FILTER_TRACKING_STATE_EXT";
            case XrStructureType.SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT -> "XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT";
            case XrStructureType.SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT -> "XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT";
            case XrStructureType.SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT -> "XR_TYPE_SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT";
            case XrStructureType.SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT -> "XR_TYPE_SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT";
            case XrStructureType.SPATIAL_MARKER_SIZE_EXT -> "XR_TYPE_SPATIAL_MARKER_SIZE_EXT";
            case XrStructureType.SPATIAL_MARKER_STATIC_OPTIMIZATION_EXT -> "XR_TYPE_SPATIAL_MARKER_STATIC_OPTIMIZATION_EXT";
            case XrStructureType.SPATIAL_PERSISTENCE_CONTEXT_CREATE_INFO_EXT -> "XR_TYPE_SPATIAL_PERSISTENCE_CONTEXT_CREATE_INFO_EXT";
            case XrStructureType.SPATIAL_UPDATE_SNAPSHOT_CREATE_INFO_EXT -> "XR_TYPE_SPATIAL_UPDATE_SNAPSHOT_CREATE_INFO_EXT";
            case XrStructureType.SWAPCHAIN_CREATE_INFO -> "XR_TYPE_SWAPCHAIN_CREATE_INFO";
            case XrStructureType.SWAPCHAIN_CREATE_INFO_FOVEATION_FB -> "XR_TYPE_SWAPCHAIN_CREATE_INFO_FOVEATION_FB";
            case XrStructureType.SWAPCHAIN_IMAGE_ACQUIRE_INFO -> "XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO";
            case XrStructureType.SWAPCHAIN_IMAGE_D3D11_KHR -> "XR_TYPE_SWAPCHAIN_IMAGE_D3D11_KHR";
            case XrStructureType.SWAPCHAIN_IMAGE_D3D12_KHR -> "XR_TYPE_SWAPCHAIN_IMAGE_D3D12_KHR";
            case XrStructureType.SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB -> "XR_TYPE_SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB";
            case XrStructureType.SWAPCHAIN_IMAGE_METAL_KHR -> "XR_TYPE_SWAPCHAIN_IMAGE_METAL_KHR";
            case XrStructureType.SWAPCHAIN_IMAGE_OPENGL_ES_KHR -> "XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR";
            case XrStructureType.SWAPCHAIN_IMAGE_OPENGL_KHR -> "XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_KHR";
            case XrStructureType.SWAPCHAIN_IMAGE_RELEASE_INFO -> "XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO";
            case XrStructureType.SWAPCHAIN_IMAGE_VULKAN_KHR -> "XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR";
            case XrStructureType.SWAPCHAIN_IMAGE_WAIT_INFO -> "XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO";
            case XrStructureType.SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB -> "XR_TYPE_SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB";
            case XrStructureType.SWAPCHAIN_STATE_FOVEATION_FB -> "XR_TYPE_SWAPCHAIN_STATE_FOVEATION_FB";
            case XrStructureType.SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB -> "XR_TYPE_SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB";
            case XrStructureType.SWAPCHAIN_STATE_SAMPLER_VULKAN_FB -> "XR_TYPE_SWAPCHAIN_STATE_SAMPLER_VULKAN_FB";
            case XrStructureType.SYSTEM_ANCHOR_PROPERTIES_HTC -> "XR_TYPE_SYSTEM_ANCHOR_PROPERTIES_HTC";
            case XrStructureType.SYSTEM_BODY_TRACKING_PROPERTIES_BD -> "XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_BD";
            case XrStructureType.SYSTEM_BODY_TRACKING_PROPERTIES_FB -> "XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_FB";
            case XrStructureType.SYSTEM_BODY_TRACKING_PROPERTIES_HTC -> "XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_HTC";
            case XrStructureType.SYSTEM_COLOCATION_DISCOVERY_PROPERTIES_META -> "XR_TYPE_SYSTEM_COLOCATION_DISCOVERY_PROPERTIES_META";
            case XrStructureType.SYSTEM_COLOR_SPACE_PROPERTIES_FB -> "XR_TYPE_SYSTEM_COLOR_SPACE_PROPERTIES_FB";
            case XrStructureType.SYSTEM_ENVIRONMENT_DEPTH_PROPERTIES_META -> "XR_TYPE_SYSTEM_ENVIRONMENT_DEPTH_PROPERTIES_META";
            case XrStructureType.SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT -> "XR_TYPE_SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT";
            case XrStructureType.SYSTEM_EYE_TRACKING_PROPERTIES_FB -> "XR_TYPE_SYSTEM_EYE_TRACKING_PROPERTIES_FB";
            case XrStructureType.SYSTEM_FACE_TRACKING_PROPERTIES2_FB -> "XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES2_FB";
            case XrStructureType.SYSTEM_FACE_TRACKING_PROPERTIES_FB -> "XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES_FB";
            case XrStructureType.SYSTEM_FACIAL_EXPRESSION_PROPERTIES_ML -> "XR_TYPE_SYSTEM_FACIAL_EXPRESSION_PROPERTIES_ML";
            case XrStructureType.SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC -> "XR_TYPE_SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC";
            case XrStructureType.SYSTEM_FORCE_FEEDBACK_CURL_PROPERTIES_MNDX -> "XR_TYPE_SYSTEM_FORCE_FEEDBACK_CURL_PROPERTIES_MNDX";
            case XrStructureType.SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO -> "XR_TYPE_SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO";
            case XrStructureType.SYSTEM_FOVEATION_EYE_TRACKED_PROPERTIES_META -> "XR_TYPE_SYSTEM_FOVEATION_EYE_TRACKED_PROPERTIES_META";
            case XrStructureType.SYSTEM_GET_INFO -> "XR_TYPE_SYSTEM_GET_INFO";
            case XrStructureType.SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT -> "XR_TYPE_SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT";
            case XrStructureType.SYSTEM_HAND_TRACKING_PROPERTIES_EXT -> "XR_TYPE_SYSTEM_HAND_TRACKING_PROPERTIES_EXT";
            case XrStructureType.SYSTEM_HEADSET_ID_PROPERTIES_META -> "XR_TYPE_SYSTEM_HEADSET_ID_PROPERTIES_META";
            case XrStructureType.SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB -> "XR_TYPE_SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB";
            case XrStructureType.SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO -> "XR_TYPE_SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO";
            case XrStructureType.SYSTEM_MARKER_UNDERSTANDING_PROPERTIES_ML -> "XR_TYPE_SYSTEM_MARKER_UNDERSTANDING_PROPERTIES_ML";
            case XrStructureType.SYSTEM_NOTIFICATIONS_SET_INFO_ML -> "XR_TYPE_SYSTEM_NOTIFICATIONS_SET_INFO_ML";
            case XrStructureType.SYSTEM_PASSTHROUGH_COLOR_LUT_PROPERTIES_META -> "XR_TYPE_SYSTEM_PASSTHROUGH_COLOR_LUT_PROPERTIES_META";
            case XrStructureType.SYSTEM_PASSTHROUGH_PROPERTIES2_FB -> "XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES2_FB";
            case XrStructureType.SYSTEM_PASSTHROUGH_PROPERTIES_FB -> "XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES_FB";
            case XrStructureType.SYSTEM_PLANE_DETECTION_PROPERTIES_EXT -> "XR_TYPE_SYSTEM_PLANE_DETECTION_PROPERTIES_EXT";
            case XrStructureType.SYSTEM_PROPERTIES -> "XR_TYPE_SYSTEM_PROPERTIES";
            case XrStructureType.SYSTEM_PROPERTIES_BODY_TRACKING_FULL_BODY_META -> "XR_TYPE_SYSTEM_PROPERTIES_BODY_TRACKING_FULL_BODY_META";
            case XrStructureType.SYSTEM_RENDER_MODEL_PROPERTIES_FB -> "XR_TYPE_SYSTEM_RENDER_MODEL_PROPERTIES_FB";
            case XrStructureType.SYSTEM_SIMULTANEOUS_HANDS_AND_CONTROLLERS_PROPERTIES_META -> "XR_TYPE_SYSTEM_SIMULTANEOUS_HANDS_AND_CONTROLLERS_PROPERTIES_META";
            case XrStructureType.SYSTEM_SPACE_WARP_PROPERTIES_FB -> "XR_TYPE_SYSTEM_SPACE_WARP_PROPERTIES_FB";
            case XrStructureType.SYSTEM_SPATIAL_ANCHOR_PROPERTIES_BD -> "XR_TYPE_SYSTEM_SPATIAL_ANCHOR_PROPERTIES_BD";
            case XrStructureType.SYSTEM_SPATIAL_ANCHOR_SHARING_PROPERTIES_BD -> "XR_TYPE_SYSTEM_SPATIAL_ANCHOR_SHARING_PROPERTIES_BD";
            case XrStructureType.SYSTEM_SPATIAL_ENTITY_GROUP_SHARING_PROPERTIES_META -> "XR_TYPE_SYSTEM_SPATIAL_ENTITY_GROUP_SHARING_PROPERTIES_META";
            case XrStructureType.SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB -> "XR_TYPE_SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB";
            case XrStructureType.SYSTEM_SPATIAL_ENTITY_SHARING_PROPERTIES_META -> "XR_TYPE_SYSTEM_SPATIAL_ENTITY_SHARING_PROPERTIES_META";
            case XrStructureType.SYSTEM_SPATIAL_MESH_PROPERTIES_BD -> "XR_TYPE_SYSTEM_SPATIAL_MESH_PROPERTIES_BD";
            case XrStructureType.SYSTEM_SPATIAL_PLANE_PROPERTIES_BD -> "XR_TYPE_SYSTEM_SPATIAL_PLANE_PROPERTIES_BD";
            case XrStructureType.SYSTEM_SPATIAL_SCENE_PROPERTIES_BD -> "XR_TYPE_SYSTEM_SPATIAL_SCENE_PROPERTIES_BD";
            case XrStructureType.SYSTEM_SPATIAL_SENSING_PROPERTIES_BD -> "XR_TYPE_SYSTEM_SPATIAL_SENSING_PROPERTIES_BD";
            case XrStructureType.SYSTEM_USER_PRESENCE_PROPERTIES_EXT -> "XR_TYPE_SYSTEM_USER_PRESENCE_PROPERTIES_EXT";
            case XrStructureType.SYSTEM_VIRTUAL_KEYBOARD_PROPERTIES_META -> "XR_TYPE_SYSTEM_VIRTUAL_KEYBOARD_PROPERTIES_META";
            case XrStructureType.TRIANGLE_MESH_CREATE_INFO_FB -> "XR_TYPE_TRIANGLE_MESH_CREATE_INFO_FB";
            case XrStructureType.UNKNOWN -> "XR_TYPE_UNKNOWN";
            case XrStructureType.UNPERSIST_SPATIAL_ENTITY_COMPLETION_EXT -> "XR_TYPE_UNPERSIST_SPATIAL_ENTITY_COMPLETION_EXT";
            case XrStructureType.USER_CALIBRATION_ENABLE_EVENTS_INFO_ML -> "XR_TYPE_USER_CALIBRATION_ENABLE_EVENTS_INFO_ML";
            case XrStructureType.VIEW -> "XR_TYPE_VIEW";
            case XrStructureType.VIEW_CONFIGURATION_DEPTH_RANGE_EXT -> "XR_TYPE_VIEW_CONFIGURATION_DEPTH_RANGE_EXT";
            case XrStructureType.VIEW_CONFIGURATION_PROPERTIES -> "XR_TYPE_VIEW_CONFIGURATION_PROPERTIES";
            case XrStructureType.VIEW_CONFIGURATION_VIEW -> "XR_TYPE_VIEW_CONFIGURATION_VIEW";
            case XrStructureType.VIEW_CONFIGURATION_VIEW_FOV_EPIC -> "XR_TYPE_VIEW_CONFIGURATION_VIEW_FOV_EPIC";
            case XrStructureType.VIEW_LOCATE_FOVEATED_RENDERING_VARJO -> "XR_TYPE_VIEW_LOCATE_FOVEATED_RENDERING_VARJO";
            case XrStructureType.VIEW_LOCATE_INFO -> "XR_TYPE_VIEW_LOCATE_INFO";
            case XrStructureType.VIEW_STATE -> "XR_TYPE_VIEW_STATE";
            case XrStructureType.VIRTUAL_KEYBOARD_ANIMATION_STATE_META -> "XR_TYPE_VIRTUAL_KEYBOARD_ANIMATION_STATE_META";
            case XrStructureType.VIRTUAL_KEYBOARD_CREATE_INFO_META -> "XR_TYPE_VIRTUAL_KEYBOARD_CREATE_INFO_META";
            case XrStructureType.VIRTUAL_KEYBOARD_INPUT_INFO_META -> "XR_TYPE_VIRTUAL_KEYBOARD_INPUT_INFO_META";
            case XrStructureType.VIRTUAL_KEYBOARD_LOCATION_INFO_META -> "XR_TYPE_VIRTUAL_KEYBOARD_LOCATION_INFO_META";
            case XrStructureType.VIRTUAL_KEYBOARD_MODEL_ANIMATION_STATES_META -> "XR_TYPE_VIRTUAL_KEYBOARD_MODEL_ANIMATION_STATES_META";
            case XrStructureType.VIRTUAL_KEYBOARD_MODEL_VISIBILITY_SET_INFO_META -> "XR_TYPE_VIRTUAL_KEYBOARD_MODEL_VISIBILITY_SET_INFO_META";
            case XrStructureType.VIRTUAL_KEYBOARD_SPACE_CREATE_INFO_META -> "XR_TYPE_VIRTUAL_KEYBOARD_SPACE_CREATE_INFO_META";
            case XrStructureType.VIRTUAL_KEYBOARD_TEXTURE_DATA_META -> "XR_TYPE_VIRTUAL_KEYBOARD_TEXTURE_DATA_META";
            case XrStructureType.VIRTUAL_KEYBOARD_TEXT_CONTEXT_CHANGE_INFO_META -> "XR_TYPE_VIRTUAL_KEYBOARD_TEXT_CONTEXT_CHANGE_INFO_META";
            case XrStructureType.VISIBILITY_MASK_KHR -> "XR_TYPE_VISIBILITY_MASK_KHR";
            case XrStructureType.VISUAL_MESH_COMPUTE_LOD_INFO_MSFT -> "XR_TYPE_VISUAL_MESH_COMPUTE_LOD_INFO_MSFT";
            case XrStructureType.VIVE_TRACKER_PATHS_HTCX -> "XR_TYPE_VIVE_TRACKER_PATHS_HTCX";
            case XrStructureType.VULKAN_DEVICE_CREATE_INFO_KHR -> "XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR";
            case XrStructureType.VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR -> "XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR";
            case XrStructureType.VULKAN_INSTANCE_CREATE_INFO_KHR -> "XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR";
            case XrStructureType.VULKAN_SWAPCHAIN_CREATE_INFO_META -> "XR_TYPE_VULKAN_SWAPCHAIN_CREATE_INFO_META";
            case XrStructureType.VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR -> "XR_TYPE_VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR";
            case XrStructureType.WORLD_MESH_BLOCK_ML -> "XR_TYPE_WORLD_MESH_BLOCK_ML";
            case XrStructureType.WORLD_MESH_BLOCK_REQUEST_ML -> "XR_TYPE_WORLD_MESH_BLOCK_REQUEST_ML";
            case XrStructureType.WORLD_MESH_BLOCK_STATE_ML -> "XR_TYPE_WORLD_MESH_BLOCK_STATE_ML";
            case XrStructureType.WORLD_MESH_BUFFER_ML -> "XR_TYPE_WORLD_MESH_BUFFER_ML";
            case XrStructureType.WORLD_MESH_BUFFER_RECOMMENDED_SIZE_INFO_ML -> "XR_TYPE_WORLD_MESH_BUFFER_RECOMMENDED_SIZE_INFO_ML";
            case XrStructureType.WORLD_MESH_BUFFER_SIZE_ML -> "XR_TYPE_WORLD_MESH_BUFFER_SIZE_ML";
            case XrStructureType.WORLD_MESH_DETECTOR_CREATE_INFO_ML -> "XR_TYPE_WORLD_MESH_DETECTOR_CREATE_INFO_ML";
            case XrStructureType.WORLD_MESH_GET_INFO_ML -> "XR_TYPE_WORLD_MESH_GET_INFO_ML";
            case XrStructureType.WORLD_MESH_REQUEST_COMPLETION_INFO_ML -> "XR_TYPE_WORLD_MESH_REQUEST_COMPLETION_INFO_ML";
            case XrStructureType.WORLD_MESH_REQUEST_COMPLETION_ML -> "XR_TYPE_WORLD_MESH_REQUEST_COMPLETION_ML";
            case XrStructureType.WORLD_MESH_STATE_REQUEST_COMPLETION_ML -> "XR_TYPE_WORLD_MESH_STATE_REQUEST_COMPLETION_ML";
            case XrStructureType.WORLD_MESH_STATE_REQUEST_INFO_ML -> "XR_TYPE_WORLD_MESH_STATE_REQUEST_INFO_ML";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private XrStructureType() {}
}
