[book]
authors = ["Chuigda Whitegive", "CousinZe", "Alexander Overvoorde"]
language = "en"
multilingual = false
src = "src"
title = "Vulkan Tutorial (Java)"

[output.html]
git-repository-url = "https://github.com/chuigda/vulkan4j"
