package club.doki7.webgpu.enumtype;

import club.doki7.ffm.annotation.*;

public final class TextureFormat {
    public static final int UNDEFINED = 0x0;
    public static final int R8_UNORM = 0x1;
    public static final int R8_SNORM = 0x2;
    public static final int R8_UINT = 0x3;
    public static final int R8_SINT = 0x4;
    public static final int R16_UINT = 0x5;
    public static final int R16_SINT = 0x6;
    public static final int R16_FLOAT = 0x7;
    public static final int RG8_UNORM = 0x8;
    public static final int RG8_SNORM = 0x9;
    public static final int RG8_UINT = 0xa;
    public static final int RG8_SINT = 0xb;
    public static final int R32_FLOAT = 0xc;
    public static final int R32_UINT = 0xd;
    public static final int R32_SINT = 0xe;
    public static final int RG16_UINT = 0xf;
    public static final int RG16_SINT = 0x10;
    public static final int RG16_FLOAT = 0x11;
    public static final int RGBA8_UNORM = 0x12;
    public static final int RGBA8_UNORM_SRGB = 0x13;
    public static final int RGBA8_SNORM = 0x14;
    public static final int RGBA8_UINT = 0x15;
    public static final int RGBA8_SINT = 0x16;
    public static final int BGRA8_UNORM = 0x17;
    public static final int BGRA8_UNORM_SRGB = 0x18;
    public static final int RGB10_A2_UINT = 0x19;
    public static final int RGB10_A2_UNORM = 0x1a;
    public static final int RG11_B10_UFLOAT = 0x1b;
    public static final int RGB9_E5_UFLOAT = 0x1c;
    public static final int RG32_FLOAT = 0x1d;
    public static final int RG32_UINT = 0x1e;
    public static final int RG32_SINT = 0x1f;
    public static final int RGBA16_UINT = 0x20;
    public static final int RGBA16_SINT = 0x21;
    public static final int RGBA16_FLOAT = 0x22;
    public static final int RGBA32_FLOAT = 0x23;
    public static final int RGBA32_UINT = 0x24;
    public static final int RGBA32_SINT = 0x25;
    public static final int STENCIL8 = 0x26;
    public static final int DEPTH16_UNORM = 0x27;
    public static final int DEPTH24_PLUS = 0x28;
    public static final int DEPTH24_PLUS_STENCIL8 = 0x29;
    public static final int DEPTH32_FLOAT = 0x2a;
    public static final int DEPTH32_FLOAT_STENCIL8 = 0x2b;
    public static final int BC1_RGBA_UNORM = 0x2c;
    public static final int BC1_RGBA_UNORM_SRGB = 0x2d;
    public static final int BC2_RGBA_UNORM = 0x2e;
    public static final int BC2_RGBA_UNORM_SRGB = 0x2f;
    public static final int BC3_RGBA_UNORM = 0x30;
    public static final int BC3_RGBA_UNORM_SRGB = 0x31;
    public static final int BC4_R_UNORM = 0x32;
    public static final int BC4_R_SNORM = 0x33;
    public static final int BC5_RG_UNORM = 0x34;
    public static final int BC5_RG_SNORM = 0x35;
    public static final int BC6H_RGB_UFLOAT = 0x36;
    public static final int BC6H_RGB_FLOAT = 0x37;
    public static final int BC7_RGBA_UNORM = 0x38;
    public static final int BC7_RGBA_UNORM_SRGB = 0x39;
    public static final int ETC2_RGB8_UNORM = 0x3a;
    public static final int ETC2_RGB8_UNORM_SRGB = 0x3b;
    public static final int ETC2_RGB8A1_UNORM = 0x3c;
    public static final int ETC2_RGB8A1_UNORM_SRGB = 0x3d;
    public static final int ETC2_RGBA8_UNORM = 0x3e;
    public static final int ETC2_RGBA8_UNORM_SRGB = 0x3f;
    public static final int EAC_R11_UNORM = 0x40;
    public static final int EAC_R11_SNORM = 0x41;
    public static final int EAC_RG11_UNORM = 0x42;
    public static final int EAC_RG11_SNORM = 0x43;
    public static final int ASTC_4X4_UNORM = 0x44;
    public static final int ASTC_4X4_UNORM_SRGB = 0x45;
    public static final int ASTC_5X4_UNORM = 0x46;
    public static final int ASTC_5X4_UNORM_SRGB = 0x47;
    public static final int ASTC_5X5_UNORM = 0x48;
    public static final int ASTC_5X5_UNORM_SRGB = 0x49;
    public static final int ASTC_6X5_UNORM = 0x4a;
    public static final int ASTC_6X5_UNORM_SRGB = 0x4b;
    public static final int ASTC_6X6_UNORM = 0x4c;
    public static final int ASTC_6X6_UNORM_SRGB = 0x4d;
    public static final int ASTC_8X5_UNORM = 0x4e;
    public static final int ASTC_8X5_UNORM_SRGB = 0x4f;
    public static final int ASTC_8X6_UNORM = 0x50;
    public static final int ASTC_8X6_UNORM_SRGB = 0x51;
    public static final int ASTC_8X8_UNORM = 0x52;
    public static final int ASTC_8X8_UNORM_SRGB = 0x53;
    public static final int ASTC_10X5_UNORM = 0x54;
    public static final int ASTC_10X5_UNORM_SRGB = 0x55;
    public static final int ASTC_10X6_UNORM = 0x56;
    public static final int ASTC_10X6_UNORM_SRGB = 0x57;
    public static final int ASTC_10X8_UNORM = 0x58;
    public static final int ASTC_10X8_UNORM_SRGB = 0x59;
    public static final int ASTC_10X10_UNORM = 0x5a;
    public static final int ASTC_10X10_UNORM_SRGB = 0x5b;
    public static final int ASTC_12X10_UNORM = 0x5c;
    public static final int ASTC_12X10_UNORM_SRGB = 0x5d;
    public static final int ASTC_12X12_UNORM = 0x5e;
    public static final int ASTC_12X12_UNORM_SRGB = 0x5f;
    public static final int FORCE32 = 0x7fffffff;

    public static String explain(@EnumType(TextureFormat.class) int value) {
        return switch (value) {
            case TextureFormat.ASTC_10X10_UNORM -> "ASTC_10X10_UNORM";
            case TextureFormat.ASTC_10X10_UNORM_SRGB -> "ASTC_10X10_UNORM_SRGB";
            case TextureFormat.ASTC_10X5_UNORM -> "ASTC_10X5_UNORM";
            case TextureFormat.ASTC_10X5_UNORM_SRGB -> "ASTC_10X5_UNORM_SRGB";
            case TextureFormat.ASTC_10X6_UNORM -> "ASTC_10X6_UNORM";
            case TextureFormat.ASTC_10X6_UNORM_SRGB -> "ASTC_10X6_UNORM_SRGB";
            case TextureFormat.ASTC_10X8_UNORM -> "ASTC_10X8_UNORM";
            case TextureFormat.ASTC_10X8_UNORM_SRGB -> "ASTC_10X8_UNORM_SRGB";
            case TextureFormat.ASTC_12X10_UNORM -> "ASTC_12X10_UNORM";
            case TextureFormat.ASTC_12X10_UNORM_SRGB -> "ASTC_12X10_UNORM_SRGB";
            case TextureFormat.ASTC_12X12_UNORM -> "ASTC_12X12_UNORM";
            case TextureFormat.ASTC_12X12_UNORM_SRGB -> "ASTC_12X12_UNORM_SRGB";
            case TextureFormat.ASTC_4X4_UNORM -> "ASTC_4X4_UNORM";
            case TextureFormat.ASTC_4X4_UNORM_SRGB -> "ASTC_4X4_UNORM_SRGB";
            case TextureFormat.ASTC_5X4_UNORM -> "ASTC_5X4_UNORM";
            case TextureFormat.ASTC_5X4_UNORM_SRGB -> "ASTC_5X4_UNORM_SRGB";
            case TextureFormat.ASTC_5X5_UNORM -> "ASTC_5X5_UNORM";
            case TextureFormat.ASTC_5X5_UNORM_SRGB -> "ASTC_5X5_UNORM_SRGB";
            case TextureFormat.ASTC_6X5_UNORM -> "ASTC_6X5_UNORM";
            case TextureFormat.ASTC_6X5_UNORM_SRGB -> "ASTC_6X5_UNORM_SRGB";
            case TextureFormat.ASTC_6X6_UNORM -> "ASTC_6X6_UNORM";
            case TextureFormat.ASTC_6X6_UNORM_SRGB -> "ASTC_6X6_UNORM_SRGB";
            case TextureFormat.ASTC_8X5_UNORM -> "ASTC_8X5_UNORM";
            case TextureFormat.ASTC_8X5_UNORM_SRGB -> "ASTC_8X5_UNORM_SRGB";
            case TextureFormat.ASTC_8X6_UNORM -> "ASTC_8X6_UNORM";
            case TextureFormat.ASTC_8X6_UNORM_SRGB -> "ASTC_8X6_UNORM_SRGB";
            case TextureFormat.ASTC_8X8_UNORM -> "ASTC_8X8_UNORM";
            case TextureFormat.ASTC_8X8_UNORM_SRGB -> "ASTC_8X8_UNORM_SRGB";
            case TextureFormat.BC1_RGBA_UNORM -> "BC1_RGBA_UNORM";
            case TextureFormat.BC1_RGBA_UNORM_SRGB -> "BC1_RGBA_UNORM_SRGB";
            case TextureFormat.BC2_RGBA_UNORM -> "BC2_RGBA_UNORM";
            case TextureFormat.BC2_RGBA_UNORM_SRGB -> "BC2_RGBA_UNORM_SRGB";
            case TextureFormat.BC3_RGBA_UNORM -> "BC3_RGBA_UNORM";
            case TextureFormat.BC3_RGBA_UNORM_SRGB -> "BC3_RGBA_UNORM_SRGB";
            case TextureFormat.BC4_R_SNORM -> "BC4_R_SNORM";
            case TextureFormat.BC4_R_UNORM -> "BC4_R_UNORM";
            case TextureFormat.BC5_RG_SNORM -> "BC5_RG_SNORM";
            case TextureFormat.BC5_RG_UNORM -> "BC5_RG_UNORM";
            case TextureFormat.BC6H_RGB_FLOAT -> "BC6H_RGB_FLOAT";
            case TextureFormat.BC6H_RGB_UFLOAT -> "BC6H_RGB_UFLOAT";
            case TextureFormat.BC7_RGBA_UNORM -> "BC7_RGBA_UNORM";
            case TextureFormat.BC7_RGBA_UNORM_SRGB -> "BC7_RGBA_UNORM_SRGB";
            case TextureFormat.BGRA8_UNORM -> "BGRA8_UNORM";
            case TextureFormat.BGRA8_UNORM_SRGB -> "BGRA8_UNORM_SRGB";
            case TextureFormat.DEPTH16_UNORM -> "DEPTH16_UNORM";
            case TextureFormat.DEPTH24_PLUS -> "DEPTH24_PLUS";
            case TextureFormat.DEPTH24_PLUS_STENCIL8 -> "DEPTH24_PLUS_STENCIL8";
            case TextureFormat.DEPTH32_FLOAT -> "DEPTH32_FLOAT";
            case TextureFormat.DEPTH32_FLOAT_STENCIL8 -> "DEPTH32_FLOAT_STENCIL8";
            case TextureFormat.EAC_R11_SNORM -> "EAC_R11_SNORM";
            case TextureFormat.EAC_R11_UNORM -> "EAC_R11_UNORM";
            case TextureFormat.EAC_RG11_SNORM -> "EAC_RG11_SNORM";
            case TextureFormat.EAC_RG11_UNORM -> "EAC_RG11_UNORM";
            case TextureFormat.ETC2_RGB8A1_UNORM -> "ETC2_RGB8A1_UNORM";
            case TextureFormat.ETC2_RGB8A1_UNORM_SRGB -> "ETC2_RGB8A1_UNORM_SRGB";
            case TextureFormat.ETC2_RGB8_UNORM -> "ETC2_RGB8_UNORM";
            case TextureFormat.ETC2_RGB8_UNORM_SRGB -> "ETC2_RGB8_UNORM_SRGB";
            case TextureFormat.ETC2_RGBA8_UNORM -> "ETC2_RGBA8_UNORM";
            case TextureFormat.ETC2_RGBA8_UNORM_SRGB -> "ETC2_RGBA8_UNORM_SRGB";
            case TextureFormat.FORCE32 -> "FORCE32";
            case TextureFormat.R16_FLOAT -> "R16_FLOAT";
            case TextureFormat.R16_SINT -> "R16_SINT";
            case TextureFormat.R16_UINT -> "R16_UINT";
            case TextureFormat.R32_FLOAT -> "R32_FLOAT";
            case TextureFormat.R32_SINT -> "R32_SINT";
            case TextureFormat.R32_UINT -> "R32_UINT";
            case TextureFormat.R8_SINT -> "R8_SINT";
            case TextureFormat.R8_SNORM -> "R8_SNORM";
            case TextureFormat.R8_UINT -> "R8_UINT";
            case TextureFormat.R8_UNORM -> "R8_UNORM";
            case TextureFormat.RG11_B10_UFLOAT -> "RG11_B10_UFLOAT";
            case TextureFormat.RG16_FLOAT -> "RG16_FLOAT";
            case TextureFormat.RG16_SINT -> "RG16_SINT";
            case TextureFormat.RG16_UINT -> "RG16_UINT";
            case TextureFormat.RG32_FLOAT -> "RG32_FLOAT";
            case TextureFormat.RG32_SINT -> "RG32_SINT";
            case TextureFormat.RG32_UINT -> "RG32_UINT";
            case TextureFormat.RG8_SINT -> "RG8_SINT";
            case TextureFormat.RG8_SNORM -> "RG8_SNORM";
            case TextureFormat.RG8_UINT -> "RG8_UINT";
            case TextureFormat.RG8_UNORM -> "RG8_UNORM";
            case TextureFormat.RGB10_A2_UINT -> "RGB10_A2_UINT";
            case TextureFormat.RGB10_A2_UNORM -> "RGB10_A2_UNORM";
            case TextureFormat.RGB9_E5_UFLOAT -> "RGB9_E5_UFLOAT";
            case TextureFormat.RGBA16_FLOAT -> "RGBA16_FLOAT";
            case TextureFormat.RGBA16_SINT -> "RGBA16_SINT";
            case TextureFormat.RGBA16_UINT -> "RGBA16_UINT";
            case TextureFormat.RGBA32_FLOAT -> "RGBA32_FLOAT";
            case TextureFormat.RGBA32_SINT -> "RGBA32_SINT";
            case TextureFormat.RGBA32_UINT -> "RGBA32_UINT";
            case TextureFormat.RGBA8_SINT -> "RGBA8_SINT";
            case TextureFormat.RGBA8_SNORM -> "RGBA8_SNORM";
            case TextureFormat.RGBA8_UINT -> "RGBA8_UINT";
            case TextureFormat.RGBA8_UNORM -> "RGBA8_UNORM";
            case TextureFormat.RGBA8_UNORM_SRGB -> "RGBA8_UNORM_SRGB";
            case TextureFormat.STENCIL8 -> "STENCIL8";
            case TextureFormat.UNDEFINED -> "UNDEFINED";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private TextureFormat() {}
}
