package club.doki7.webgpu.enumtype;

import club.doki7.ffm.annotation.*;

public final class TextureFormat {
    public static final int TEXTURE_FORMAT_UNDEFINED = 0x0;
    public static final int TEXTURE_FORMAT_R8_UNORM = 0x1;
    public static final int TEXTURE_FORMAT_R8_SNORM = 0x2;
    public static final int TEXTURE_FORMAT_R8_UINT = 0x3;
    public static final int TEXTURE_FORMAT_R8_SINT = 0x4;
    public static final int TEXTURE_FORMAT_R16_UINT = 0x5;
    public static final int TEXTURE_FORMAT_R16_SINT = 0x6;
    public static final int TEXTURE_FORMAT_R16_FLOAT = 0x7;
    public static final int TEXTURE_FORMAT_RG8_UNORM = 0x8;
    public static final int TEXTURE_FORMAT_RG8_SNORM = 0x9;
    public static final int TEXTURE_FORMAT_RG8_UINT = 0xa;
    public static final int TEXTURE_FORMAT_RG8_SINT = 0xb;
    public static final int TEXTURE_FORMAT_R32_FLOAT = 0xc;
    public static final int TEXTURE_FORMAT_R32_UINT = 0xd;
    public static final int TEXTURE_FORMAT_R32_SINT = 0xe;
    public static final int TEXTURE_FORMAT_RG16_UINT = 0xf;
    public static final int TEXTURE_FORMAT_RG16_SINT = 0x10;
    public static final int TEXTURE_FORMAT_RG16_FLOAT = 0x11;
    public static final int TEXTURE_FORMAT_RGBA8_UNORM = 0x12;
    public static final int TEXTURE_FORMAT_RGBA8_UNORM_SRGB = 0x13;
    public static final int TEXTURE_FORMAT_RGBA8_SNORM = 0x14;
    public static final int TEXTURE_FORMAT_RGBA8_UINT = 0x15;
    public static final int TEXTURE_FORMAT_RGBA8_SINT = 0x16;
    public static final int TEXTURE_FORMAT_BGRA8_UNORM = 0x17;
    public static final int TEXTURE_FORMAT_BGRA8_UNORM_SRGB = 0x18;
    public static final int TEXTURE_FORMAT_RGB10_A2_UINT = 0x19;
    public static final int TEXTURE_FORMAT_RGB10_A2_UNORM = 0x1a;
    public static final int TEXTURE_FORMAT_RG11_B10_UFLOAT = 0x1b;
    public static final int TEXTURE_FORMAT_RGB9_E5_UFLOAT = 0x1c;
    public static final int TEXTURE_FORMAT_RG32_FLOAT = 0x1d;
    public static final int TEXTURE_FORMAT_RG32_UINT = 0x1e;
    public static final int TEXTURE_FORMAT_RG32_SINT = 0x1f;
    public static final int TEXTURE_FORMAT_RGBA16_UINT = 0x20;
    public static final int TEXTURE_FORMAT_RGBA16_SINT = 0x21;
    public static final int TEXTURE_FORMAT_RGBA16_FLOAT = 0x22;
    public static final int TEXTURE_FORMAT_RGBA32_FLOAT = 0x23;
    public static final int TEXTURE_FORMAT_RGBA32_UINT = 0x24;
    public static final int TEXTURE_FORMAT_RGBA32_SINT = 0x25;
    public static final int TEXTURE_FORMAT_STENCIL8 = 0x26;
    public static final int TEXTURE_FORMAT_DEPTH16_UNORM = 0x27;
    public static final int TEXTURE_FORMAT_DEPTH24_PLUS = 0x28;
    public static final int TEXTURE_FORMAT_DEPTH24_PLUS_STENCIL8 = 0x29;
    public static final int TEXTURE_FORMAT_DEPTH32_FLOAT = 0x2a;
    public static final int TEXTURE_FORMAT_DEPTH32_FLOAT_STENCIL8 = 0x2b;
    public static final int TEXTURE_FORMAT_BC1_RGBA_UNORM = 0x2c;
    public static final int TEXTURE_FORMAT_BC1_RGBA_UNORM_SRGB = 0x2d;
    public static final int TEXTURE_FORMAT_BC2_RGBA_UNORM = 0x2e;
    public static final int TEXTURE_FORMAT_BC2_RGBA_UNORM_SRGB = 0x2f;
    public static final int TEXTURE_FORMAT_BC3_RGBA_UNORM = 0x30;
    public static final int TEXTURE_FORMAT_BC3_RGBA_UNORM_SRGB = 0x31;
    public static final int TEXTURE_FORMAT_BC4_R_UNORM = 0x32;
    public static final int TEXTURE_FORMAT_BC4_R_SNORM = 0x33;
    public static final int TEXTURE_FORMAT_BC5_RG_UNORM = 0x34;
    public static final int TEXTURE_FORMAT_BC5_RG_SNORM = 0x35;
    public static final int TEXTURE_FORMAT_BC6H_RGB_UFLOAT = 0x36;
    public static final int TEXTURE_FORMAT_BC6H_RGB_FLOAT = 0x37;
    public static final int TEXTURE_FORMAT_BC7_RGBA_UNORM = 0x38;
    public static final int TEXTURE_FORMAT_BC7_RGBA_UNORM_SRGB = 0x39;
    public static final int TEXTURE_FORMAT_ETC2_RGB8_UNORM = 0x3a;
    public static final int TEXTURE_FORMAT_ETC2_RGB8_UNORM_SRGB = 0x3b;
    public static final int TEXTURE_FORMAT_ETC2_RGB8A1_UNORM = 0x3c;
    public static final int TEXTURE_FORMAT_ETC2_RGB8A1_UNORM_SRGB = 0x3d;
    public static final int TEXTURE_FORMAT_ETC2_RGBA8_UNORM = 0x3e;
    public static final int TEXTURE_FORMAT_ETC2_RGBA8_UNORM_SRGB = 0x3f;
    public static final int TEXTURE_FORMAT_EAC_R11_UNORM = 0x40;
    public static final int TEXTURE_FORMAT_EAC_R11_SNORM = 0x41;
    public static final int TEXTURE_FORMAT_EAC_RG11_UNORM = 0x42;
    public static final int TEXTURE_FORMAT_EAC_RG11_SNORM = 0x43;
    public static final int TEXTURE_FORMAT_ASTC_4X4_UNORM = 0x44;
    public static final int TEXTURE_FORMAT_ASTC_4X4_UNORM_SRGB = 0x45;
    public static final int TEXTURE_FORMAT_ASTC_5X4_UNORM = 0x46;
    public static final int TEXTURE_FORMAT_ASTC_5X4_UNORM_SRGB = 0x47;
    public static final int TEXTURE_FORMAT_ASTC_5X5_UNORM = 0x48;
    public static final int TEXTURE_FORMAT_ASTC_5X5_UNORM_SRGB = 0x49;
    public static final int TEXTURE_FORMAT_ASTC_6X5_UNORM = 0x4a;
    public static final int TEXTURE_FORMAT_ASTC_6X5_UNORM_SRGB = 0x4b;
    public static final int TEXTURE_FORMAT_ASTC_6X6_UNORM = 0x4c;
    public static final int TEXTURE_FORMAT_ASTC_6X6_UNORM_SRGB = 0x4d;
    public static final int TEXTURE_FORMAT_ASTC_8X5_UNORM = 0x4e;
    public static final int TEXTURE_FORMAT_ASTC_8X5_UNORM_SRGB = 0x4f;
    public static final int TEXTURE_FORMAT_ASTC_8X6_UNORM = 0x50;
    public static final int TEXTURE_FORMAT_ASTC_8X6_UNORM_SRGB = 0x51;
    public static final int TEXTURE_FORMAT_ASTC_8X8_UNORM = 0x52;
    public static final int TEXTURE_FORMAT_ASTC_8X8_UNORM_SRGB = 0x53;
    public static final int TEXTURE_FORMAT_ASTC_10X5_UNORM = 0x54;
    public static final int TEXTURE_FORMAT_ASTC_10X5_UNORM_SRGB = 0x55;
    public static final int TEXTURE_FORMAT_ASTC_10X6_UNORM = 0x56;
    public static final int TEXTURE_FORMAT_ASTC_10X6_UNORM_SRGB = 0x57;
    public static final int TEXTURE_FORMAT_ASTC_10X8_UNORM = 0x58;
    public static final int TEXTURE_FORMAT_ASTC_10X8_UNORM_SRGB = 0x59;
    public static final int TEXTURE_FORMAT_ASTC_10X10_UNORM = 0x5a;
    public static final int TEXTURE_FORMAT_ASTC_10X10_UNORM_SRGB = 0x5b;
    public static final int TEXTURE_FORMAT_ASTC_12X10_UNORM = 0x5c;
    public static final int TEXTURE_FORMAT_ASTC_12X10_UNORM_SRGB = 0x5d;
    public static final int TEXTURE_FORMAT_ASTC_12X12_UNORM = 0x5e;
    public static final int TEXTURE_FORMAT_ASTC_12X12_UNORM_SRGB = 0x5f;
    public static final int TEXTURE_FORMAT_FORCE32 = 0x7fffffff;

    public static String explain(@EnumType(TextureFormat.class) int value) {
        return switch (value) {
            case TextureFormat.TEXTURE_FORMAT_ASTC_10X10_UNORM -> "TEXTURE_FORMAT_ASTC_10X10_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_10X10_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_10X10_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_10X5_UNORM -> "TEXTURE_FORMAT_ASTC_10X5_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_10X5_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_10X5_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_10X6_UNORM -> "TEXTURE_FORMAT_ASTC_10X6_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_10X6_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_10X6_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_10X8_UNORM -> "TEXTURE_FORMAT_ASTC_10X8_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_10X8_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_10X8_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_12X10_UNORM -> "TEXTURE_FORMAT_ASTC_12X10_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_12X10_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_12X10_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_12X12_UNORM -> "TEXTURE_FORMAT_ASTC_12X12_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_12X12_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_12X12_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_4X4_UNORM -> "TEXTURE_FORMAT_ASTC_4X4_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_4X4_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_4X4_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_5X4_UNORM -> "TEXTURE_FORMAT_ASTC_5X4_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_5X4_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_5X4_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_5X5_UNORM -> "TEXTURE_FORMAT_ASTC_5X5_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_5X5_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_5X5_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_6X5_UNORM -> "TEXTURE_FORMAT_ASTC_6X5_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_6X5_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_6X5_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_6X6_UNORM -> "TEXTURE_FORMAT_ASTC_6X6_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_6X6_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_6X6_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_8X5_UNORM -> "TEXTURE_FORMAT_ASTC_8X5_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_8X5_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_8X5_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_8X6_UNORM -> "TEXTURE_FORMAT_ASTC_8X6_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_8X6_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_8X6_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ASTC_8X8_UNORM -> "TEXTURE_FORMAT_ASTC_8X8_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ASTC_8X8_UNORM_SRGB -> "TEXTURE_FORMAT_ASTC_8X8_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_BC1_RGBA_UNORM -> "TEXTURE_FORMAT_BC1_RGBA_UNORM";
            case TextureFormat.TEXTURE_FORMAT_BC1_RGBA_UNORM_SRGB -> "TEXTURE_FORMAT_BC1_RGBA_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_BC2_RGBA_UNORM -> "TEXTURE_FORMAT_BC2_RGBA_UNORM";
            case TextureFormat.TEXTURE_FORMAT_BC2_RGBA_UNORM_SRGB -> "TEXTURE_FORMAT_BC2_RGBA_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_BC3_RGBA_UNORM -> "TEXTURE_FORMAT_BC3_RGBA_UNORM";
            case TextureFormat.TEXTURE_FORMAT_BC3_RGBA_UNORM_SRGB -> "TEXTURE_FORMAT_BC3_RGBA_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_BC4_R_SNORM -> "TEXTURE_FORMAT_BC4_R_SNORM";
            case TextureFormat.TEXTURE_FORMAT_BC4_R_UNORM -> "TEXTURE_FORMAT_BC4_R_UNORM";
            case TextureFormat.TEXTURE_FORMAT_BC5_RG_SNORM -> "TEXTURE_FORMAT_BC5_RG_SNORM";
            case TextureFormat.TEXTURE_FORMAT_BC5_RG_UNORM -> "TEXTURE_FORMAT_BC5_RG_UNORM";
            case TextureFormat.TEXTURE_FORMAT_BC6H_RGB_FLOAT -> "TEXTURE_FORMAT_BC6H_RGB_FLOAT";
            case TextureFormat.TEXTURE_FORMAT_BC6H_RGB_UFLOAT -> "TEXTURE_FORMAT_BC6H_RGB_UFLOAT";
            case TextureFormat.TEXTURE_FORMAT_BC7_RGBA_UNORM -> "TEXTURE_FORMAT_BC7_RGBA_UNORM";
            case TextureFormat.TEXTURE_FORMAT_BC7_RGBA_UNORM_SRGB -> "TEXTURE_FORMAT_BC7_RGBA_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_BGRA8_UNORM -> "TEXTURE_FORMAT_BGRA8_UNORM";
            case TextureFormat.TEXTURE_FORMAT_BGRA8_UNORM_SRGB -> "TEXTURE_FORMAT_BGRA8_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_DEPTH16_UNORM -> "TEXTURE_FORMAT_DEPTH16_UNORM";
            case TextureFormat.TEXTURE_FORMAT_DEPTH24_PLUS -> "TEXTURE_FORMAT_DEPTH24_PLUS";
            case TextureFormat.TEXTURE_FORMAT_DEPTH24_PLUS_STENCIL8 -> "TEXTURE_FORMAT_DEPTH24_PLUS_STENCIL8";
            case TextureFormat.TEXTURE_FORMAT_DEPTH32_FLOAT -> "TEXTURE_FORMAT_DEPTH32_FLOAT";
            case TextureFormat.TEXTURE_FORMAT_DEPTH32_FLOAT_STENCIL8 -> "TEXTURE_FORMAT_DEPTH32_FLOAT_STENCIL8";
            case TextureFormat.TEXTURE_FORMAT_EAC_R11_SNORM -> "TEXTURE_FORMAT_EAC_R11_SNORM";
            case TextureFormat.TEXTURE_FORMAT_EAC_R11_UNORM -> "TEXTURE_FORMAT_EAC_R11_UNORM";
            case TextureFormat.TEXTURE_FORMAT_EAC_RG11_SNORM -> "TEXTURE_FORMAT_EAC_RG11_SNORM";
            case TextureFormat.TEXTURE_FORMAT_EAC_RG11_UNORM -> "TEXTURE_FORMAT_EAC_RG11_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ETC2_RGB8A1_UNORM -> "TEXTURE_FORMAT_ETC2_RGB8A1_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ETC2_RGB8A1_UNORM_SRGB -> "TEXTURE_FORMAT_ETC2_RGB8A1_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ETC2_RGB8_UNORM -> "TEXTURE_FORMAT_ETC2_RGB8_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ETC2_RGB8_UNORM_SRGB -> "TEXTURE_FORMAT_ETC2_RGB8_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_ETC2_RGBA8_UNORM -> "TEXTURE_FORMAT_ETC2_RGBA8_UNORM";
            case TextureFormat.TEXTURE_FORMAT_ETC2_RGBA8_UNORM_SRGB -> "TEXTURE_FORMAT_ETC2_RGBA8_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_FORCE32 -> "TEXTURE_FORMAT_FORCE32";
            case TextureFormat.TEXTURE_FORMAT_R16_FLOAT -> "TEXTURE_FORMAT_R16_FLOAT";
            case TextureFormat.TEXTURE_FORMAT_R16_SINT -> "TEXTURE_FORMAT_R16_SINT";
            case TextureFormat.TEXTURE_FORMAT_R16_UINT -> "TEXTURE_FORMAT_R16_UINT";
            case TextureFormat.TEXTURE_FORMAT_R32_FLOAT -> "TEXTURE_FORMAT_R32_FLOAT";
            case TextureFormat.TEXTURE_FORMAT_R32_SINT -> "TEXTURE_FORMAT_R32_SINT";
            case TextureFormat.TEXTURE_FORMAT_R32_UINT -> "TEXTURE_FORMAT_R32_UINT";
            case TextureFormat.TEXTURE_FORMAT_R8_SINT -> "TEXTURE_FORMAT_R8_SINT";
            case TextureFormat.TEXTURE_FORMAT_R8_SNORM -> "TEXTURE_FORMAT_R8_SNORM";
            case TextureFormat.TEXTURE_FORMAT_R8_UINT -> "TEXTURE_FORMAT_R8_UINT";
            case TextureFormat.TEXTURE_FORMAT_R8_UNORM -> "TEXTURE_FORMAT_R8_UNORM";
            case TextureFormat.TEXTURE_FORMAT_RG11_B10_UFLOAT -> "TEXTURE_FORMAT_RG11_B10_UFLOAT";
            case TextureFormat.TEXTURE_FORMAT_RG16_FLOAT -> "TEXTURE_FORMAT_RG16_FLOAT";
            case TextureFormat.TEXTURE_FORMAT_RG16_SINT -> "TEXTURE_FORMAT_RG16_SINT";
            case TextureFormat.TEXTURE_FORMAT_RG16_UINT -> "TEXTURE_FORMAT_RG16_UINT";
            case TextureFormat.TEXTURE_FORMAT_RG32_FLOAT -> "TEXTURE_FORMAT_RG32_FLOAT";
            case TextureFormat.TEXTURE_FORMAT_RG32_SINT -> "TEXTURE_FORMAT_RG32_SINT";
            case TextureFormat.TEXTURE_FORMAT_RG32_UINT -> "TEXTURE_FORMAT_RG32_UINT";
            case TextureFormat.TEXTURE_FORMAT_RG8_SINT -> "TEXTURE_FORMAT_RG8_SINT";
            case TextureFormat.TEXTURE_FORMAT_RG8_SNORM -> "TEXTURE_FORMAT_RG8_SNORM";
            case TextureFormat.TEXTURE_FORMAT_RG8_UINT -> "TEXTURE_FORMAT_RG8_UINT";
            case TextureFormat.TEXTURE_FORMAT_RG8_UNORM -> "TEXTURE_FORMAT_RG8_UNORM";
            case TextureFormat.TEXTURE_FORMAT_RGB10_A2_UINT -> "TEXTURE_FORMAT_RGB10_A2_UINT";
            case TextureFormat.TEXTURE_FORMAT_RGB10_A2_UNORM -> "TEXTURE_FORMAT_RGB10_A2_UNORM";
            case TextureFormat.TEXTURE_FORMAT_RGB9_E5_UFLOAT -> "TEXTURE_FORMAT_RGB9_E5_UFLOAT";
            case TextureFormat.TEXTURE_FORMAT_RGBA16_FLOAT -> "TEXTURE_FORMAT_RGBA16_FLOAT";
            case TextureFormat.TEXTURE_FORMAT_RGBA16_SINT -> "TEXTURE_FORMAT_RGBA16_SINT";
            case TextureFormat.TEXTURE_FORMAT_RGBA16_UINT -> "TEXTURE_FORMAT_RGBA16_UINT";
            case TextureFormat.TEXTURE_FORMAT_RGBA32_FLOAT -> "TEXTURE_FORMAT_RGBA32_FLOAT";
            case TextureFormat.TEXTURE_FORMAT_RGBA32_SINT -> "TEXTURE_FORMAT_RGBA32_SINT";
            case TextureFormat.TEXTURE_FORMAT_RGBA32_UINT -> "TEXTURE_FORMAT_RGBA32_UINT";
            case TextureFormat.TEXTURE_FORMAT_RGBA8_SINT -> "TEXTURE_FORMAT_RGBA8_SINT";
            case TextureFormat.TEXTURE_FORMAT_RGBA8_SNORM -> "TEXTURE_FORMAT_RGBA8_SNORM";
            case TextureFormat.TEXTURE_FORMAT_RGBA8_UINT -> "TEXTURE_FORMAT_RGBA8_UINT";
            case TextureFormat.TEXTURE_FORMAT_RGBA8_UNORM -> "TEXTURE_FORMAT_RGBA8_UNORM";
            case TextureFormat.TEXTURE_FORMAT_RGBA8_UNORM_SRGB -> "TEXTURE_FORMAT_RGBA8_UNORM_SRGB";
            case TextureFormat.TEXTURE_FORMAT_STENCIL8 -> "TEXTURE_FORMAT_STENCIL8";
            case TextureFormat.TEXTURE_FORMAT_UNDEFINED -> "TEXTURE_FORMAT_UNDEFINED";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private TextureFormat() {}
}
