package tech.icey.vk4j.enumtype;

import tech.icey.panama.annotation.enumtype;

public final class VkIndirectCommandsTokenTypeNV {
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_SHADER_GROUP_NV = 0;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_STATE_FLAGS_NV = 1;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_NV = 2;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_NV = 3;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NV = 4;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_NV = 5;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_NV = 6;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_TASKS_NV = 7;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV = 1000328000;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NV = 1000428003;
    public static final int VK_INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_NV = 1000428004;

    public static String explain(@enumtype(VkIndirectCommandsTokenTypeNV.class) int value) {
        return switch (value) {
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_SHADER_GROUP_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_SHADER_GROUP_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_STATE_FLAGS_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_STATE_FLAGS_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_TASKS_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_TASKS_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NV";
            case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_NV -> "VK_INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_NV";
            default -> "Unknown";
        };
    }
}
