package tech.icey.vk4j.enumtype;

import tech.icey.panama.annotation.enumtype;

public final class VkLatencyMarkerNV {
    public static final int VK_LATENCY_MARKER_SIMULATION_START_NV = 0;
    public static final int VK_LATENCY_MARKER_SIMULATION_END_NV = 1;
    public static final int VK_LATENCY_MARKER_RENDERSUBMIT_START_NV = 2;
    public static final int VK_LATENCY_MARKER_RENDERSUBMIT_END_NV = 3;
    public static final int VK_LATENCY_MARKER_PRESENT_START_NV = 4;
    public static final int VK_LATENCY_MARKER_PRESENT_END_NV = 5;
    public static final int VK_LATENCY_MARKER_INPUT_SAMPLE_NV = 6;
    public static final int VK_LATENCY_MARKER_TRIGGER_FLASH_NV = 7;
    public static final int VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_START_NV = 8;
    public static final int VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_END_NV = 9;
    public static final int VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_START_NV = 10;
    public static final int VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_END_NV = 11;

    public static String explain(@enumtype(VkLatencyMarkerNV.class) int value) {
        return switch (value) {
            case VK_LATENCY_MARKER_SIMULATION_START_NV -> "VK_LATENCY_MARKER_SIMULATION_START_NV";
            case VK_LATENCY_MARKER_SIMULATION_END_NV -> "VK_LATENCY_MARKER_SIMULATION_END_NV";
            case VK_LATENCY_MARKER_RENDERSUBMIT_START_NV -> "VK_LATENCY_MARKER_RENDERSUBMIT_START_NV";
            case VK_LATENCY_MARKER_RENDERSUBMIT_END_NV -> "VK_LATENCY_MARKER_RENDERSUBMIT_END_NV";
            case VK_LATENCY_MARKER_PRESENT_START_NV -> "VK_LATENCY_MARKER_PRESENT_START_NV";
            case VK_LATENCY_MARKER_PRESENT_END_NV -> "VK_LATENCY_MARKER_PRESENT_END_NV";
            case VK_LATENCY_MARKER_INPUT_SAMPLE_NV -> "VK_LATENCY_MARKER_INPUT_SAMPLE_NV";
            case VK_LATENCY_MARKER_TRIGGER_FLASH_NV -> "VK_LATENCY_MARKER_TRIGGER_FLASH_NV";
            case VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_START_NV -> "VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_START_NV";
            case VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_END_NV -> "VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_END_NV";
            case VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_START_NV -> "VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_START_NV";
            case VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_END_NV -> "VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_END_NV";
            default -> "Unknown";
        };
    }
}
