package tech.icey.vk4j.enumtype;

import tech.icey.vk4j.annotation.enumtype;

public final class VkOpticalFlowSessionBindingPointNV {
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_UNKNOWN_NV = 0;
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_INPUT_NV = 1;
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_REFERENCE_NV = 2;
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_HINT_NV = 3;
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_FLOW_VECTOR_NV = 4;
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_FLOW_VECTOR_NV = 5;
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_COST_NV = 6;
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NV = 7;
    public static final int VK_OPTICAL_FLOW_SESSION_BINDING_POINT_GLOBAL_FLOW_NV = 8;

    public static String explain(@enumtype(VkOpticalFlowSessionBindingPointNV.class) int value) {
        return switch (value) {
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_UNKNOWN_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_UNKNOWN_NV";
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_INPUT_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_INPUT_NV";
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_REFERENCE_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_REFERENCE_NV";
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_HINT_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_HINT_NV";
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_FLOW_VECTOR_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_FLOW_VECTOR_NV";
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_FLOW_VECTOR_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_FLOW_VECTOR_NV";
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_COST_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_COST_NV";
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NV";
            case VK_OPTICAL_FLOW_SESSION_BINDING_POINT_GLOBAL_FLOW_NV -> "VK_OPTICAL_FLOW_SESSION_BINDING_POINT_GLOBAL_FLOW_NV";
            default -> "Unknown";
        };
    }
}
