package tech.icey.vk4j.enumtype;

import tech.icey.panama.annotation.enumtype;

public final class VkPerformanceCounterUnitKHR {
    public static final int VK_PERFORMANCE_COUNTER_UNIT_GENERIC_KHR = 0;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_PERCENTAGE_KHR = 1;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_NANOSECONDS_KHR = 2;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_BYTES_KHR = 3;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_BYTES_PER_SECOND_KHR = 4;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_KELVIN_KHR = 5;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_WATTS_KHR = 6;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_VOLTS_KHR = 7;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_AMPS_KHR = 8;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_HERTZ_KHR = 9;
    public static final int VK_PERFORMANCE_COUNTER_UNIT_CYCLES_KHR = 10;

    public static String explain(@enumtype(VkPerformanceCounterUnitKHR.class) int value) {
        return switch (value) {
            case VK_PERFORMANCE_COUNTER_UNIT_GENERIC_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_GENERIC_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_PERCENTAGE_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_PERCENTAGE_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_NANOSECONDS_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_NANOSECONDS_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_BYTES_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_BYTES_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_BYTES_PER_SECOND_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_BYTES_PER_SECOND_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_KELVIN_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_KELVIN_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_WATTS_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_WATTS_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_VOLTS_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_VOLTS_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_AMPS_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_AMPS_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_HERTZ_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_HERTZ_KHR";
            case VK_PERFORMANCE_COUNTER_UNIT_CYCLES_KHR -> "VK_PERFORMANCE_COUNTER_UNIT_CYCLES_KHR";
            default -> "Unknown";
        };
    }
}
