package tech.icey.vk4j.enumtype;

import tech.icey.panama.annotation.enumtype;

public final class VkValidationFeatureDisableEXT {
    public static final int VK_VALIDATION_FEATURE_DISABLE_ALL_EXT = 0;
    public static final int VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT = 1;
    public static final int VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT = 2;
    public static final int VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT = 3;
    public static final int VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT = 4;
    public static final int VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT = 5;
    public static final int VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT = 6;
    public static final int VK_VALIDATION_FEATURE_DISABLE_SHADER_VALIDATION_CACHE_EXT = 7;

    public static String explain(@enumtype(VkValidationFeatureDisableEXT.class) int value) {
        return switch (value) {
            case VK_VALIDATION_FEATURE_DISABLE_ALL_EXT -> "VK_VALIDATION_FEATURE_DISABLE_ALL_EXT";
            case VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT -> "VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT";
            case VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT -> "VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT";
            case VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT -> "VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT";
            case VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT -> "VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT";
            case VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT -> "VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT";
            case VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT -> "VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT";
            case VK_VALIDATION_FEATURE_DISABLE_SHADER_VALIDATION_CACHE_EXT -> "VK_VALIDATION_FEATURE_DISABLE_SHADER_VALIDATION_CACHE_EXT";
            default -> "Unknown";
        };
    }
}
