package tech.icey.vk4j.enumtype;

import tech.icey.panama.annotation.enumtype;

public final class VkValidationFeatureEnableEXT {
    public static final int VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT = 0;
    public static final int VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT = 1;
    public static final int VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT = 2;
    public static final int VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT = 3;
    public static final int VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT = 4;

    public static String explain(@enumtype(VkValidationFeatureEnableEXT.class) int value) {
        return switch (value) {
            case VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT -> "VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT";
            case VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT -> "VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT";
            case VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT -> "VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT";
            case VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT -> "VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT";
            case VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT -> "VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT";
            default -> "Unknown";
        };
    }
}
