package tech.icey.vk4j.enumtype;

import tech.icey.panama.annotation.enumtype;

public final class VkViewportCoordinateSwizzleNV {
    public static final int VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV = 0;
    public static final int VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV = 1;
    public static final int VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV = 2;
    public static final int VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV = 3;
    public static final int VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV = 4;
    public static final int VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV = 5;
    public static final int VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV = 6;
    public static final int VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV = 7;

    public static String explain(@enumtype(VkViewportCoordinateSwizzleNV.class) int value) {
        return switch (value) {
            case VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV -> "VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV";
            case VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV -> "VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV";
            case VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV -> "VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV";
            case VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV -> "VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV";
            case VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV -> "VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV";
            case VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV -> "VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV";
            case VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV -> "VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV";
            case VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV -> "VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV";
            default -> "Unknown";
        };
    }
}
