package cc.design7.vulkan.enumtype;

import cc.design7.ffm.annotation.*;

/// @see <a href="https://registry.khronos.org/vulkan/specs/latest/man/html/VkDynamicState.html">VkDynamicState</a>
public final class VkDynamicState {
    public static final int VIEWPORT = 0x0;
    public static final int SCISSOR = 0x1;
    public static final int LINE_WIDTH = 0x2;
    public static final int DEPTH_BIAS = 0x3;
    public static final int BLEND_CONSTANTS = 0x4;
    public static final int DEPTH_BOUNDS = 0x5;
    public static final int STENCIL_COMPARE_MASK = 0x6;
    public static final int STENCIL_WRITE_MASK = 0x7;
    public static final int STENCIL_REFERENCE = 0x8;
    public static final int CULL_MODE = 0x3b9edcf8;
    public static final int FRONT_FACE = 0x3b9edcf9;
    public static final int PRIMITIVE_TOPOLOGY = 0x3b9edcfa;
    public static final int VIEWPORT_WITH_COUNT = 0x3b9edcfb;
    public static final int SCISSOR_WITH_COUNT = 0x3b9edcfc;
    public static final int VERTEX_INPUT_BINDING_STRIDE = 0x3b9edcfd;
    public static final int DEPTH_TEST_ENABLE = 0x3b9edcfe;
    public static final int DEPTH_WRITE_ENABLE = 0x3b9edcff;
    public static final int DEPTH_COMPARE_OP = 0x3b9edd00;
    public static final int DEPTH_BOUNDS_TEST_ENABLE = 0x3b9edd01;
    public static final int STENCIL_TEST_ENABLE = 0x3b9edd02;
    public static final int STENCIL_OP = 0x3b9edd03;
    public static final int RASTERIZER_DISCARD_ENABLE = 0x3ba08aa9;
    public static final int DEPTH_BIAS_ENABLE = 0x3ba08aaa;
    public static final int PRIMITIVE_RESTART_ENABLE = 0x3ba08aac;
    public static final int LINE_STIPPLE = 0x3b9ebdb8;
    public static final int VIEWPORT_W_SCALING_NV = 0x3b9c1dd8;
    public static final int DISCARD_RECTANGLE_EXT = 0x3b9c4cb8;
    public static final int DISCARD_RECTANGLE_ENABLE_EXT = 0x3b9c4cb9;
    public static final int DISCARD_RECTANGLE_MODE_EXT = 0x3b9c4cba;
    public static final int SAMPLE_LOCATIONS_EXT = 0x3b9cf898;
    public static final int RAY_TRACING_PIPELINE_STACK_SIZE_KHR = 0x3ba01578;
    public static final int VIEWPORT_SHADING_RATE_PALETTE_NV = 0x3b9d4aa4;
    public static final int VIEWPORT_COARSE_SAMPLE_ORDER_NV = 0x3b9d4aa6;
    public static final int EXCLUSIVE_SCISSOR_ENABLE_NV = 0x3b9deac8;
    public static final int EXCLUSIVE_SCISSOR_NV = 0x3b9deac9;
    public static final int FRAGMENT_SHADING_RATE_KHR = 0x3b9e3cd0;
    public static final int VERTEX_INPUT_EXT = 0x3ba02900;
    public static final int PATCH_CONTROL_POINTS_EXT = 0x3ba08aa8;
    public static final int LOGIC_OP_EXT = 0x3ba08aab;
    public static final int COLOR_WRITE_ENABLE_EXT = 0x3ba09a48;
    public static final int DEPTH_CLAMP_ENABLE_EXT = 0x3ba1bb5b;
    public static final int POLYGON_MODE_EXT = 0x3ba1bb5c;
    public static final int RASTERIZATION_SAMPLES_EXT = 0x3ba1bb5d;
    public static final int SAMPLE_MASK_EXT = 0x3ba1bb5e;
    public static final int ALPHA_TO_COVERAGE_ENABLE_EXT = 0x3ba1bb5f;
    public static final int ALPHA_TO_ONE_ENABLE_EXT = 0x3ba1bb60;
    public static final int LOGIC_OP_ENABLE_EXT = 0x3ba1bb61;
    public static final int COLOR_BLEND_ENABLE_EXT = 0x3ba1bb62;
    public static final int COLOR_BLEND_EQUATION_EXT = 0x3ba1bb63;
    public static final int COLOR_WRITE_MASK_EXT = 0x3ba1bb64;
    public static final int TESSELLATION_DOMAIN_ORIGIN_EXT = 0x3ba1bb5a;
    public static final int RASTERIZATION_STREAM_EXT = 0x3ba1bb65;
    public static final int CONSERVATIVE_RASTERIZATION_MODE_EXT = 0x3ba1bb66;
    public static final int EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT = 0x3ba1bb67;
    public static final int DEPTH_CLIP_ENABLE_EXT = 0x3ba1bb68;
    public static final int SAMPLE_LOCATIONS_ENABLE_EXT = 0x3ba1bb69;
    public static final int COLOR_BLEND_ADVANCED_EXT = 0x3ba1bb6a;
    public static final int PROVOKING_VERTEX_MODE_EXT = 0x3ba1bb6b;
    public static final int LINE_RASTERIZATION_MODE_EXT = 0x3ba1bb6c;
    public static final int LINE_STIPPLE_ENABLE_EXT = 0x3ba1bb6d;
    public static final int DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT = 0x3ba1bb6e;
    public static final int VIEWPORT_W_SCALING_ENABLE_NV = 0x3ba1bb6f;
    public static final int VIEWPORT_SWIZZLE_NV = 0x3ba1bb70;
    public static final int COVERAGE_TO_COLOR_ENABLE_NV = 0x3ba1bb71;
    public static final int COVERAGE_TO_COLOR_LOCATION_NV = 0x3ba1bb72;
    public static final int COVERAGE_MODULATION_MODE_NV = 0x3ba1bb73;
    public static final int COVERAGE_MODULATION_TABLE_ENABLE_NV = 0x3ba1bb74;
    public static final int COVERAGE_MODULATION_TABLE_NV = 0x3ba1bb75;
    public static final int SHADING_RATE_IMAGE_ENABLE_NV = 0x3ba1bb76;
    public static final int REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV = 0x3ba1bb77;
    public static final int COVERAGE_REDUCTION_MODE_NV = 0x3ba1bb78;
    public static final int ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT = 0x3ba2c8e0;
    public static final int DEPTH_CLAMP_RANGE_EXT = 0x3ba3ab70;

    public static String explain(@enumtype(VkDynamicState.class) int value) {
        return switch (value) {
            case VkDynamicState.ALPHA_TO_COVERAGE_ENABLE_EXT -> "VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT";
            case VkDynamicState.ALPHA_TO_ONE_ENABLE_EXT -> "VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT";
            case VkDynamicState.ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT -> "VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT";
            case VkDynamicState.BLEND_CONSTANTS -> "VK_DYNAMIC_STATE_BLEND_CONSTANTS";
            case VkDynamicState.COLOR_BLEND_ADVANCED_EXT -> "VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT";
            case VkDynamicState.COLOR_BLEND_ENABLE_EXT -> "VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT";
            case VkDynamicState.COLOR_BLEND_EQUATION_EXT -> "VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT";
            case VkDynamicState.COLOR_WRITE_ENABLE_EXT -> "VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT";
            case VkDynamicState.COLOR_WRITE_MASK_EXT -> "VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT";
            case VkDynamicState.CONSERVATIVE_RASTERIZATION_MODE_EXT -> "VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT";
            case VkDynamicState.COVERAGE_MODULATION_MODE_NV -> "VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV";
            case VkDynamicState.COVERAGE_MODULATION_TABLE_ENABLE_NV -> "VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV";
            case VkDynamicState.COVERAGE_MODULATION_TABLE_NV -> "VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV";
            case VkDynamicState.COVERAGE_REDUCTION_MODE_NV -> "VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV";
            case VkDynamicState.COVERAGE_TO_COLOR_ENABLE_NV -> "VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV";
            case VkDynamicState.COVERAGE_TO_COLOR_LOCATION_NV -> "VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV";
            case VkDynamicState.CULL_MODE -> "VK_DYNAMIC_STATE_CULL_MODE";
            case VkDynamicState.DEPTH_BIAS -> "VK_DYNAMIC_STATE_DEPTH_BIAS";
            case VkDynamicState.DEPTH_BIAS_ENABLE -> "VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE";
            case VkDynamicState.DEPTH_BOUNDS -> "VK_DYNAMIC_STATE_DEPTH_BOUNDS";
            case VkDynamicState.DEPTH_BOUNDS_TEST_ENABLE -> "VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE";
            case VkDynamicState.DEPTH_CLAMP_ENABLE_EXT -> "VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT";
            case VkDynamicState.DEPTH_CLAMP_RANGE_EXT -> "VK_DYNAMIC_STATE_DEPTH_CLAMP_RANGE_EXT";
            case VkDynamicState.DEPTH_CLIP_ENABLE_EXT -> "VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT";
            case VkDynamicState.DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT -> "VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT";
            case VkDynamicState.DEPTH_COMPARE_OP -> "VK_DYNAMIC_STATE_DEPTH_COMPARE_OP";
            case VkDynamicState.DEPTH_TEST_ENABLE -> "VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE";
            case VkDynamicState.DEPTH_WRITE_ENABLE -> "VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE";
            case VkDynamicState.DISCARD_RECTANGLE_ENABLE_EXT -> "VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT";
            case VkDynamicState.DISCARD_RECTANGLE_EXT -> "VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT";
            case VkDynamicState.DISCARD_RECTANGLE_MODE_EXT -> "VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT";
            case VkDynamicState.EXCLUSIVE_SCISSOR_ENABLE_NV -> "VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV";
            case VkDynamicState.EXCLUSIVE_SCISSOR_NV -> "VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV";
            case VkDynamicState.EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT -> "VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT";
            case VkDynamicState.FRAGMENT_SHADING_RATE_KHR -> "VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR";
            case VkDynamicState.FRONT_FACE -> "VK_DYNAMIC_STATE_FRONT_FACE";
            case VkDynamicState.LINE_RASTERIZATION_MODE_EXT -> "VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT";
            case VkDynamicState.LINE_STIPPLE -> "VK_DYNAMIC_STATE_LINE_STIPPLE";
            case VkDynamicState.LINE_STIPPLE_ENABLE_EXT -> "VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT";
            case VkDynamicState.LINE_WIDTH -> "VK_DYNAMIC_STATE_LINE_WIDTH";
            case VkDynamicState.LOGIC_OP_ENABLE_EXT -> "VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT";
            case VkDynamicState.LOGIC_OP_EXT -> "VK_DYNAMIC_STATE_LOGIC_OP_EXT";
            case VkDynamicState.PATCH_CONTROL_POINTS_EXT -> "VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT";
            case VkDynamicState.POLYGON_MODE_EXT -> "VK_DYNAMIC_STATE_POLYGON_MODE_EXT";
            case VkDynamicState.PRIMITIVE_RESTART_ENABLE -> "VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE";
            case VkDynamicState.PRIMITIVE_TOPOLOGY -> "VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY";
            case VkDynamicState.PROVOKING_VERTEX_MODE_EXT -> "VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT";
            case VkDynamicState.RASTERIZATION_SAMPLES_EXT -> "VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT";
            case VkDynamicState.RASTERIZATION_STREAM_EXT -> "VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT";
            case VkDynamicState.RASTERIZER_DISCARD_ENABLE -> "VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE";
            case VkDynamicState.RAY_TRACING_PIPELINE_STACK_SIZE_KHR -> "VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR";
            case VkDynamicState.REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV -> "VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV";
            case VkDynamicState.SAMPLE_LOCATIONS_ENABLE_EXT -> "VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT";
            case VkDynamicState.SAMPLE_LOCATIONS_EXT -> "VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT";
            case VkDynamicState.SAMPLE_MASK_EXT -> "VK_DYNAMIC_STATE_SAMPLE_MASK_EXT";
            case VkDynamicState.SCISSOR -> "VK_DYNAMIC_STATE_SCISSOR";
            case VkDynamicState.SCISSOR_WITH_COUNT -> "VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT";
            case VkDynamicState.SHADING_RATE_IMAGE_ENABLE_NV -> "VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV";
            case VkDynamicState.STENCIL_COMPARE_MASK -> "VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK";
            case VkDynamicState.STENCIL_OP -> "VK_DYNAMIC_STATE_STENCIL_OP";
            case VkDynamicState.STENCIL_REFERENCE -> "VK_DYNAMIC_STATE_STENCIL_REFERENCE";
            case VkDynamicState.STENCIL_TEST_ENABLE -> "VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE";
            case VkDynamicState.STENCIL_WRITE_MASK -> "VK_DYNAMIC_STATE_STENCIL_WRITE_MASK";
            case VkDynamicState.TESSELLATION_DOMAIN_ORIGIN_EXT -> "VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT";
            case VkDynamicState.VERTEX_INPUT_BINDING_STRIDE -> "VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE";
            case VkDynamicState.VERTEX_INPUT_EXT -> "VK_DYNAMIC_STATE_VERTEX_INPUT_EXT";
            case VkDynamicState.VIEWPORT -> "VK_DYNAMIC_STATE_VIEWPORT";
            case VkDynamicState.VIEWPORT_COARSE_SAMPLE_ORDER_NV -> "VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV";
            case VkDynamicState.VIEWPORT_SHADING_RATE_PALETTE_NV -> "VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV";
            case VkDynamicState.VIEWPORT_SWIZZLE_NV -> "VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV";
            case VkDynamicState.VIEWPORT_WITH_COUNT -> "VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT";
            case VkDynamicState.VIEWPORT_W_SCALING_ENABLE_NV -> "VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV";
            case VkDynamicState.VIEWPORT_W_SCALING_NV -> "VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private VkDynamicState() {}
}
