package cc.design7.vulkan.enumtype;

import cc.design7.ffm.annotation.*;

/// @see <a href="https://registry.khronos.org/vulkan/specs/latest/man/html/VkDynamicState.html">VkDynamicState</a>
public final class VkDynamicState {
    public static final int VIEWPORT = 0;
    public static final int SCISSOR = 1;
    public static final int LINE_WIDTH = 2;
    public static final int DEPTH_BIAS = 3;
    public static final int BLEND_CONSTANTS = 4;
    public static final int DEPTH_BOUNDS = 5;
    public static final int STENCIL_COMPARE_MASK = 6;
    public static final int STENCIL_WRITE_MASK = 7;
    public static final int STENCIL_REFERENCE = 8;
    public static final int CULL_MODE = 1000267000;
    public static final int FRONT_FACE = 1000267001;
    public static final int PRIMITIVE_TOPOLOGY = 1000267002;
    public static final int VIEWPORT_WITH_COUNT = 1000267003;
    public static final int SCISSOR_WITH_COUNT = 1000267004;
    public static final int VERTEX_INPUT_BINDING_STRIDE = 1000267005;
    public static final int DEPTH_TEST_ENABLE = 1000267006;
    public static final int DEPTH_WRITE_ENABLE = 1000267007;
    public static final int DEPTH_COMPARE_OP = 1000267008;
    public static final int DEPTH_BOUNDS_TEST_ENABLE = 1000267009;
    public static final int STENCIL_TEST_ENABLE = 1000267010;
    public static final int STENCIL_OP = 1000267011;
    public static final int RASTERIZER_DISCARD_ENABLE = 1000377001;
    public static final int DEPTH_BIAS_ENABLE = 1000377002;
    public static final int PRIMITIVE_RESTART_ENABLE = 1000377004;
    public static final int LINE_STIPPLE = 1000259000;
    public static final int VIEWPORT_W_SCALING_NV = 1000087000;
    public static final int DISCARD_RECTANGLE_EXT = 1000099000;
    public static final int DISCARD_RECTANGLE_ENABLE_EXT = 1000099001;
    public static final int DISCARD_RECTANGLE_MODE_EXT = 1000099002;
    public static final int SAMPLE_LOCATIONS_EXT = 1000143000;
    public static final int RAY_TRACING_PIPELINE_STACK_SIZE_KHR = 1000347000;
    public static final int VIEWPORT_SHADING_RATE_PALETTE_NV = 1000164004;
    public static final int VIEWPORT_COARSE_SAMPLE_ORDER_NV = 1000164006;
    public static final int EXCLUSIVE_SCISSOR_ENABLE_NV = 1000205000;
    public static final int EXCLUSIVE_SCISSOR_NV = 1000205001;
    public static final int FRAGMENT_SHADING_RATE_KHR = 1000226000;
    public static final int VERTEX_INPUT_EXT = 1000352000;
    public static final int PATCH_CONTROL_POINTS_EXT = 1000377000;
    public static final int LOGIC_OP_EXT = 1000377003;
    public static final int COLOR_WRITE_ENABLE_EXT = 1000381000;
    public static final int DEPTH_CLAMP_ENABLE_EXT = 1000455003;
    public static final int POLYGON_MODE_EXT = 1000455004;
    public static final int RASTERIZATION_SAMPLES_EXT = 1000455005;
    public static final int SAMPLE_MASK_EXT = 1000455006;
    public static final int ALPHA_TO_COVERAGE_ENABLE_EXT = 1000455007;
    public static final int ALPHA_TO_ONE_ENABLE_EXT = 1000455008;
    public static final int LOGIC_OP_ENABLE_EXT = 1000455009;
    public static final int COLOR_BLEND_ENABLE_EXT = 1000455010;
    public static final int COLOR_BLEND_EQUATION_EXT = 1000455011;
    public static final int COLOR_WRITE_MASK_EXT = 1000455012;
    public static final int TESSELLATION_DOMAIN_ORIGIN_EXT = 1000455002;
    public static final int RASTERIZATION_STREAM_EXT = 1000455013;
    public static final int CONSERVATIVE_RASTERIZATION_MODE_EXT = 1000455014;
    public static final int EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT = 1000455015;
    public static final int DEPTH_CLIP_ENABLE_EXT = 1000455016;
    public static final int SAMPLE_LOCATIONS_ENABLE_EXT = 1000455017;
    public static final int COLOR_BLEND_ADVANCED_EXT = 1000455018;
    public static final int PROVOKING_VERTEX_MODE_EXT = 1000455019;
    public static final int LINE_RASTERIZATION_MODE_EXT = 1000455020;
    public static final int LINE_STIPPLE_ENABLE_EXT = 1000455021;
    public static final int DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT = 1000455022;
    public static final int VIEWPORT_W_SCALING_ENABLE_NV = 1000455023;
    public static final int VIEWPORT_SWIZZLE_NV = 1000455024;
    public static final int COVERAGE_TO_COLOR_ENABLE_NV = 1000455025;
    public static final int COVERAGE_TO_COLOR_LOCATION_NV = 1000455026;
    public static final int COVERAGE_MODULATION_MODE_NV = 1000455027;
    public static final int COVERAGE_MODULATION_TABLE_ENABLE_NV = 1000455028;
    public static final int COVERAGE_MODULATION_TABLE_NV = 1000455029;
    public static final int SHADING_RATE_IMAGE_ENABLE_NV = 1000455030;
    public static final int REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV = 1000455031;
    public static final int COVERAGE_REDUCTION_MODE_NV = 1000455032;
    public static final int ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT = 1000524000;
    public static final int DEPTH_CLAMP_RANGE_EXT = 1000582000;

    public static String explain(@enumtype(VkDynamicState.class) int value) {
        return switch (value) {
            case VkDynamicState.ALPHA_TO_COVERAGE_ENABLE_EXT -> "VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT";
            case VkDynamicState.ALPHA_TO_ONE_ENABLE_EXT -> "VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT";
            case VkDynamicState.ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT -> "VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT";
            case VkDynamicState.BLEND_CONSTANTS -> "VK_DYNAMIC_STATE_BLEND_CONSTANTS";
            case VkDynamicState.COLOR_BLEND_ADVANCED_EXT -> "VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT";
            case VkDynamicState.COLOR_BLEND_ENABLE_EXT -> "VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT";
            case VkDynamicState.COLOR_BLEND_EQUATION_EXT -> "VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT";
            case VkDynamicState.COLOR_WRITE_ENABLE_EXT -> "VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT";
            case VkDynamicState.COLOR_WRITE_MASK_EXT -> "VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT";
            case VkDynamicState.CONSERVATIVE_RASTERIZATION_MODE_EXT -> "VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT";
            case VkDynamicState.COVERAGE_MODULATION_MODE_NV -> "VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV";
            case VkDynamicState.COVERAGE_MODULATION_TABLE_ENABLE_NV -> "VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV";
            case VkDynamicState.COVERAGE_MODULATION_TABLE_NV -> "VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV";
            case VkDynamicState.COVERAGE_REDUCTION_MODE_NV -> "VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV";
            case VkDynamicState.COVERAGE_TO_COLOR_ENABLE_NV -> "VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV";
            case VkDynamicState.COVERAGE_TO_COLOR_LOCATION_NV -> "VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV";
            case VkDynamicState.CULL_MODE -> "VK_DYNAMIC_STATE_CULL_MODE";
            case VkDynamicState.DEPTH_BIAS -> "VK_DYNAMIC_STATE_DEPTH_BIAS";
            case VkDynamicState.DEPTH_BIAS_ENABLE -> "VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE";
            case VkDynamicState.DEPTH_BOUNDS -> "VK_DYNAMIC_STATE_DEPTH_BOUNDS";
            case VkDynamicState.DEPTH_BOUNDS_TEST_ENABLE -> "VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE";
            case VkDynamicState.DEPTH_CLAMP_ENABLE_EXT -> "VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT";
            case VkDynamicState.DEPTH_CLAMP_RANGE_EXT -> "VK_DYNAMIC_STATE_DEPTH_CLAMP_RANGE_EXT";
            case VkDynamicState.DEPTH_CLIP_ENABLE_EXT -> "VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT";
            case VkDynamicState.DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT -> "VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT";
            case VkDynamicState.DEPTH_COMPARE_OP -> "VK_DYNAMIC_STATE_DEPTH_COMPARE_OP";
            case VkDynamicState.DEPTH_TEST_ENABLE -> "VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE";
            case VkDynamicState.DEPTH_WRITE_ENABLE -> "VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE";
            case VkDynamicState.DISCARD_RECTANGLE_ENABLE_EXT -> "VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT";
            case VkDynamicState.DISCARD_RECTANGLE_EXT -> "VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT";
            case VkDynamicState.DISCARD_RECTANGLE_MODE_EXT -> "VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT";
            case VkDynamicState.EXCLUSIVE_SCISSOR_ENABLE_NV -> "VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV";
            case VkDynamicState.EXCLUSIVE_SCISSOR_NV -> "VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV";
            case VkDynamicState.EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT -> "VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT";
            case VkDynamicState.FRAGMENT_SHADING_RATE_KHR -> "VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR";
            case VkDynamicState.FRONT_FACE -> "VK_DYNAMIC_STATE_FRONT_FACE";
            case VkDynamicState.LINE_RASTERIZATION_MODE_EXT -> "VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT";
            case VkDynamicState.LINE_STIPPLE -> "VK_DYNAMIC_STATE_LINE_STIPPLE";
            case VkDynamicState.LINE_STIPPLE_ENABLE_EXT -> "VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT";
            case VkDynamicState.LINE_WIDTH -> "VK_DYNAMIC_STATE_LINE_WIDTH";
            case VkDynamicState.LOGIC_OP_ENABLE_EXT -> "VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT";
            case VkDynamicState.LOGIC_OP_EXT -> "VK_DYNAMIC_STATE_LOGIC_OP_EXT";
            case VkDynamicState.PATCH_CONTROL_POINTS_EXT -> "VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT";
            case VkDynamicState.POLYGON_MODE_EXT -> "VK_DYNAMIC_STATE_POLYGON_MODE_EXT";
            case VkDynamicState.PRIMITIVE_RESTART_ENABLE -> "VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE";
            case VkDynamicState.PRIMITIVE_TOPOLOGY -> "VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY";
            case VkDynamicState.PROVOKING_VERTEX_MODE_EXT -> "VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT";
            case VkDynamicState.RASTERIZATION_SAMPLES_EXT -> "VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT";
            case VkDynamicState.RASTERIZATION_STREAM_EXT -> "VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT";
            case VkDynamicState.RASTERIZER_DISCARD_ENABLE -> "VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE";
            case VkDynamicState.RAY_TRACING_PIPELINE_STACK_SIZE_KHR -> "VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR";
            case VkDynamicState.REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV -> "VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV";
            case VkDynamicState.SAMPLE_LOCATIONS_ENABLE_EXT -> "VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT";
            case VkDynamicState.SAMPLE_LOCATIONS_EXT -> "VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT";
            case VkDynamicState.SAMPLE_MASK_EXT -> "VK_DYNAMIC_STATE_SAMPLE_MASK_EXT";
            case VkDynamicState.SCISSOR -> "VK_DYNAMIC_STATE_SCISSOR";
            case VkDynamicState.SCISSOR_WITH_COUNT -> "VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT";
            case VkDynamicState.SHADING_RATE_IMAGE_ENABLE_NV -> "VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV";
            case VkDynamicState.STENCIL_COMPARE_MASK -> "VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK";
            case VkDynamicState.STENCIL_OP -> "VK_DYNAMIC_STATE_STENCIL_OP";
            case VkDynamicState.STENCIL_REFERENCE -> "VK_DYNAMIC_STATE_STENCIL_REFERENCE";
            case VkDynamicState.STENCIL_TEST_ENABLE -> "VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE";
            case VkDynamicState.STENCIL_WRITE_MASK -> "VK_DYNAMIC_STATE_STENCIL_WRITE_MASK";
            case VkDynamicState.TESSELLATION_DOMAIN_ORIGIN_EXT -> "VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT";
            case VkDynamicState.VERTEX_INPUT_BINDING_STRIDE -> "VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE";
            case VkDynamicState.VERTEX_INPUT_EXT -> "VK_DYNAMIC_STATE_VERTEX_INPUT_EXT";
            case VkDynamicState.VIEWPORT -> "VK_DYNAMIC_STATE_VIEWPORT";
            case VkDynamicState.VIEWPORT_COARSE_SAMPLE_ORDER_NV -> "VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV";
            case VkDynamicState.VIEWPORT_SHADING_RATE_PALETTE_NV -> "VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV";
            case VkDynamicState.VIEWPORT_SWIZZLE_NV -> "VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV";
            case VkDynamicState.VIEWPORT_WITH_COUNT -> "VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT";
            case VkDynamicState.VIEWPORT_W_SCALING_ENABLE_NV -> "VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV";
            case VkDynamicState.VIEWPORT_W_SCALING_NV -> "VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV";
            default -> "Unknown VkDynamicState: " + value;
        };
    }
    /// Constructing this class is nonsense so the constructor is made private.
    private VkDynamicState() {}
}
