[book]
authors = ["Chuigda Whitegive", "CousinZe"]
language = "zh_CN"
multilingual = false
src = "src"
title = "Vulkan 教程 (Java)"

[output.html]
git-repository-url = "https://github.com/chuigda/vulkan4j"
