package club.doki7.webgpu;

import club.doki7.ffm.annotation.*;

public interface WGPUConstants {
    int FALSE = 0x0;
    int TRUE = 0x1;
    long ARRAY_LAYER_COUNT_UNDEFINED = 0xFFFFFFFFL;
    long COPY_STRIDE_UNDEFINED = 0xFFFFFFFFL;
    long DEPTH_SLICE_UNDEFINED = 0xFFFFFFFFL;
    long LIMIT_U32_UNDEFINED = 0xFFFFFFFFL;
    long LIMIT_U64_UNDEFINED = 0xFFFFFFFF_FFFFFFFFL;
    long MIP_LEVEL_COUNT_UNDEFINED = 0xFFFFFFFFL;
    long QUERY_SET_INDEX_UNDEFINED = 0xFFFFFFFFL;
    long WHOLE_MAP_SIZE = 0xFFFFFFFF_FFFFFFFFL;
    long WHOLE_SIZE = 0xFFFFFFFF_FFFFFFFFL;
}
