package club.doki7.sdl3.enumtype;

import club.doki7.ffm.annotation.*;

/// The types of events that can be delivered.
///
/// Since: This enum is available since SDL 3.2.0.
///
public final class SDL_EventType {
    public static final int FIRST = 0x0;
    public static final int QUIT = 0x100;
    public static final int TERMINATING = 0x102;
    public static final int LOW_MEMORY = 0x103;
    public static final int WILL_ENTER_BACKGROUND = 0x104;
    public static final int DID_ENTER_BACKGROUND = 0x105;
    public static final int WILL_ENTER_FOREGROUND = 0x106;
    public static final int DID_ENTER_FOREGROUND = 0x107;
    public static final int LOCALE_CHANGED = 0x108;
    public static final int SYSTEM_THEME_CHANGED = 0x109;
    public static final int DISPLAY_ORIENTATION = 0x151;
    public static final int DISPLAY_ADDED = 0x153;
    public static final int DISPLAY_REMOVED = 0x154;
    public static final int DISPLAY_MOVED = 0x155;
    public static final int DISPLAY_DESKTOP_MODE_CHANGED = 0x156;
    public static final int DISPLAY_CURRENT_MODE_CHANGED = 0x157;
    public static final int DISPLAY_CONTENT_SCALE_CHANGED = 0x158;
    public static final int DISPLAY_FIRST = DISPLAY_ORIENTATION;
    public static final int DISPLAY_LAST = DISPLAY_CONTENT_SCALE_CHANGED;
    public static final int WINDOW_SHOWN = 0x202;
    public static final int WINDOW_HIDDEN = 0x204;
    public static final int WINDOW_EXPOSED = 0x205;
    public static final int WINDOW_MOVED = 0x206;
    public static final int WINDOW_RESIZED = 0x207;
    public static final int WINDOW_PIXEL_SIZE_CHANGED = 0x208;
    public static final int WINDOW_METAL_VIEW_RESIZED = 0x209;
    public static final int WINDOW_MINIMIZED = 0x20a;
    public static final int WINDOW_MAXIMIZED = 0x20b;
    public static final int WINDOW_RESTORED = 0x20c;
    public static final int WINDOW_MOUSE_ENTER = 0x20d;
    public static final int WINDOW_MOUSE_LEAVE = 0x20e;
    public static final int WINDOW_FOCUS_GAINED = 0x20f;
    public static final int WINDOW_FOCUS_LOST = 0x210;
    public static final int WINDOW_CLOSE_REQUESTED = 0x211;
    public static final int WINDOW_HIT_TEST = 0x212;
    public static final int WINDOW_ICCPROF_CHANGED = 0x213;
    public static final int WINDOW_DISPLAY_CHANGED = 0x214;
    public static final int WINDOW_DISPLAY_SCALE_CHANGED = 0x215;
    public static final int WINDOW_SAFE_AREA_CHANGED = 0x216;
    public static final int WINDOW_OCCLUDED = 0x217;
    public static final int WINDOW_ENTER_FULLSCREEN = 0x218;
    public static final int WINDOW_LEAVE_FULLSCREEN = 0x219;
    public static final int WINDOW_DESTROYED = 0x21a;
    public static final int WINDOW_HDR_STATE_CHANGED = 0x21b;
    public static final int WINDOW_FIRST = WINDOW_SHOWN;
    public static final int WINDOW_LAST = WINDOW_HDR_STATE_CHANGED;
    public static final int KEY_DOWN = 0x300;
    public static final int KEY_UP = 0x302;
    public static final int TEXT_EDITING = 0x303;
    public static final int TEXT_INPUT = 0x304;
    public static final int KEYMAP_CHANGED = 0x305;
    public static final int KEYBOARD_ADDED = 0x306;
    public static final int KEYBOARD_REMOVED = 0x307;
    public static final int TEXT_EDITING_CANDIDATES = 0x308;
    public static final int MOUSE_MOTION = 0x400;
    public static final int MOUSE_BUTTON_DOWN = 0x402;
    public static final int MOUSE_BUTTON_UP = 0x403;
    public static final int MOUSE_WHEEL = 0x404;
    public static final int MOUSE_ADDED = 0x405;
    public static final int MOUSE_REMOVED = 0x406;
    public static final int JOYSTICK_AXIS_MOTION = 0x600;
    public static final int JOYSTICK_BALL_MOTION = 0x602;
    public static final int JOYSTICK_HAT_MOTION = 0x603;
    public static final int JOYSTICK_BUTTON_DOWN = 0x604;
    public static final int JOYSTICK_BUTTON_UP = 0x605;
    public static final int JOYSTICK_ADDED = 0x606;
    public static final int JOYSTICK_REMOVED = 0x607;
    public static final int JOYSTICK_BATTERY_UPDATED = 0x608;
    public static final int JOYSTICK_UPDATE_COMPLETE = 0x609;
    public static final int GAMEPAD_AXIS_MOTION = 0x650;
    public static final int GAMEPAD_BUTTON_DOWN = 0x652;
    public static final int GAMEPAD_BUTTON_UP = 0x653;
    public static final int GAMEPAD_ADDED = 0x654;
    public static final int GAMEPAD_REMOVED = 0x655;
    public static final int GAMEPAD_REMAPPED = 0x656;
    public static final int GAMEPAD_TOUCHPAD_DOWN = 0x657;
    public static final int GAMEPAD_TOUCHPAD_MOTION = 0x658;
    public static final int GAMEPAD_TOUCHPAD_UP = 0x659;
    public static final int GAMEPAD_SENSOR_UPDATE = 0x65a;
    public static final int GAMEPAD_UPDATE_COMPLETE = 0x65b;
    public static final int GAMEPAD_STEAM_HANDLE_UPDATED = 0x65c;
    public static final int FINGER_DOWN = 0x700;
    public static final int FINGER_UP = 0x702;
    public static final int FINGER_MOTION = 0x703;
    public static final int FINGER_CANCELED = 0x704;
    public static final int CLIPBOARD_UPDATE = 0x900;
    public static final int DROP_FILE = 0x1000;
    public static final int DROP_TEXT = 0x1002;
    public static final int DROP_BEGIN = 0x1003;
    public static final int DROP_COMPLETE = 0x1004;
    public static final int DROP_POSITION = 0x1005;
    public static final int AUDIO_DEVICE_ADDED = 0x1100;
    public static final int AUDIO_DEVICE_REMOVED = 0x1102;
    public static final int AUDIO_DEVICE_FORMAT_CHANGED = 0x1103;
    public static final int SENSOR_UPDATE = 0x1200;
    public static final int PEN_PROXIMITY_IN = 0x1300;
    public static final int PEN_PROXIMITY_OUT = 0x1302;
    public static final int PEN_DOWN = 0x1303;
    public static final int PEN_UP = 0x1304;
    public static final int PEN_BUTTON_DOWN = 0x1305;
    public static final int PEN_BUTTON_UP = 0x1306;
    public static final int PEN_MOTION = 0x1307;
    public static final int PEN_AXIS = 0x1308;
    public static final int CAMERA_DEVICE_ADDED = 0x1400;
    public static final int CAMERA_DEVICE_REMOVED = 0x1402;
    public static final int CAMERA_DEVICE_APPROVED = 0x1403;
    public static final int CAMERA_DEVICE_DENIED = 0x1404;
    public static final int RENDER_TARGETS_RESET = 0x2000;
    public static final int RENDER_DEVICE_RESET = 0x2002;
    public static final int RENDER_DEVICE_LOST = 0x2003;
    public static final int PRIVATE0 = 0x4000;
    public static final int PRIVATE1 = 0x4002;
    public static final int PRIVATE2 = 0x4003;
    public static final int PRIVATE3 = 0x4004;
    public static final int POLL_SENTINEL = 0x7f00;

    /// Events SDL_EVENT_USER through SDL_EVENT_LAST are for your use,
    /// and should be allocated with SDL_RegisterEvents()
    public static final int USER = 0x8000;

    /// This last event is only for bounding internal arrays
    public static final int LAST = 0xffff;
    public static final int ENUM_PADDING = 0x7fffffff;

    public static String explain(@EnumType(SDL_EventType.class) int value) {
        return switch (value) {
            case SDL_EventType.AUDIO_DEVICE_ADDED -> "SDL_EVENT_AUDIO_DEVICE_ADDED";
            case SDL_EventType.AUDIO_DEVICE_FORMAT_CHANGED -> "SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED";
            case SDL_EventType.AUDIO_DEVICE_REMOVED -> "SDL_EVENT_AUDIO_DEVICE_REMOVED";
            case SDL_EventType.CAMERA_DEVICE_ADDED -> "SDL_EVENT_CAMERA_DEVICE_ADDED";
            case SDL_EventType.CAMERA_DEVICE_APPROVED -> "SDL_EVENT_CAMERA_DEVICE_APPROVED";
            case SDL_EventType.CAMERA_DEVICE_DENIED -> "SDL_EVENT_CAMERA_DEVICE_DENIED";
            case SDL_EventType.CAMERA_DEVICE_REMOVED -> "SDL_EVENT_CAMERA_DEVICE_REMOVED";
            case SDL_EventType.CLIPBOARD_UPDATE -> "SDL_EVENT_CLIPBOARD_UPDATE";
            case SDL_EventType.DID_ENTER_BACKGROUND -> "SDL_EVENT_DID_ENTER_BACKGROUND";
            case SDL_EventType.DID_ENTER_FOREGROUND -> "SDL_EVENT_DID_ENTER_FOREGROUND";
            case SDL_EventType.DISPLAY_ADDED -> "SDL_EVENT_DISPLAY_ADDED";
            case SDL_EventType.DISPLAY_CONTENT_SCALE_CHANGED -> "SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED";
            case SDL_EventType.DISPLAY_CURRENT_MODE_CHANGED -> "SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED";
            case SDL_EventType.DISPLAY_DESKTOP_MODE_CHANGED -> "SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED";
            case SDL_EventType.DISPLAY_MOVED -> "SDL_EVENT_DISPLAY_MOVED";
            case SDL_EventType.DISPLAY_ORIENTATION -> "SDL_EVENT_DISPLAY_ORIENTATION";
            case SDL_EventType.DISPLAY_REMOVED -> "SDL_EVENT_DISPLAY_REMOVED";
            case SDL_EventType.DROP_BEGIN -> "SDL_EVENT_DROP_BEGIN";
            case SDL_EventType.DROP_COMPLETE -> "SDL_EVENT_DROP_COMPLETE";
            case SDL_EventType.DROP_FILE -> "SDL_EVENT_DROP_FILE";
            case SDL_EventType.DROP_POSITION -> "SDL_EVENT_DROP_POSITION";
            case SDL_EventType.DROP_TEXT -> "SDL_EVENT_DROP_TEXT";
            case SDL_EventType.ENUM_PADDING -> "SDL_EVENT_ENUM_PADDING";
            case SDL_EventType.FINGER_CANCELED -> "SDL_EVENT_FINGER_CANCELED";
            case SDL_EventType.FINGER_DOWN -> "SDL_EVENT_FINGER_DOWN";
            case SDL_EventType.FINGER_MOTION -> "SDL_EVENT_FINGER_MOTION";
            case SDL_EventType.FINGER_UP -> "SDL_EVENT_FINGER_UP";
            case SDL_EventType.FIRST -> "SDL_EVENT_FIRST";
            case SDL_EventType.GAMEPAD_ADDED -> "SDL_EVENT_GAMEPAD_ADDED";
            case SDL_EventType.GAMEPAD_AXIS_MOTION -> "SDL_EVENT_GAMEPAD_AXIS_MOTION";
            case SDL_EventType.GAMEPAD_BUTTON_DOWN -> "SDL_EVENT_GAMEPAD_BUTTON_DOWN";
            case SDL_EventType.GAMEPAD_BUTTON_UP -> "SDL_EVENT_GAMEPAD_BUTTON_UP";
            case SDL_EventType.GAMEPAD_REMAPPED -> "SDL_EVENT_GAMEPAD_REMAPPED";
            case SDL_EventType.GAMEPAD_REMOVED -> "SDL_EVENT_GAMEPAD_REMOVED";
            case SDL_EventType.GAMEPAD_SENSOR_UPDATE -> "SDL_EVENT_GAMEPAD_SENSOR_UPDATE";
            case SDL_EventType.GAMEPAD_STEAM_HANDLE_UPDATED -> "SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED";
            case SDL_EventType.GAMEPAD_TOUCHPAD_DOWN -> "SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN";
            case SDL_EventType.GAMEPAD_TOUCHPAD_MOTION -> "SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION";
            case SDL_EventType.GAMEPAD_TOUCHPAD_UP -> "SDL_EVENT_GAMEPAD_TOUCHPAD_UP";
            case SDL_EventType.GAMEPAD_UPDATE_COMPLETE -> "SDL_EVENT_GAMEPAD_UPDATE_COMPLETE";
            case SDL_EventType.JOYSTICK_ADDED -> "SDL_EVENT_JOYSTICK_ADDED";
            case SDL_EventType.JOYSTICK_AXIS_MOTION -> "SDL_EVENT_JOYSTICK_AXIS_MOTION";
            case SDL_EventType.JOYSTICK_BALL_MOTION -> "SDL_EVENT_JOYSTICK_BALL_MOTION";
            case SDL_EventType.JOYSTICK_BATTERY_UPDATED -> "SDL_EVENT_JOYSTICK_BATTERY_UPDATED";
            case SDL_EventType.JOYSTICK_BUTTON_DOWN -> "SDL_EVENT_JOYSTICK_BUTTON_DOWN";
            case SDL_EventType.JOYSTICK_BUTTON_UP -> "SDL_EVENT_JOYSTICK_BUTTON_UP";
            case SDL_EventType.JOYSTICK_HAT_MOTION -> "SDL_EVENT_JOYSTICK_HAT_MOTION";
            case SDL_EventType.JOYSTICK_REMOVED -> "SDL_EVENT_JOYSTICK_REMOVED";
            case SDL_EventType.JOYSTICK_UPDATE_COMPLETE -> "SDL_EVENT_JOYSTICK_UPDATE_COMPLETE";
            case SDL_EventType.KEYBOARD_ADDED -> "SDL_EVENT_KEYBOARD_ADDED";
            case SDL_EventType.KEYBOARD_REMOVED -> "SDL_EVENT_KEYBOARD_REMOVED";
            case SDL_EventType.KEYMAP_CHANGED -> "SDL_EVENT_KEYMAP_CHANGED";
            case SDL_EventType.KEY_DOWN -> "SDL_EVENT_KEY_DOWN";
            case SDL_EventType.KEY_UP -> "SDL_EVENT_KEY_UP";
            case SDL_EventType.LAST -> "SDL_EVENT_LAST";
            case SDL_EventType.LOCALE_CHANGED -> "SDL_EVENT_LOCALE_CHANGED";
            case SDL_EventType.LOW_MEMORY -> "SDL_EVENT_LOW_MEMORY";
            case SDL_EventType.MOUSE_ADDED -> "SDL_EVENT_MOUSE_ADDED";
            case SDL_EventType.MOUSE_BUTTON_DOWN -> "SDL_EVENT_MOUSE_BUTTON_DOWN";
            case SDL_EventType.MOUSE_BUTTON_UP -> "SDL_EVENT_MOUSE_BUTTON_UP";
            case SDL_EventType.MOUSE_MOTION -> "SDL_EVENT_MOUSE_MOTION";
            case SDL_EventType.MOUSE_REMOVED -> "SDL_EVENT_MOUSE_REMOVED";
            case SDL_EventType.MOUSE_WHEEL -> "SDL_EVENT_MOUSE_WHEEL";
            case SDL_EventType.PEN_AXIS -> "SDL_EVENT_PEN_AXIS";
            case SDL_EventType.PEN_BUTTON_DOWN -> "SDL_EVENT_PEN_BUTTON_DOWN";
            case SDL_EventType.PEN_BUTTON_UP -> "SDL_EVENT_PEN_BUTTON_UP";
            case SDL_EventType.PEN_DOWN -> "SDL_EVENT_PEN_DOWN";
            case SDL_EventType.PEN_MOTION -> "SDL_EVENT_PEN_MOTION";
            case SDL_EventType.PEN_PROXIMITY_IN -> "SDL_EVENT_PEN_PROXIMITY_IN";
            case SDL_EventType.PEN_PROXIMITY_OUT -> "SDL_EVENT_PEN_PROXIMITY_OUT";
            case SDL_EventType.PEN_UP -> "SDL_EVENT_PEN_UP";
            case SDL_EventType.POLL_SENTINEL -> "SDL_EVENT_POLL_SENTINEL";
            case SDL_EventType.PRIVATE0 -> "SDL_EVENT_PRIVATE0";
            case SDL_EventType.PRIVATE1 -> "SDL_EVENT_PRIVATE1";
            case SDL_EventType.PRIVATE2 -> "SDL_EVENT_PRIVATE2";
            case SDL_EventType.PRIVATE3 -> "SDL_EVENT_PRIVATE3";
            case SDL_EventType.QUIT -> "SDL_EVENT_QUIT";
            case SDL_EventType.RENDER_DEVICE_LOST -> "SDL_EVENT_RENDER_DEVICE_LOST";
            case SDL_EventType.RENDER_DEVICE_RESET -> "SDL_EVENT_RENDER_DEVICE_RESET";
            case SDL_EventType.RENDER_TARGETS_RESET -> "SDL_EVENT_RENDER_TARGETS_RESET";
            case SDL_EventType.SENSOR_UPDATE -> "SDL_EVENT_SENSOR_UPDATE";
            case SDL_EventType.SYSTEM_THEME_CHANGED -> "SDL_EVENT_SYSTEM_THEME_CHANGED";
            case SDL_EventType.TERMINATING -> "SDL_EVENT_TERMINATING";
            case SDL_EventType.TEXT_EDITING -> "SDL_EVENT_TEXT_EDITING";
            case SDL_EventType.TEXT_EDITING_CANDIDATES -> "SDL_EVENT_TEXT_EDITING_CANDIDATES";
            case SDL_EventType.TEXT_INPUT -> "SDL_EVENT_TEXT_INPUT";
            case SDL_EventType.USER -> "SDL_EVENT_USER";
            case SDL_EventType.WILL_ENTER_BACKGROUND -> "SDL_EVENT_WILL_ENTER_BACKGROUND";
            case SDL_EventType.WILL_ENTER_FOREGROUND -> "SDL_EVENT_WILL_ENTER_FOREGROUND";
            case SDL_EventType.WINDOW_CLOSE_REQUESTED -> "SDL_EVENT_WINDOW_CLOSE_REQUESTED";
            case SDL_EventType.WINDOW_DESTROYED -> "SDL_EVENT_WINDOW_DESTROYED";
            case SDL_EventType.WINDOW_DISPLAY_CHANGED -> "SDL_EVENT_WINDOW_DISPLAY_CHANGED";
            case SDL_EventType.WINDOW_DISPLAY_SCALE_CHANGED -> "SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED";
            case SDL_EventType.WINDOW_ENTER_FULLSCREEN -> "SDL_EVENT_WINDOW_ENTER_FULLSCREEN";
            case SDL_EventType.WINDOW_EXPOSED -> "SDL_EVENT_WINDOW_EXPOSED";
            case SDL_EventType.WINDOW_FOCUS_GAINED -> "SDL_EVENT_WINDOW_FOCUS_GAINED";
            case SDL_EventType.WINDOW_FOCUS_LOST -> "SDL_EVENT_WINDOW_FOCUS_LOST";
            case SDL_EventType.WINDOW_HDR_STATE_CHANGED -> "SDL_EVENT_WINDOW_HDR_STATE_CHANGED";
            case SDL_EventType.WINDOW_HIDDEN -> "SDL_EVENT_WINDOW_HIDDEN";
            case SDL_EventType.WINDOW_HIT_TEST -> "SDL_EVENT_WINDOW_HIT_TEST";
            case SDL_EventType.WINDOW_ICCPROF_CHANGED -> "SDL_EVENT_WINDOW_ICCPROF_CHANGED";
            case SDL_EventType.WINDOW_LEAVE_FULLSCREEN -> "SDL_EVENT_WINDOW_LEAVE_FULLSCREEN";
            case SDL_EventType.WINDOW_MAXIMIZED -> "SDL_EVENT_WINDOW_MAXIMIZED";
            case SDL_EventType.WINDOW_METAL_VIEW_RESIZED -> "SDL_EVENT_WINDOW_METAL_VIEW_RESIZED";
            case SDL_EventType.WINDOW_MINIMIZED -> "SDL_EVENT_WINDOW_MINIMIZED";
            case SDL_EventType.WINDOW_MOUSE_ENTER -> "SDL_EVENT_WINDOW_MOUSE_ENTER";
            case SDL_EventType.WINDOW_MOUSE_LEAVE -> "SDL_EVENT_WINDOW_MOUSE_LEAVE";
            case SDL_EventType.WINDOW_MOVED -> "SDL_EVENT_WINDOW_MOVED";
            case SDL_EventType.WINDOW_OCCLUDED -> "SDL_EVENT_WINDOW_OCCLUDED";
            case SDL_EventType.WINDOW_PIXEL_SIZE_CHANGED -> "SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED";
            case SDL_EventType.WINDOW_RESIZED -> "SDL_EVENT_WINDOW_RESIZED";
            case SDL_EventType.WINDOW_RESTORED -> "SDL_EVENT_WINDOW_RESTORED";
            case SDL_EventType.WINDOW_SAFE_AREA_CHANGED -> "SDL_EVENT_WINDOW_SAFE_AREA_CHANGED";
            case SDL_EventType.WINDOW_SHOWN -> "SDL_EVENT_WINDOW_SHOWN";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private SDL_EventType() {}
}
