package club.doki7.sdl3.enumtype;

import club.doki7.ffm.annotation.*;

/// The SDL keyboard scancode representation.
///
/// An SDL scancode is the physical representation of a key on the keyboard,
/// independent of language and keyboard mapping.
///
/// Values of this type are used to represent keyboard keys, among other places
/// in the `scancode` field of the SDL_KeyboardEvent structure.
///
/// The values in this enumeration are based on the USB usage page standard:
/// https://usb.org/sites/default/files/hut1_5.pdf
///
/// \since This enum is available since SDL 3.2.0.
///
public final class SDL_Scancode {
    public static final int SDL_SCANCODE_UNKNOWN = 0x0;

    /// ame Usage page 0x07
    ///
    ///  These values are from usage page 0x07 (USB keyboard page).
    public static final int SDL_SCANCODE_A = 0x4;
    public static final int SDL_SCANCODE_B = 0x5;
    public static final int SDL_SCANCODE_C = 0x6;
    public static final int SDL_SCANCODE_D = 0x7;
    public static final int SDL_SCANCODE_E = 0x8;
    public static final int SDL_SCANCODE_F = 0x9;
    public static final int SDL_SCANCODE_G = 0xa;
    public static final int SDL_SCANCODE_H = 0xb;
    public static final int SDL_SCANCODE_I = 0xc;
    public static final int SDL_SCANCODE_J = 0xd;
    public static final int SDL_SCANCODE_K = 0xe;
    public static final int SDL_SCANCODE_L = 0xf;
    public static final int SDL_SCANCODE_M = 0x10;
    public static final int SDL_SCANCODE_N = 0x11;
    public static final int SDL_SCANCODE_O = 0x12;
    public static final int SDL_SCANCODE_P = 0x13;
    public static final int SDL_SCANCODE_Q = 0x14;
    public static final int SDL_SCANCODE_R = 0x15;
    public static final int SDL_SCANCODE_S = 0x16;
    public static final int SDL_SCANCODE_T = 0x17;
    public static final int SDL_SCANCODE_U = 0x18;
    public static final int SDL_SCANCODE_V = 0x19;
    public static final int SDL_SCANCODE_W = 0x1a;
    public static final int SDL_SCANCODE_X = 0x1b;
    public static final int SDL_SCANCODE_Y = 0x1c;
    public static final int SDL_SCANCODE_Z = 0x1d;
    public static final int SDL_SCANCODE_1 = 0x1e;
    public static final int SDL_SCANCODE_2 = 0x1f;
    public static final int SDL_SCANCODE_3 = 0x20;
    public static final int SDL_SCANCODE_4 = 0x21;
    public static final int SDL_SCANCODE_5 = 0x22;
    public static final int SDL_SCANCODE_6 = 0x23;
    public static final int SDL_SCANCODE_7 = 0x24;
    public static final int SDL_SCANCODE_8 = 0x25;
    public static final int SDL_SCANCODE_9 = 0x26;
    public static final int SDL_SCANCODE_0 = 0x27;
    public static final int SDL_SCANCODE_RETURN = 0x28;
    public static final int SDL_SCANCODE_ESCAPE = 0x29;
    public static final int SDL_SCANCODE_BACKSPACE = 0x2a;
    public static final int SDL_SCANCODE_TAB = 0x2b;
    public static final int SDL_SCANCODE_SPACE = 0x2c;
    public static final int SDL_SCANCODE_MINUS = 0x2d;
    public static final int SDL_SCANCODE_EQUALS = 0x2e;
    public static final int SDL_SCANCODE_LEFTBRACKET = 0x2f;
    public static final int SDL_SCANCODE_RIGHTBRACKET = 0x30;
    public static final int SDL_SCANCODE_BACKSLASH = 0x31;
    public static final int SDL_SCANCODE_NONUSHASH = 0x32;
    public static final int SDL_SCANCODE_SEMICOLON = 0x33;
    public static final int SDL_SCANCODE_APOSTROPHE = 0x34;
    public static final int SDL_SCANCODE_GRAVE = 0x35;
    public static final int SDL_SCANCODE_COMMA = 0x36;
    public static final int SDL_SCANCODE_PERIOD = 0x37;
    public static final int SDL_SCANCODE_SLASH = 0x38;
    public static final int SDL_SCANCODE_CAPSLOCK = 0x39;
    public static final int SDL_SCANCODE_F1 = 0x3a;
    public static final int SDL_SCANCODE_F2 = 0x3b;
    public static final int SDL_SCANCODE_F3 = 0x3c;
    public static final int SDL_SCANCODE_F4 = 0x3d;
    public static final int SDL_SCANCODE_F5 = 0x3e;
    public static final int SDL_SCANCODE_F6 = 0x3f;
    public static final int SDL_SCANCODE_F7 = 0x40;
    public static final int SDL_SCANCODE_F8 = 0x41;
    public static final int SDL_SCANCODE_F9 = 0x42;
    public static final int SDL_SCANCODE_F10 = 0x43;
    public static final int SDL_SCANCODE_F11 = 0x44;
    public static final int SDL_SCANCODE_F12 = 0x45;
    public static final int SDL_SCANCODE_PRINTSCREEN = 0x46;
    public static final int SDL_SCANCODE_SCROLLLOCK = 0x47;
    public static final int SDL_SCANCODE_PAUSE = 0x48;
    public static final int SDL_SCANCODE_INSERT = 0x49;
    public static final int SDL_SCANCODE_HOME = 0x4a;
    public static final int SDL_SCANCODE_PAGEUP = 0x4b;
    public static final int SDL_SCANCODE_DELETE = 0x4c;
    public static final int SDL_SCANCODE_END = 0x4d;
    public static final int SDL_SCANCODE_PAGEDOWN = 0x4e;
    public static final int SDL_SCANCODE_RIGHT = 0x4f;
    public static final int SDL_SCANCODE_LEFT = 0x50;
    public static final int SDL_SCANCODE_DOWN = 0x51;
    public static final int SDL_SCANCODE_UP = 0x52;
    public static final int SDL_SCANCODE_NUMLOCKCLEAR = 0x53;
    public static final int SDL_SCANCODE_KP_DIVIDE = 0x54;
    public static final int SDL_SCANCODE_KP_MULTIPLY = 0x55;
    public static final int SDL_SCANCODE_KP_MINUS = 0x56;
    public static final int SDL_SCANCODE_KP_PLUS = 0x57;
    public static final int SDL_SCANCODE_KP_ENTER = 0x58;
    public static final int SDL_SCANCODE_KP_1 = 0x59;
    public static final int SDL_SCANCODE_KP_2 = 0x5a;
    public static final int SDL_SCANCODE_KP_3 = 0x5b;
    public static final int SDL_SCANCODE_KP_4 = 0x5c;
    public static final int SDL_SCANCODE_KP_5 = 0x5d;
    public static final int SDL_SCANCODE_KP_6 = 0x5e;
    public static final int SDL_SCANCODE_KP_7 = 0x5f;
    public static final int SDL_SCANCODE_KP_8 = 0x60;
    public static final int SDL_SCANCODE_KP_9 = 0x61;
    public static final int SDL_SCANCODE_KP_0 = 0x62;
    public static final int SDL_SCANCODE_KP_PERIOD = 0x63;
    public static final int SDL_SCANCODE_NONUSBACKSLASH = 0x64;
    public static final int SDL_SCANCODE_APPLICATION = 0x65;
    public static final int SDL_SCANCODE_POWER = 0x66;
    public static final int SDL_SCANCODE_KP_EQUALS = 0x67;
    public static final int SDL_SCANCODE_F13 = 0x68;
    public static final int SDL_SCANCODE_F14 = 0x69;
    public static final int SDL_SCANCODE_F15 = 0x6a;
    public static final int SDL_SCANCODE_F16 = 0x6b;
    public static final int SDL_SCANCODE_F17 = 0x6c;
    public static final int SDL_SCANCODE_F18 = 0x6d;
    public static final int SDL_SCANCODE_F19 = 0x6e;
    public static final int SDL_SCANCODE_F20 = 0x6f;
    public static final int SDL_SCANCODE_F21 = 0x70;
    public static final int SDL_SCANCODE_F22 = 0x71;
    public static final int SDL_SCANCODE_F23 = 0x72;
    public static final int SDL_SCANCODE_F24 = 0x73;
    public static final int SDL_SCANCODE_EXECUTE = 0x74;
    public static final int SDL_SCANCODE_HELP = 0x75;
    public static final int SDL_SCANCODE_MENU = 0x76;
    public static final int SDL_SCANCODE_SELECT = 0x77;
    public static final int SDL_SCANCODE_STOP = 0x78;
    public static final int SDL_SCANCODE_AGAIN = 0x79;
    public static final int SDL_SCANCODE_UNDO = 0x7a;
    public static final int SDL_SCANCODE_CUT = 0x7b;
    public static final int SDL_SCANCODE_COPY = 0x7c;
    public static final int SDL_SCANCODE_PASTE = 0x7d;
    public static final int SDL_SCANCODE_FIND = 0x7e;
    public static final int SDL_SCANCODE_MUTE = 0x7f;
    public static final int SDL_SCANCODE_VOLUMEUP = 0x80;
    public static final int SDL_SCANCODE_VOLUMEDOWN = 0x81;
    public static final int SDL_SCANCODE_KP_COMMA = 0x85;
    public static final int SDL_SCANCODE_KP_EQUALSAS400 = 0x86;
    public static final int SDL_SCANCODE_INTERNATIONAL1 = 0x87;
    public static final int SDL_SCANCODE_INTERNATIONAL2 = 0x88;
    public static final int SDL_SCANCODE_INTERNATIONAL3 = 0x89;
    public static final int SDL_SCANCODE_INTERNATIONAL4 = 0x8a;
    public static final int SDL_SCANCODE_INTERNATIONAL5 = 0x8b;
    public static final int SDL_SCANCODE_INTERNATIONAL6 = 0x8c;
    public static final int SDL_SCANCODE_INTERNATIONAL7 = 0x8d;
    public static final int SDL_SCANCODE_INTERNATIONAL8 = 0x8e;
    public static final int SDL_SCANCODE_INTERNATIONAL9 = 0x8f;
    public static final int SDL_SCANCODE_LANG1 = 0x90;
    public static final int SDL_SCANCODE_LANG2 = 0x91;
    public static final int SDL_SCANCODE_LANG3 = 0x92;
    public static final int SDL_SCANCODE_LANG4 = 0x93;
    public static final int SDL_SCANCODE_LANG5 = 0x94;
    public static final int SDL_SCANCODE_LANG6 = 0x95;
    public static final int SDL_SCANCODE_LANG7 = 0x96;
    public static final int SDL_SCANCODE_LANG8 = 0x97;
    public static final int SDL_SCANCODE_LANG9 = 0x98;
    public static final int SDL_SCANCODE_ALTERASE = 0x99;
    public static final int SDL_SCANCODE_SYSREQ = 0x9a;
    public static final int SDL_SCANCODE_CANCEL = 0x9b;
    public static final int SDL_SCANCODE_CLEAR = 0x9c;
    public static final int SDL_SCANCODE_PRIOR = 0x9d;
    public static final int SDL_SCANCODE_RETURN2 = 0x9e;
    public static final int SDL_SCANCODE_SEPARATOR = 0x9f;
    public static final int SDL_SCANCODE_OUT = 0xa0;
    public static final int SDL_SCANCODE_OPER = 0xa1;
    public static final int SDL_SCANCODE_CLEARAGAIN = 0xa2;
    public static final int SDL_SCANCODE_CRSEL = 0xa3;
    public static final int SDL_SCANCODE_EXSEL = 0xa4;
    public static final int SDL_SCANCODE_KP_00 = 0xb0;
    public static final int SDL_SCANCODE_KP_000 = 0xb1;
    public static final int SDL_SCANCODE_THOUSANDSSEPARATOR = 0xb2;
    public static final int SDL_SCANCODE_DECIMALSEPARATOR = 0xb3;
    public static final int SDL_SCANCODE_CURRENCYUNIT = 0xb4;
    public static final int SDL_SCANCODE_CURRENCYSUBUNIT = 0xb5;
    public static final int SDL_SCANCODE_KP_LEFTPAREN = 0xb6;
    public static final int SDL_SCANCODE_KP_RIGHTPAREN = 0xb7;
    public static final int SDL_SCANCODE_KP_LEFTBRACE = 0xb8;
    public static final int SDL_SCANCODE_KP_RIGHTBRACE = 0xb9;
    public static final int SDL_SCANCODE_KP_TAB = 0xba;
    public static final int SDL_SCANCODE_KP_BACKSPACE = 0xbb;
    public static final int SDL_SCANCODE_KP_A = 0xbc;
    public static final int SDL_SCANCODE_KP_B = 0xbd;
    public static final int SDL_SCANCODE_KP_C = 0xbe;
    public static final int SDL_SCANCODE_KP_D = 0xbf;
    public static final int SDL_SCANCODE_KP_E = 0xc0;
    public static final int SDL_SCANCODE_KP_F = 0xc1;
    public static final int SDL_SCANCODE_KP_XOR = 0xc2;
    public static final int SDL_SCANCODE_KP_POWER = 0xc3;
    public static final int SDL_SCANCODE_KP_PERCENT = 0xc4;
    public static final int SDL_SCANCODE_KP_LESS = 0xc5;
    public static final int SDL_SCANCODE_KP_GREATER = 0xc6;
    public static final int SDL_SCANCODE_KP_AMPERSAND = 0xc7;
    public static final int SDL_SCANCODE_KP_DBLAMPERSAND = 0xc8;
    public static final int SDL_SCANCODE_KP_VERTICALBAR = 0xc9;
    public static final int SDL_SCANCODE_KP_DBLVERTICALBAR = 0xca;
    public static final int SDL_SCANCODE_KP_COLON = 0xcb;
    public static final int SDL_SCANCODE_KP_HASH = 0xcc;
    public static final int SDL_SCANCODE_KP_SPACE = 0xcd;
    public static final int SDL_SCANCODE_KP_AT = 0xce;
    public static final int SDL_SCANCODE_KP_EXCLAM = 0xcf;
    public static final int SDL_SCANCODE_KP_MEMSTORE = 0xd0;
    public static final int SDL_SCANCODE_KP_MEMRECALL = 0xd1;
    public static final int SDL_SCANCODE_KP_MEMCLEAR = 0xd2;
    public static final int SDL_SCANCODE_KP_MEMADD = 0xd3;
    public static final int SDL_SCANCODE_KP_MEMSUBTRACT = 0xd4;
    public static final int SDL_SCANCODE_KP_MEMMULTIPLY = 0xd5;
    public static final int SDL_SCANCODE_KP_MEMDIVIDE = 0xd6;
    public static final int SDL_SCANCODE_KP_PLUSMINUS = 0xd7;
    public static final int SDL_SCANCODE_KP_CLEAR = 0xd8;
    public static final int SDL_SCANCODE_KP_CLEARENTRY = 0xd9;
    public static final int SDL_SCANCODE_KP_BINARY = 0xda;
    public static final int SDL_SCANCODE_KP_OCTAL = 0xdb;
    public static final int SDL_SCANCODE_KP_DECIMAL = 0xdc;
    public static final int SDL_SCANCODE_KP_HEXADECIMAL = 0xdd;
    public static final int SDL_SCANCODE_LCTRL = 0xe0;
    public static final int SDL_SCANCODE_LSHIFT = 0xe1;
    public static final int SDL_SCANCODE_LALT = 0xe2;
    public static final int SDL_SCANCODE_LGUI = 0xe3;
    public static final int SDL_SCANCODE_RCTRL = 0xe4;
    public static final int SDL_SCANCODE_RSHIFT = 0xe5;
    public static final int SDL_SCANCODE_RALT = 0xe6;
    public static final int SDL_SCANCODE_RGUI = 0xe7;
    public static final int SDL_SCANCODE_MODE = 0x101;

    /// ame Usage page 0x0C
    ///
    ///  These values are mapped from usage page 0x0C (USB consumer page).
    ///
    ///  There are way more keys in the spec than we can represent in the
    ///  current scancode range, so pick the ones that commonly come up in
    ///  real world usage.
    public static final int SDL_SCANCODE_SLEEP = 0x102;
    public static final int SDL_SCANCODE_WAKE = 0x103;
    public static final int SDL_SCANCODE_CHANNEL_INCREMENT = 0x104;
    public static final int SDL_SCANCODE_CHANNEL_DECREMENT = 0x105;
    public static final int SDL_SCANCODE_MEDIA_PLAY = 0x106;
    public static final int SDL_SCANCODE_MEDIA_PAUSE = 0x107;
    public static final int SDL_SCANCODE_MEDIA_RECORD = 0x108;
    public static final int SDL_SCANCODE_MEDIA_FAST_FORWARD = 0x109;
    public static final int SDL_SCANCODE_MEDIA_REWIND = 0x10a;
    public static final int SDL_SCANCODE_MEDIA_NEXT_TRACK = 0x10b;
    public static final int SDL_SCANCODE_MEDIA_PREVIOUS_TRACK = 0x10c;
    public static final int SDL_SCANCODE_MEDIA_STOP = 0x10d;
    public static final int SDL_SCANCODE_MEDIA_EJECT = 0x10e;
    public static final int SDL_SCANCODE_MEDIA_PLAY_PAUSE = 0x10f;
    public static final int SDL_SCANCODE_MEDIA_SELECT = 0x110;
    public static final int SDL_SCANCODE_AC_NEW = 0x111;
    public static final int SDL_SCANCODE_AC_OPEN = 0x112;
    public static final int SDL_SCANCODE_AC_CLOSE = 0x113;
    public static final int SDL_SCANCODE_AC_EXIT = 0x114;
    public static final int SDL_SCANCODE_AC_SAVE = 0x115;
    public static final int SDL_SCANCODE_AC_PRINT = 0x116;
    public static final int SDL_SCANCODE_AC_PROPERTIES = 0x117;
    public static final int SDL_SCANCODE_AC_SEARCH = 0x118;
    public static final int SDL_SCANCODE_AC_HOME = 0x119;
    public static final int SDL_SCANCODE_AC_BACK = 0x11a;
    public static final int SDL_SCANCODE_AC_FORWARD = 0x11b;
    public static final int SDL_SCANCODE_AC_STOP = 0x11c;
    public static final int SDL_SCANCODE_AC_REFRESH = 0x11d;
    public static final int SDL_SCANCODE_AC_BOOKMARKS = 0x11e;

    /// ame Mobile keys
    ///
    ///  These are values that are often used on mobile phones.
    public static final int SDL_SCANCODE_SOFTLEFT = 0x11f;
    public static final int SDL_SCANCODE_SOFTRIGHT = 0x120;
    public static final int SDL_SCANCODE_CALL = 0x121;
    public static final int SDL_SCANCODE_ENDCALL = 0x122;
    public static final int SDL_SCANCODE_RESERVED = 0x190;
    public static final int SDL_SCANCODE_COUNT = 0x200;

    public static String explain(@EnumType(SDL_Scancode.class) int value) {
        return switch (value) {
            case SDL_Scancode.SDL_SCANCODE_0 -> "SDL_SCANCODE_0";
            case SDL_Scancode.SDL_SCANCODE_1 -> "SDL_SCANCODE_1";
            case SDL_Scancode.SDL_SCANCODE_2 -> "SDL_SCANCODE_2";
            case SDL_Scancode.SDL_SCANCODE_3 -> "SDL_SCANCODE_3";
            case SDL_Scancode.SDL_SCANCODE_4 -> "SDL_SCANCODE_4";
            case SDL_Scancode.SDL_SCANCODE_5 -> "SDL_SCANCODE_5";
            case SDL_Scancode.SDL_SCANCODE_6 -> "SDL_SCANCODE_6";
            case SDL_Scancode.SDL_SCANCODE_7 -> "SDL_SCANCODE_7";
            case SDL_Scancode.SDL_SCANCODE_8 -> "SDL_SCANCODE_8";
            case SDL_Scancode.SDL_SCANCODE_9 -> "SDL_SCANCODE_9";
            case SDL_Scancode.SDL_SCANCODE_A -> "SDL_SCANCODE_A";
            case SDL_Scancode.SDL_SCANCODE_AC_BACK -> "SDL_SCANCODE_AC_BACK";
            case SDL_Scancode.SDL_SCANCODE_AC_BOOKMARKS -> "SDL_SCANCODE_AC_BOOKMARKS";
            case SDL_Scancode.SDL_SCANCODE_AC_CLOSE -> "SDL_SCANCODE_AC_CLOSE";
            case SDL_Scancode.SDL_SCANCODE_AC_EXIT -> "SDL_SCANCODE_AC_EXIT";
            case SDL_Scancode.SDL_SCANCODE_AC_FORWARD -> "SDL_SCANCODE_AC_FORWARD";
            case SDL_Scancode.SDL_SCANCODE_AC_HOME -> "SDL_SCANCODE_AC_HOME";
            case SDL_Scancode.SDL_SCANCODE_AC_NEW -> "SDL_SCANCODE_AC_NEW";
            case SDL_Scancode.SDL_SCANCODE_AC_OPEN -> "SDL_SCANCODE_AC_OPEN";
            case SDL_Scancode.SDL_SCANCODE_AC_PRINT -> "SDL_SCANCODE_AC_PRINT";
            case SDL_Scancode.SDL_SCANCODE_AC_PROPERTIES -> "SDL_SCANCODE_AC_PROPERTIES";
            case SDL_Scancode.SDL_SCANCODE_AC_REFRESH -> "SDL_SCANCODE_AC_REFRESH";
            case SDL_Scancode.SDL_SCANCODE_AC_SAVE -> "SDL_SCANCODE_AC_SAVE";
            case SDL_Scancode.SDL_SCANCODE_AC_SEARCH -> "SDL_SCANCODE_AC_SEARCH";
            case SDL_Scancode.SDL_SCANCODE_AC_STOP -> "SDL_SCANCODE_AC_STOP";
            case SDL_Scancode.SDL_SCANCODE_AGAIN -> "SDL_SCANCODE_AGAIN";
            case SDL_Scancode.SDL_SCANCODE_ALTERASE -> "SDL_SCANCODE_ALTERASE";
            case SDL_Scancode.SDL_SCANCODE_APOSTROPHE -> "SDL_SCANCODE_APOSTROPHE";
            case SDL_Scancode.SDL_SCANCODE_APPLICATION -> "SDL_SCANCODE_APPLICATION";
            case SDL_Scancode.SDL_SCANCODE_B -> "SDL_SCANCODE_B";
            case SDL_Scancode.SDL_SCANCODE_BACKSLASH -> "SDL_SCANCODE_BACKSLASH";
            case SDL_Scancode.SDL_SCANCODE_BACKSPACE -> "SDL_SCANCODE_BACKSPACE";
            case SDL_Scancode.SDL_SCANCODE_C -> "SDL_SCANCODE_C";
            case SDL_Scancode.SDL_SCANCODE_CALL -> "SDL_SCANCODE_CALL";
            case SDL_Scancode.SDL_SCANCODE_CANCEL -> "SDL_SCANCODE_CANCEL";
            case SDL_Scancode.SDL_SCANCODE_CAPSLOCK -> "SDL_SCANCODE_CAPSLOCK";
            case SDL_Scancode.SDL_SCANCODE_CHANNEL_DECREMENT -> "SDL_SCANCODE_CHANNEL_DECREMENT";
            case SDL_Scancode.SDL_SCANCODE_CHANNEL_INCREMENT -> "SDL_SCANCODE_CHANNEL_INCREMENT";
            case SDL_Scancode.SDL_SCANCODE_CLEAR -> "SDL_SCANCODE_CLEAR";
            case SDL_Scancode.SDL_SCANCODE_CLEARAGAIN -> "SDL_SCANCODE_CLEARAGAIN";
            case SDL_Scancode.SDL_SCANCODE_COMMA -> "SDL_SCANCODE_COMMA";
            case SDL_Scancode.SDL_SCANCODE_COPY -> "SDL_SCANCODE_COPY";
            case SDL_Scancode.SDL_SCANCODE_COUNT -> "SDL_SCANCODE_COUNT";
            case SDL_Scancode.SDL_SCANCODE_CRSEL -> "SDL_SCANCODE_CRSEL";
            case SDL_Scancode.SDL_SCANCODE_CURRENCYSUBUNIT -> "SDL_SCANCODE_CURRENCYSUBUNIT";
            case SDL_Scancode.SDL_SCANCODE_CURRENCYUNIT -> "SDL_SCANCODE_CURRENCYUNIT";
            case SDL_Scancode.SDL_SCANCODE_CUT -> "SDL_SCANCODE_CUT";
            case SDL_Scancode.SDL_SCANCODE_D -> "SDL_SCANCODE_D";
            case SDL_Scancode.SDL_SCANCODE_DECIMALSEPARATOR -> "SDL_SCANCODE_DECIMALSEPARATOR";
            case SDL_Scancode.SDL_SCANCODE_DELETE -> "SDL_SCANCODE_DELETE";
            case SDL_Scancode.SDL_SCANCODE_DOWN -> "SDL_SCANCODE_DOWN";
            case SDL_Scancode.SDL_SCANCODE_E -> "SDL_SCANCODE_E";
            case SDL_Scancode.SDL_SCANCODE_END -> "SDL_SCANCODE_END";
            case SDL_Scancode.SDL_SCANCODE_ENDCALL -> "SDL_SCANCODE_ENDCALL";
            case SDL_Scancode.SDL_SCANCODE_EQUALS -> "SDL_SCANCODE_EQUALS";
            case SDL_Scancode.SDL_SCANCODE_ESCAPE -> "SDL_SCANCODE_ESCAPE";
            case SDL_Scancode.SDL_SCANCODE_EXECUTE -> "SDL_SCANCODE_EXECUTE";
            case SDL_Scancode.SDL_SCANCODE_EXSEL -> "SDL_SCANCODE_EXSEL";
            case SDL_Scancode.SDL_SCANCODE_F -> "SDL_SCANCODE_F";
            case SDL_Scancode.SDL_SCANCODE_F1 -> "SDL_SCANCODE_F1";
            case SDL_Scancode.SDL_SCANCODE_F10 -> "SDL_SCANCODE_F10";
            case SDL_Scancode.SDL_SCANCODE_F11 -> "SDL_SCANCODE_F11";
            case SDL_Scancode.SDL_SCANCODE_F12 -> "SDL_SCANCODE_F12";
            case SDL_Scancode.SDL_SCANCODE_F13 -> "SDL_SCANCODE_F13";
            case SDL_Scancode.SDL_SCANCODE_F14 -> "SDL_SCANCODE_F14";
            case SDL_Scancode.SDL_SCANCODE_F15 -> "SDL_SCANCODE_F15";
            case SDL_Scancode.SDL_SCANCODE_F16 -> "SDL_SCANCODE_F16";
            case SDL_Scancode.SDL_SCANCODE_F17 -> "SDL_SCANCODE_F17";
            case SDL_Scancode.SDL_SCANCODE_F18 -> "SDL_SCANCODE_F18";
            case SDL_Scancode.SDL_SCANCODE_F19 -> "SDL_SCANCODE_F19";
            case SDL_Scancode.SDL_SCANCODE_F2 -> "SDL_SCANCODE_F2";
            case SDL_Scancode.SDL_SCANCODE_F20 -> "SDL_SCANCODE_F20";
            case SDL_Scancode.SDL_SCANCODE_F21 -> "SDL_SCANCODE_F21";
            case SDL_Scancode.SDL_SCANCODE_F22 -> "SDL_SCANCODE_F22";
            case SDL_Scancode.SDL_SCANCODE_F23 -> "SDL_SCANCODE_F23";
            case SDL_Scancode.SDL_SCANCODE_F24 -> "SDL_SCANCODE_F24";
            case SDL_Scancode.SDL_SCANCODE_F3 -> "SDL_SCANCODE_F3";
            case SDL_Scancode.SDL_SCANCODE_F4 -> "SDL_SCANCODE_F4";
            case SDL_Scancode.SDL_SCANCODE_F5 -> "SDL_SCANCODE_F5";
            case SDL_Scancode.SDL_SCANCODE_F6 -> "SDL_SCANCODE_F6";
            case SDL_Scancode.SDL_SCANCODE_F7 -> "SDL_SCANCODE_F7";
            case SDL_Scancode.SDL_SCANCODE_F8 -> "SDL_SCANCODE_F8";
            case SDL_Scancode.SDL_SCANCODE_F9 -> "SDL_SCANCODE_F9";
            case SDL_Scancode.SDL_SCANCODE_FIND -> "SDL_SCANCODE_FIND";
            case SDL_Scancode.SDL_SCANCODE_G -> "SDL_SCANCODE_G";
            case SDL_Scancode.SDL_SCANCODE_GRAVE -> "SDL_SCANCODE_GRAVE";
            case SDL_Scancode.SDL_SCANCODE_H -> "SDL_SCANCODE_H";
            case SDL_Scancode.SDL_SCANCODE_HELP -> "SDL_SCANCODE_HELP";
            case SDL_Scancode.SDL_SCANCODE_HOME -> "SDL_SCANCODE_HOME";
            case SDL_Scancode.SDL_SCANCODE_I -> "SDL_SCANCODE_I";
            case SDL_Scancode.SDL_SCANCODE_INSERT -> "SDL_SCANCODE_INSERT";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL1 -> "SDL_SCANCODE_INTERNATIONAL1";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL2 -> "SDL_SCANCODE_INTERNATIONAL2";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL3 -> "SDL_SCANCODE_INTERNATIONAL3";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL4 -> "SDL_SCANCODE_INTERNATIONAL4";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL5 -> "SDL_SCANCODE_INTERNATIONAL5";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL6 -> "SDL_SCANCODE_INTERNATIONAL6";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL7 -> "SDL_SCANCODE_INTERNATIONAL7";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL8 -> "SDL_SCANCODE_INTERNATIONAL8";
            case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL9 -> "SDL_SCANCODE_INTERNATIONAL9";
            case SDL_Scancode.SDL_SCANCODE_J -> "SDL_SCANCODE_J";
            case SDL_Scancode.SDL_SCANCODE_K -> "SDL_SCANCODE_K";
            case SDL_Scancode.SDL_SCANCODE_KP_0 -> "SDL_SCANCODE_KP_0";
            case SDL_Scancode.SDL_SCANCODE_KP_00 -> "SDL_SCANCODE_KP_00";
            case SDL_Scancode.SDL_SCANCODE_KP_000 -> "SDL_SCANCODE_KP_000";
            case SDL_Scancode.SDL_SCANCODE_KP_1 -> "SDL_SCANCODE_KP_1";
            case SDL_Scancode.SDL_SCANCODE_KP_2 -> "SDL_SCANCODE_KP_2";
            case SDL_Scancode.SDL_SCANCODE_KP_3 -> "SDL_SCANCODE_KP_3";
            case SDL_Scancode.SDL_SCANCODE_KP_4 -> "SDL_SCANCODE_KP_4";
            case SDL_Scancode.SDL_SCANCODE_KP_5 -> "SDL_SCANCODE_KP_5";
            case SDL_Scancode.SDL_SCANCODE_KP_6 -> "SDL_SCANCODE_KP_6";
            case SDL_Scancode.SDL_SCANCODE_KP_7 -> "SDL_SCANCODE_KP_7";
            case SDL_Scancode.SDL_SCANCODE_KP_8 -> "SDL_SCANCODE_KP_8";
            case SDL_Scancode.SDL_SCANCODE_KP_9 -> "SDL_SCANCODE_KP_9";
            case SDL_Scancode.SDL_SCANCODE_KP_A -> "SDL_SCANCODE_KP_A";
            case SDL_Scancode.SDL_SCANCODE_KP_AMPERSAND -> "SDL_SCANCODE_KP_AMPERSAND";
            case SDL_Scancode.SDL_SCANCODE_KP_AT -> "SDL_SCANCODE_KP_AT";
            case SDL_Scancode.SDL_SCANCODE_KP_B -> "SDL_SCANCODE_KP_B";
            case SDL_Scancode.SDL_SCANCODE_KP_BACKSPACE -> "SDL_SCANCODE_KP_BACKSPACE";
            case SDL_Scancode.SDL_SCANCODE_KP_BINARY -> "SDL_SCANCODE_KP_BINARY";
            case SDL_Scancode.SDL_SCANCODE_KP_C -> "SDL_SCANCODE_KP_C";
            case SDL_Scancode.SDL_SCANCODE_KP_CLEAR -> "SDL_SCANCODE_KP_CLEAR";
            case SDL_Scancode.SDL_SCANCODE_KP_CLEARENTRY -> "SDL_SCANCODE_KP_CLEARENTRY";
            case SDL_Scancode.SDL_SCANCODE_KP_COLON -> "SDL_SCANCODE_KP_COLON";
            case SDL_Scancode.SDL_SCANCODE_KP_COMMA -> "SDL_SCANCODE_KP_COMMA";
            case SDL_Scancode.SDL_SCANCODE_KP_D -> "SDL_SCANCODE_KP_D";
            case SDL_Scancode.SDL_SCANCODE_KP_DBLAMPERSAND -> "SDL_SCANCODE_KP_DBLAMPERSAND";
            case SDL_Scancode.SDL_SCANCODE_KP_DBLVERTICALBAR -> "SDL_SCANCODE_KP_DBLVERTICALBAR";
            case SDL_Scancode.SDL_SCANCODE_KP_DECIMAL -> "SDL_SCANCODE_KP_DECIMAL";
            case SDL_Scancode.SDL_SCANCODE_KP_DIVIDE -> "SDL_SCANCODE_KP_DIVIDE";
            case SDL_Scancode.SDL_SCANCODE_KP_E -> "SDL_SCANCODE_KP_E";
            case SDL_Scancode.SDL_SCANCODE_KP_ENTER -> "SDL_SCANCODE_KP_ENTER";
            case SDL_Scancode.SDL_SCANCODE_KP_EQUALS -> "SDL_SCANCODE_KP_EQUALS";
            case SDL_Scancode.SDL_SCANCODE_KP_EQUALSAS400 -> "SDL_SCANCODE_KP_EQUALSAS400";
            case SDL_Scancode.SDL_SCANCODE_KP_EXCLAM -> "SDL_SCANCODE_KP_EXCLAM";
            case SDL_Scancode.SDL_SCANCODE_KP_F -> "SDL_SCANCODE_KP_F";
            case SDL_Scancode.SDL_SCANCODE_KP_GREATER -> "SDL_SCANCODE_KP_GREATER";
            case SDL_Scancode.SDL_SCANCODE_KP_HASH -> "SDL_SCANCODE_KP_HASH";
            case SDL_Scancode.SDL_SCANCODE_KP_HEXADECIMAL -> "SDL_SCANCODE_KP_HEXADECIMAL";
            case SDL_Scancode.SDL_SCANCODE_KP_LEFTBRACE -> "SDL_SCANCODE_KP_LEFTBRACE";
            case SDL_Scancode.SDL_SCANCODE_KP_LEFTPAREN -> "SDL_SCANCODE_KP_LEFTPAREN";
            case SDL_Scancode.SDL_SCANCODE_KP_LESS -> "SDL_SCANCODE_KP_LESS";
            case SDL_Scancode.SDL_SCANCODE_KP_MEMADD -> "SDL_SCANCODE_KP_MEMADD";
            case SDL_Scancode.SDL_SCANCODE_KP_MEMCLEAR -> "SDL_SCANCODE_KP_MEMCLEAR";
            case SDL_Scancode.SDL_SCANCODE_KP_MEMDIVIDE -> "SDL_SCANCODE_KP_MEMDIVIDE";
            case SDL_Scancode.SDL_SCANCODE_KP_MEMMULTIPLY -> "SDL_SCANCODE_KP_MEMMULTIPLY";
            case SDL_Scancode.SDL_SCANCODE_KP_MEMRECALL -> "SDL_SCANCODE_KP_MEMRECALL";
            case SDL_Scancode.SDL_SCANCODE_KP_MEMSTORE -> "SDL_SCANCODE_KP_MEMSTORE";
            case SDL_Scancode.SDL_SCANCODE_KP_MEMSUBTRACT -> "SDL_SCANCODE_KP_MEMSUBTRACT";
            case SDL_Scancode.SDL_SCANCODE_KP_MINUS -> "SDL_SCANCODE_KP_MINUS";
            case SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY -> "SDL_SCANCODE_KP_MULTIPLY";
            case SDL_Scancode.SDL_SCANCODE_KP_OCTAL -> "SDL_SCANCODE_KP_OCTAL";
            case SDL_Scancode.SDL_SCANCODE_KP_PERCENT -> "SDL_SCANCODE_KP_PERCENT";
            case SDL_Scancode.SDL_SCANCODE_KP_PERIOD -> "SDL_SCANCODE_KP_PERIOD";
            case SDL_Scancode.SDL_SCANCODE_KP_PLUS -> "SDL_SCANCODE_KP_PLUS";
            case SDL_Scancode.SDL_SCANCODE_KP_PLUSMINUS -> "SDL_SCANCODE_KP_PLUSMINUS";
            case SDL_Scancode.SDL_SCANCODE_KP_POWER -> "SDL_SCANCODE_KP_POWER";
            case SDL_Scancode.SDL_SCANCODE_KP_RIGHTBRACE -> "SDL_SCANCODE_KP_RIGHTBRACE";
            case SDL_Scancode.SDL_SCANCODE_KP_RIGHTPAREN -> "SDL_SCANCODE_KP_RIGHTPAREN";
            case SDL_Scancode.SDL_SCANCODE_KP_SPACE -> "SDL_SCANCODE_KP_SPACE";
            case SDL_Scancode.SDL_SCANCODE_KP_TAB -> "SDL_SCANCODE_KP_TAB";
            case SDL_Scancode.SDL_SCANCODE_KP_VERTICALBAR -> "SDL_SCANCODE_KP_VERTICALBAR";
            case SDL_Scancode.SDL_SCANCODE_KP_XOR -> "SDL_SCANCODE_KP_XOR";
            case SDL_Scancode.SDL_SCANCODE_L -> "SDL_SCANCODE_L";
            case SDL_Scancode.SDL_SCANCODE_LALT -> "SDL_SCANCODE_LALT";
            case SDL_Scancode.SDL_SCANCODE_LANG1 -> "SDL_SCANCODE_LANG1";
            case SDL_Scancode.SDL_SCANCODE_LANG2 -> "SDL_SCANCODE_LANG2";
            case SDL_Scancode.SDL_SCANCODE_LANG3 -> "SDL_SCANCODE_LANG3";
            case SDL_Scancode.SDL_SCANCODE_LANG4 -> "SDL_SCANCODE_LANG4";
            case SDL_Scancode.SDL_SCANCODE_LANG5 -> "SDL_SCANCODE_LANG5";
            case SDL_Scancode.SDL_SCANCODE_LANG6 -> "SDL_SCANCODE_LANG6";
            case SDL_Scancode.SDL_SCANCODE_LANG7 -> "SDL_SCANCODE_LANG7";
            case SDL_Scancode.SDL_SCANCODE_LANG8 -> "SDL_SCANCODE_LANG8";
            case SDL_Scancode.SDL_SCANCODE_LANG9 -> "SDL_SCANCODE_LANG9";
            case SDL_Scancode.SDL_SCANCODE_LCTRL -> "SDL_SCANCODE_LCTRL";
            case SDL_Scancode.SDL_SCANCODE_LEFT -> "SDL_SCANCODE_LEFT";
            case SDL_Scancode.SDL_SCANCODE_LEFTBRACKET -> "SDL_SCANCODE_LEFTBRACKET";
            case SDL_Scancode.SDL_SCANCODE_LGUI -> "SDL_SCANCODE_LGUI";
            case SDL_Scancode.SDL_SCANCODE_LSHIFT -> "SDL_SCANCODE_LSHIFT";
            case SDL_Scancode.SDL_SCANCODE_M -> "SDL_SCANCODE_M";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_EJECT -> "SDL_SCANCODE_MEDIA_EJECT";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_FAST_FORWARD -> "SDL_SCANCODE_MEDIA_FAST_FORWARD";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_NEXT_TRACK -> "SDL_SCANCODE_MEDIA_NEXT_TRACK";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_PAUSE -> "SDL_SCANCODE_MEDIA_PAUSE";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_PLAY -> "SDL_SCANCODE_MEDIA_PLAY";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_PLAY_PAUSE -> "SDL_SCANCODE_MEDIA_PLAY_PAUSE";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_PREVIOUS_TRACK -> "SDL_SCANCODE_MEDIA_PREVIOUS_TRACK";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_RECORD -> "SDL_SCANCODE_MEDIA_RECORD";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_REWIND -> "SDL_SCANCODE_MEDIA_REWIND";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_SELECT -> "SDL_SCANCODE_MEDIA_SELECT";
            case SDL_Scancode.SDL_SCANCODE_MEDIA_STOP -> "SDL_SCANCODE_MEDIA_STOP";
            case SDL_Scancode.SDL_SCANCODE_MENU -> "SDL_SCANCODE_MENU";
            case SDL_Scancode.SDL_SCANCODE_MINUS -> "SDL_SCANCODE_MINUS";
            case SDL_Scancode.SDL_SCANCODE_MODE -> "SDL_SCANCODE_MODE";
            case SDL_Scancode.SDL_SCANCODE_MUTE -> "SDL_SCANCODE_MUTE";
            case SDL_Scancode.SDL_SCANCODE_N -> "SDL_SCANCODE_N";
            case SDL_Scancode.SDL_SCANCODE_NONUSBACKSLASH -> "SDL_SCANCODE_NONUSBACKSLASH";
            case SDL_Scancode.SDL_SCANCODE_NONUSHASH -> "SDL_SCANCODE_NONUSHASH";
            case SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR -> "SDL_SCANCODE_NUMLOCKCLEAR";
            case SDL_Scancode.SDL_SCANCODE_O -> "SDL_SCANCODE_O";
            case SDL_Scancode.SDL_SCANCODE_OPER -> "SDL_SCANCODE_OPER";
            case SDL_Scancode.SDL_SCANCODE_OUT -> "SDL_SCANCODE_OUT";
            case SDL_Scancode.SDL_SCANCODE_P -> "SDL_SCANCODE_P";
            case SDL_Scancode.SDL_SCANCODE_PAGEDOWN -> "SDL_SCANCODE_PAGEDOWN";
            case SDL_Scancode.SDL_SCANCODE_PAGEUP -> "SDL_SCANCODE_PAGEUP";
            case SDL_Scancode.SDL_SCANCODE_PASTE -> "SDL_SCANCODE_PASTE";
            case SDL_Scancode.SDL_SCANCODE_PAUSE -> "SDL_SCANCODE_PAUSE";
            case SDL_Scancode.SDL_SCANCODE_PERIOD -> "SDL_SCANCODE_PERIOD";
            case SDL_Scancode.SDL_SCANCODE_POWER -> "SDL_SCANCODE_POWER";
            case SDL_Scancode.SDL_SCANCODE_PRINTSCREEN -> "SDL_SCANCODE_PRINTSCREEN";
            case SDL_Scancode.SDL_SCANCODE_PRIOR -> "SDL_SCANCODE_PRIOR";
            case SDL_Scancode.SDL_SCANCODE_Q -> "SDL_SCANCODE_Q";
            case SDL_Scancode.SDL_SCANCODE_R -> "SDL_SCANCODE_R";
            case SDL_Scancode.SDL_SCANCODE_RALT -> "SDL_SCANCODE_RALT";
            case SDL_Scancode.SDL_SCANCODE_RCTRL -> "SDL_SCANCODE_RCTRL";
            case SDL_Scancode.SDL_SCANCODE_RESERVED -> "SDL_SCANCODE_RESERVED";
            case SDL_Scancode.SDL_SCANCODE_RETURN -> "SDL_SCANCODE_RETURN";
            case SDL_Scancode.SDL_SCANCODE_RETURN2 -> "SDL_SCANCODE_RETURN2";
            case SDL_Scancode.SDL_SCANCODE_RGUI -> "SDL_SCANCODE_RGUI";
            case SDL_Scancode.SDL_SCANCODE_RIGHT -> "SDL_SCANCODE_RIGHT";
            case SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET -> "SDL_SCANCODE_RIGHTBRACKET";
            case SDL_Scancode.SDL_SCANCODE_RSHIFT -> "SDL_SCANCODE_RSHIFT";
            case SDL_Scancode.SDL_SCANCODE_S -> "SDL_SCANCODE_S";
            case SDL_Scancode.SDL_SCANCODE_SCROLLLOCK -> "SDL_SCANCODE_SCROLLLOCK";
            case SDL_Scancode.SDL_SCANCODE_SELECT -> "SDL_SCANCODE_SELECT";
            case SDL_Scancode.SDL_SCANCODE_SEMICOLON -> "SDL_SCANCODE_SEMICOLON";
            case SDL_Scancode.SDL_SCANCODE_SEPARATOR -> "SDL_SCANCODE_SEPARATOR";
            case SDL_Scancode.SDL_SCANCODE_SLASH -> "SDL_SCANCODE_SLASH";
            case SDL_Scancode.SDL_SCANCODE_SLEEP -> "SDL_SCANCODE_SLEEP";
            case SDL_Scancode.SDL_SCANCODE_SOFTLEFT -> "SDL_SCANCODE_SOFTLEFT";
            case SDL_Scancode.SDL_SCANCODE_SOFTRIGHT -> "SDL_SCANCODE_SOFTRIGHT";
            case SDL_Scancode.SDL_SCANCODE_SPACE -> "SDL_SCANCODE_SPACE";
            case SDL_Scancode.SDL_SCANCODE_STOP -> "SDL_SCANCODE_STOP";
            case SDL_Scancode.SDL_SCANCODE_SYSREQ -> "SDL_SCANCODE_SYSREQ";
            case SDL_Scancode.SDL_SCANCODE_T -> "SDL_SCANCODE_T";
            case SDL_Scancode.SDL_SCANCODE_TAB -> "SDL_SCANCODE_TAB";
            case SDL_Scancode.SDL_SCANCODE_THOUSANDSSEPARATOR -> "SDL_SCANCODE_THOUSANDSSEPARATOR";
            case SDL_Scancode.SDL_SCANCODE_U -> "SDL_SCANCODE_U";
            case SDL_Scancode.SDL_SCANCODE_UNDO -> "SDL_SCANCODE_UNDO";
            case SDL_Scancode.SDL_SCANCODE_UNKNOWN -> "SDL_SCANCODE_UNKNOWN";
            case SDL_Scancode.SDL_SCANCODE_UP -> "SDL_SCANCODE_UP";
            case SDL_Scancode.SDL_SCANCODE_V -> "SDL_SCANCODE_V";
            case SDL_Scancode.SDL_SCANCODE_VOLUMEDOWN -> "SDL_SCANCODE_VOLUMEDOWN";
            case SDL_Scancode.SDL_SCANCODE_VOLUMEUP -> "SDL_SCANCODE_VOLUMEUP";
            case SDL_Scancode.SDL_SCANCODE_W -> "SDL_SCANCODE_W";
            case SDL_Scancode.SDL_SCANCODE_WAKE -> "SDL_SCANCODE_WAKE";
            case SDL_Scancode.SDL_SCANCODE_X -> "SDL_SCANCODE_X";
            case SDL_Scancode.SDL_SCANCODE_Y -> "SDL_SCANCODE_Y";
            case SDL_Scancode.SDL_SCANCODE_Z -> "SDL_SCANCODE_Z";
            default -> "UNKNOWN(" + value + ")";
        };
    }

    /// Constructing this class is nonsense so the constructor is made private.
    private SDL_Scancode() {}
}
