name: Website Deploy

on:
  push:
    branches: ["dont-run-this-workflow-automatically-on-push-please-anyway"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.51/mdbook-v0.4.51-x86_64-unknown-linux-musl.tar.gz
          tar -xvf mdbook-v0.4.51-x86_64-unknown-linux-musl.tar.gz
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23' # Our JavaDoc works best with JDK 23, very funny.
          distribution: 'liberica'
          cache: maven
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Generate JavaDoc
        run: mvn -B site --file pom.xml || true
      - name: Build mdbook
        run: ../../../mdbook build
        working-directory: ./tutorial/mdbook/en
      - name: Copy mdbook output to JavaDoc directory
        run: |
          mkdir -p ./target/site/apidocs/tutorial
          mkdir -p ./target/site/apidocs/tutorial/en
          cp -r ./tutorial/mdbook/en/book/* ./target/site/apidocs/tutorial/en/
          cp -r ./tutorial/mdbook/images ./target/site/apidocs/tutorial/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/site/apidocs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
